In [1]:
import pandas as pd
import requests 
import json
import os
import networkx as nx

import matplotlib.pyplot as plt
#from wordcloud import WordCloud

from collections import defaultdict
import spacy
#import Functions as fn
#import seaborn as sns
import numpy as np  

import re

In [2]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /home/jovyan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
nlp = spacy.load("en_core_sci_sm")

/opt/conda/lib/python3.11/site-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

In [4]:
pwd

'/home/eidf128/eidf128/shared/export/juliana/export/juliana'

In [5]:
home_dir = '/home/eidf128/eidf128/shared/export/juliana/export/juliana'

### Functions

##### Clean

In [6]:
def remove_stop_words(text):
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words("english"))
    filtered = [w for w in tokens if w.lower() not in stop_words and w.isalpha()]

    return filtered

In [7]:
def remove_special_characters(text):
    """
    This function removes special characters from the text.
    :param text: text
    :return: text without special characters
    """
    cleaned_string = re.sub(r'[?|$|.|!|@|#|%|^|&|*|(|)|-|_|+|=|;|:|,|<|>|/|{|}|[|]|~|`|\'|\"|\\]',r'', text)

    return cleaned_string

In [8]:
def clean_text(text):
    if pd.isna(text) or str(text).strip() == "":
        return ""
    text = remove_special_characters(str(text)) or ""
    
    return remove_stop_words(text)

##### Counts

In [9]:
# It counts the number of words in a phrase
def count_words(phrase):
    """
    This function counts the number of words in a phrase.
    :param phrase: text

    :return: the number of words in the phrase
    """
    lenght = 0
    if len(phrase) > 1 and phrase.isspace() == True:
        lenght = 1
    
    else:
        words = phrase.split()
        lenght = len(words)
    
    return lenght

In [10]:
# It counts the number of characters in a phrase
def count_characters(phrase):
    """
    This function counts the number of characters in a phrase.
    :param phrase: text

    :return: the number of characters in the phrase
    """
    lenght = 0
    if len(phrase) < 1:
        lenght = 0
    else:
        lenght = len(phrase)
        
    return lenght

#### NLP

In [11]:
# It lemmizes a text
def lemmatizer(phrase):
    """
    This function lemmatizes a text.
    :param phrase: text

    :return: the lemmatized text
    """
    doc = nlp(phrase)
    lemmatized_tokens = [token.lemma_ for token in doc]
    lemmatized_text = ' '.join(lemmatized_tokens)
    
    return lemmatized_text

In [12]:
# It extracts the entities from a text
def entities_recognition(phrase):
    """
    This function extracts the entities from a text.
    :param phrase: text
    :return: the entities extracted from the text
    """
    entities = []
    doc_phrase = nlp(phrase)
    entities = list(doc_phrase.ents)
    
    return entities

##### Organization

In [13]:
def first_non_null(s):
    s = s.dropna()
    return s.iloc[0] if len(s) else pd.NA

In [14]:
def join_unique_non_null(s, sep=" | "):
    s = s.dropna().astype(str)
    s = s[s.str.strip().ne("")]           # drop empty strings
    s = pd.unique(s)                      # keep unique (preserve order)
    return sep.join(s) if len(s) else pd.NA

### Reading the data and creating df

In [15]:
data_dir = '/home/eidf128/eidf128/shared/export/juliana/export/juliana/items'

In [16]:
os.chdir(data_dir)

In [17]:
json_files = [f for f in os.listdir(data_dir) if f.endswith('.json')]
json_files

['49dbc9e1-eeab-411b-8510-080ceb5dccfa_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'ecfd3009-d585-4b1a-9137-6b7460379b94_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '619bb04f-94c4-4eb8-9511-b2dfeaa3412a_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'e232d2db-1621-47df-bb6d-ea69187de44f_in_3b8e9ad5-7d72-430c-aed5-a73376ba2bf8.json',
 '9bf808da-4a87-4bfc-a885-4f53bf7531fc_in_300bc74f-b2ca-4cdb-94f8-757e57d8f753.json',
 '50e06d54-ef79-4eda-ba70-53af5f601281_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '4e3448ea-fc40-4b5c-94f4-a429349bbc27_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 'c453e153-7b18-4b3d-ae05-69ef3210e4c7_in_9053e53c-3f3e-443a-940a-bf374489f89c.json',
 '2f73dbf5-7b4a-4f18-a29c-20a046031c39_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '35241ba3-5bd0-4266-966f-fbbdedf2d53b_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '687d6803-5d6e-447d-b9ed-d9f71d4a3d26_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'f084fe67-dfb5-4569-b9a1-759ef2ddbdc3_in_51c495e9-9c4f-49ed-b1fe-40e95f9ad2fe.json',
 '719adf40-e30a-463f-a940-8a727671b7b1_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '5b3d327a-a3cd-49f9-afc1-38b26b3caa21_in_1ac0f2fb-ec25-4eba-8958-be1e9679a0f9.json',
 '63503800-2fe4-40cc-96a3-0f024c6abdc6_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'cd2050a6-2b6c-4f95-909e-e5abf6f9dcde_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 'd27ec461-8149-4b76-bad5-a7fe5c1ee06d_in_51c495e9-9c4f-49ed-b1fe-40e95f9ad2fe.json',
 '622f00dc-3145-4fd3-aeda-4dbe688bbd9d_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'cf8c904b-ce8d-4688-b0cb-5bdbfbd337b8_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 '84a4205b-fe62-4139-9848-a383c6a2a840_in_4c2abe73-43a7-49c2-aa54-d2f7302c6b0a.json',
 '104ced2e-6219-4084-82e6-7b9cd8d4e0c7_in_61e0ea5f-b9a8-4e00-b6e1-b5ba89420827.json',
 'd49286db-ce9a-4afc-8a62-55fadd784a43_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '6f15f930-6ed9-4a87-bb8d-cefe0532d1ab_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '297495e8-0f6d-4538-848d-a72a89918fb7_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 '1ed19f4b-f89c-4d94-817b-24ed1a15c879_in_161f31d6-630a-467f-a5e6-0cf696714f42.json',
 '0f1ac760-437e-4006-814d-32ec7d31fc79_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 '1c64e67a-2fc0-4c35-a7e9-ed7e9c4b7721_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 '51cee9a7-1059-4276-a6cf-8e07614d05f2_in_7ec05b33-4b3d-4b99-a47d-6587bf34ac74.json',
 'bc54eb9e-7fe2-4b8c-8c40-0cf15f1bd0ff_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '66dadb6e-9246-4d8f-9a6e-d00ba1656cf1_in_51c495e9-9c4f-49ed-b1fe-40e95f9ad2fe.json',
 'd23947bf-ca25-4f34-8b20-840c299ae023_in_40498c59-c0f4-4da9-8faf-2e72e69e83bc.json',
 '3eaadcc9-1b46-4d77-ae1e-be5fb2a3331a_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '6c4a0ed7-4098-40a2-a4bb-d180cb6d1c60_in_68a277d4-d365-468b-8de3-0bf920887051.json',
 'baaedb44-2bc0-43e7-9b5a-6de4ca2c23fe_in_161f31d6-630a-467f-a5e6-0cf696714f42.json',
 '8f9b573f-e339-492d-9c3b-92b96f635cbb_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd905d729-ea3b-4e34-8e9e-19d7de9f09f6_in_3b8e9ad5-7d72-430c-aed5-a73376ba2bf8.json',
 '0b623382-788e-4826-8070-8c5124895f84_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '122bf0d3-568c-48fc-9855-b8f3ea464bf2_in_9053e53c-3f3e-443a-940a-bf374489f89c.json',
 '13a6cc8b-c468-4483-a554-a5e854f100cd_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'ac79b4cd-ed72-4b88-8d5d-37beacef6da9_in_22521a17-78ba-452b-be71-59965f4962cd.json',
 '632defd4-0b7a-40db-9db6-d30466eac4f7_in_a1e10c1a-91d5-4259-85a7-78317298294a.json',
 '9fc1a995-ae84-458d-b8b4-f1565d5e8883_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '42c75f54-e3e6-4153-80f0-2c9fa532b8e8_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '1c8c8c55-9e4d-44e6-8b20-a639c6994eb6_in_b10c0a23-6e99-4b0b-a9bf-90b2f61b27d8.json',
 '6ccf0348-484a-4174-9aae-71e783a56696_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 '0f12685d-6435-4f68-8b08-8828daaa49e2_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '20c83359-bbe1-4c0a-9eb7-23fbd267083c_in_6aa864a3-2383-4e9c-9a83-58dc5c4a66c4.json',
 '712c7544-1faf-48ab-8178-638d030d6566_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'f7dc78ed-b420-45ce-ad14-51b2ccf871af_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '634b198a-0936-4493-8aa5-8eadb58c54bc_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'ec7d0d2b-b58a-4ce5-aa8b-6995538b3364_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '8ec61e48-0475-4a5b-b6bf-21e8a71bfa7d_in_a81372fc-a366-4640-b4ee-58e28769c33c.json',
 '6efa3174-1afb-4538-bbca-6c4bf4a58d74_in_2d3e9732-a14c-4009-b2b3-2de986d551d8.json',
 'e50bc7ee-d661-4955-af8a-df09e0b7b323_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '473b7f5e-05dd-4ae2-a2f0-c4db93b82bff_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '33aaac7e-9f1d-4151-b698-2b230c918270_in_bcbf6f27-2d85-402c-a1cc-a03a74a5052c.json',
 '6ca381a4-28e3-47b1-a1ff-8bf4babda114_in_3944db8e-cf10-4043-b903-91735aea8e4f.json',
 '4c4a389e-6fbf-45f6-919f-7a4d9ce8464b_in_8c54afdb-dd9e-4232-94af-40d163e88716.json',
 '51756e2c-3184-4562-8f8d-9b49e58c7c00_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 'efc3e830-13c6-4efe-bd5a-21d07c34c4b0_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 'b95d8b74-8025-4e2f-a027-738904b8c023_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '79edda41-1606-474b-be7d-5be7ccff8f9f_in_90917883-0ec6-4070-8746-cee321fea156.json',
 '67f4ec35-6fbb-4d90-9f53-5094ae61f6a9_in_1673fd96-9813-4db8-983d-6408ad910d2b.json',
 'b21ccba6-5544-435e-bc0c-1fdab12353aa_in_876d47d2-1473-4485-b606-0de72d081fa1.json',
 '874245be-36cc-4267-be23-831f8d4729eb_in_51c495e9-9c4f-49ed-b1fe-40e95f9ad2fe.json',
 'a35e9261-fce2-4582-9d57-ea915c971a96_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 '7d046975-1aa7-4db7-a117-cbf4ca39da92_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'f40b6725-cc78-46d7-ae55-3bdaa3cfed4e_in_3afdb97c-1221-4518-9d77-9ebc322ceca5.json',
 'd04e4113-56d8-468c-a4b7-ec874770d20e_in_4cc910f0-f2b1-4034-a4d6-9815f5d11aaa.json',
 'eb020208-0593-4ed9-8b2e-f12c8278ed89_in_9ac6844f-3c04-4852-aa07-6c97028d9ec1.json',
 '3fcdb64b-f2fe-4641-9dc2-9d59a462e048_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '7b5e3e4d-a277-47c4-929d-795da38b0138_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'c75a3738-6a0e-4422-8c4a-a650d6b373f7_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '2ad7f841-75b6-458d-9448-af7fb2314fda_in_e15f7311-c8dc-4e71-bf2a-f1bfc21f2299.json',
 '36bcbf56-0fde-486f-b355-fa3ac50933de_in_4030962c-60b3-4432-80d8-bdc0be370558.json',
 'c1884a16-bae5-4d6c-9766-87e6b4edb97f_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '39f83aaa-63ec-40eb-b55f-c0844436b6a7_in_80d43058-b550-4139-96e7-3c6837635f33.json',
 'e93ee62f-cf48-40dc-b73e-89dd125e524d_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'c09d23c5-de7b-4099-b90a-fc458f8c6def_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '13ef0aa3-77a1-4e6f-b60e-707b4f524068_in_53fa6767-def3-4378-94fc-bb809ad55c55.json',
 '330f10c5-a36d-4297-a95a-ce37c4ec32ce_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '8acf44bc-4fb0-4a05-8d96-8eeec2902e96_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '2f2dd358-9646-44c8-a566-30e4365bd732_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'bbff0c05-772d-4669-ac9a-256bf9a8d910_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '236c692d-264c-4fb6-99ac-2edba347c3ae_in_93779c8f-b2b0-45a1-ba38-ac7024f2b847.json',
 '09c18873-29fe-4798-831b-57d652fa7ec9_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '2a0a0d81-2726-4130-8bae-6cafb18b2c83_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '9e651ce8-5925-41b0-88cd-09d3de096ae8_in_b10c0a23-6e99-4b0b-a9bf-90b2f61b27d8.json',
 'bc1d5267-f745-42a5-9a45-7d2126420b82_in_51c495e9-9c4f-49ed-b1fe-40e95f9ad2fe.json',
 '2ca46575-74db-40eb-bf35-847ffc29d774_in_1b007cf1-85be-47ce-b356-f0f5552ec7f8.json',
 '7fb31b98-a1a1-47df-8948-08f6a0fdaeef_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'e77eab70-fd1e-4aa3-b63b-e06720056112_in_52bb4fd3-4b86-4811-990e-c50729e78c7d.json',
 '313d0f5c-38a6-4512-b540-bf279d701cbb_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '4fe84f61-775e-4bc1-bb3c-3e8fe4949fba_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'cadb5286-4201-4922-aeeb-0be81fa68bf1_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '34046892-c405-4435-8810-1150f0eb85d7_in_5f4fb7b2-b949-42a8-8212-cff21e62c582.json',
 'e9c6bce4-7f8c-4fef-b472-795c377ce5cf_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'dea9e7e2-1400-4798-b56f-aeacbbbee158_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '7f486648-d424-4be4-a576-112c09d02505_in_1673fd96-9813-4db8-983d-6408ad910d2b.json',
 '754d088c-514d-4b39-98ea-2064b2f8e5ce_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 '9717c8f6-7ac9-4575-918c-2917af496b5d_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '45e0d03b-e207-40d8-8a73-b8ee43ec0f5f_in_92a35e73-9417-4e9b-855c-a6385635d361.json',
 '962140bf-0030-4f9a-8089-dbfbc1bb81d0_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 'ea9d67da-2ac2-4486-b77a-f17aa347c8fd_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '93491bc7-6670-4f1b-8956-da779ef7dc17_in_b185c0e2-5d29-4737-84b7-bf75210f1a95.json',
 '3125f76d-5bb7-48a5-8a7e-70c7a614ffbe_in_1673fd96-9813-4db8-983d-6408ad910d2b.json',
 'a36d8a8c-38a2-425c-90e2-8101648d3ee1_in_8a826a38-6349-4db8-a374-766e7f220374.json',
 '7f790d74-43ef-456f-9528-677e7da80aef_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 'd9353382-628c-4085-bebd-11bdcfde39de_in_1b007cf1-85be-47ce-b356-f0f5552ec7f8.json',
 '8dd7eaa3-d2d8-4aa7-9683-27e102f9c6f4_in_89452524-cce0-49de-96d7-46e9035f7a6d.json',
 '5a1bb77c-f70c-4957-a021-ad533b2dcc01_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '8d47f3e2-014b-4419-8af2-ca3441bbc599_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'ebee8ba6-fd1b-40a2-90e2-60f92a47ae7e_in_fbbcbdab-9aba-4533-afdf-1152205ab162.json',
 '4c82bd55-deec-4596-8ea0-ca3f44a1956b_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '03f2fcc4-f557-45c6-97c0-a052bfb20ea0_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'a2cf75de-07d1-4f4b-8446-d65441647fa1_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'b9a517a0-4b8a-4949-af44-ff108ee9a01e_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '0221717e-737f-492a-9c9c-4f4b37ca2642_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '8e54c9f2-f830-4cd8-9a80-7b03f9399ddc_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '9f4e23e0-57fb-4af9-afea-93977f4b8027_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '37ca235c-6c5d-4e77-bc3f-2bdfc3f7c724_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'a5ccb0ed-a241-4fb4-9c3f-613573338d94_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 'd37accf0-d963-46ee-b664-a6b62b391c2b_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 '59223435-77b5-46fa-8f66-075c7c3774e6_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd255d161-fcbb-44d1-9166-50e2e8844dba_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '6cdf5121-386d-4e44-aec6-c8e4d9b082c3_in_707c6ee6-3ebf-4730-91f3-fa40026e3fb0.json',
 '59fd5917-1693-4a0e-a2ac-3695768565f8_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '4c8c6625-db10-4606-a18a-fe7c027fcfd5_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 'ca2c9e29-f596-4bee-a12e-b0cd56d10274_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '5dc26916-ca4d-4285-b760-c0231ec923a6_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '3b0a3031-3d98-4937-bf17-bf31e8a9b88a_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 'cd6f72a6-a23c-444a-b43c-ab84aadefba3_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd6293ff3-6dc4-4161-b14f-621b6326973e_in_1b007cf1-85be-47ce-b356-f0f5552ec7f8.json',
 '994e280c-07d9-4615-bfd3-2a59ab7b53ca_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '4b838bd3-0702-4d3a-9300-323b38e344d7_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'cbc5dcfe-27e8-4ab1-b198-5fc4235ea2a8_in_8a826a38-6349-4db8-a374-766e7f220374.json',
 '1a1ec322-309e-4776-9242-0d21faed5b50_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '1e7e6355-1e66-4544-b0f3-2a859b030460_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 'ff2f17e1-fd35-4ad5-a20f-245620b76b76_in_5fdd0918-23fa-4bed-b766-e11e767233c9.json',
 'e1ce5590-0688-492c-8f5c-298fbb52b6a0_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'a63a6a25-f7fb-4867-b3e8-bb66611d23ff_in_848a34b9-f59c-4e98-8c2c-e3f038795232.json',
 '9cd48244-2046-49b3-b366-32b96f266a95_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '1a5ce174-9d22-4e56-98f1-7a12a02812ba_in_8c1ab939-0978-4637-a4fa-d6678a6a82ec.json',
 '17a99a7d-68e7-421c-b341-e1551da50eeb_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 '4769c77a-a21c-4e18-9bcc-9f31ad891ac0_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd607d27b-c339-4538-821b-47f425f12e56_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'abb05f2b-9064-4c6d-9f70-76a85d7413d9_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd564a8f5-20d5-4952-8bd5-ad56bd564870_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 'eb9812c3-ae2d-4664-a4bf-061af9a5edd8_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '17180e0c-41df-4766-9e70-5858b4b53a61_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 '61390512-9681-4435-8c15-7c3ed4c9708a_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 'c43df299-7e17-43dd-b34c-5b856c609392_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '1c6bfe23-f500-4b42-b850-d0ec7f603a5b_in_3c17bbd4-b344-46fe-ab40-9898f03d0906.json',
 '5838a7e9-b8f3-429a-bcc2-2bfcf2a9909f_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '23d09f69-f599-4312-a0f4-c43a3052907c_in_cdac1f28-f74c-486d-9f51-0239c61a6ca7.json',
 '653a7457-dff1-4af6-a2aa-730d6eafb02a_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 '6eff6e68-df97-40ae-b96f-44d4a880321e_in_89715629-7613-4621-9ff8-0cd4508c7e94.json',
 'ff84d6b4-ade2-491f-a375-b036503f2ecf_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '052d4f94-a1f9-44e0-8717-2f835316e238_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 '6e53f6ff-57e5-47fd-bb6d-117a15fb0ad6_in_5f66c403-12af-41a4-b3e3-a560277df001.json',
 '261fad8b-9dbe-47fe-b1e1-659b9b7a83c1_in_22521a17-78ba-452b-be71-59965f4962cd.json',
 '2650051f-ad66-428b-a082-dc7c947d00ea_in_b5054881-3845-488d-92fd-c60f468003a1.json',
 '82e9290f-3cd5-4ee9-baed-c5dfd7d906c7_in_fbd15ad3-fe51-4587-926d-319083b0d337.json',
 '1cfc7ee8-5b95-4c28-98de-94fb876cc6d0_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '13340971-1aab-400c-898f-0dbbae17fb67_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd58bf0a3-a5da-4f86-bb7d-805bf6a814b4_in_1673fd96-9813-4db8-983d-6408ad910d2b.json',
 'd57a2aff-e21b-4ac0-9bc6-82ae98849ea5_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 '75ce1dbb-efcb-4631-84e9-89417102575e_in_3944db8e-cf10-4043-b903-91735aea8e4f.json',
 '8738e04b-aacd-4208-9255-3094606e522b_in_4c2abe73-43a7-49c2-aa54-d2f7302c6b0a.json',
 'eaf0e713-885d-4eac-a618-268198c0f282_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '8dd90ef3-341b-4706-86c4-43fbc0472731_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd8080285-0477-40b8-8012-44655f6fa50a_in_9ac6844f-3c04-4852-aa07-6c97028d9ec1.json',
 '56e7d971-0be1-41bc-8f29-5f24b88cb7b9_in_0663178d-f8c5-46c6-9d97-1e1f78c3fe0d.json',
 'b076dc23-b3b6-4705-a91f-435b84334719_in_7a72c356-d007-4911-bfdf-1b0c08e2b5cd.json',
 'f99cfb5b-7c77-45c3-ae71-a780577fbb59_in_1673fd96-9813-4db8-983d-6408ad910d2b.json',
 '1611180b-2677-44dc-a14b-aa8f395b144c_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '5ae8e2d5-33b8-4617-8990-2a213057315c_in_3824436b-8092-4cde-880d-6a68a5e86cc6.json',
 'c2d40e11-5ee2-4e16-aaa4-3708e9513241_in_de4dbea0-9427-4104-b422-86d33427ce75.json',
 '86cfc62e-b67a-417b-a3e5-972a0145c1c1_in_80d43058-b550-4139-96e7-3c6837635f33.json',
 '1eb2de47-7c24-43f2-b685-5fdcccbd4e32_in_c3cf47c6-7da4-4fd8-a904-ca7cc54ac206.json',
 '5cc29014-7019-4f76-a123-2a2cd9ceb1c1_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '44e390a1-c057-4ace-ba8c-93383745c532_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 '4b0ec746-04cb-4aa2-99c8-b0429c187739_in_8a826a38-6349-4db8-a374-766e7f220374.json',
 '98165269-334a-4a21-a6f8-bdd66a7283a7_in_a8a4b5f2-8944-4a1e-8cce-a42dba4d1783.json',
 'dda5ba88-b7fa-4b9b-b6a6-18270013e16c_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd308deb0-73e0-46b0-b7e0-73b0f88a9d0a_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'cc13cea1-16b9-4dfc-82bc-bdb1caf8591f_in_b7d99824-d0d0-47ec-bb3e-457a06b676bd.json',
 'e78547d3-400f-4ea9-aae3-5fe39cb327b5_in_9e4a3b50-dfc3-47ff-9b67-6ba4ee328e35.json',
 'd0be0285-83c8-4f84-8dec-ecd03c31918f_in_3944db8e-cf10-4043-b903-91735aea8e4f.json',
 '4be65b38-64b6-431c-a1b8-321a2248b8cd_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '92d5c382-12f0-40fe-b32e-be7bd3f73e3f_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'f3afb003-bb38-45f8-a2de-9a5ee2c7b3a0_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'e1edfddf-0a1b-4d3f-b302-3c2e00051c24_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '7723e9d9-4158-4836-ad75-ec97890b9436_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '40977940-c564-4613-a899-5243aecdef65_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'e9effdce-1f8d-4859-9a9c-6357f341fbec_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '26423500-f917-4e01-9f2b-c290f0a48d67_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 'ca591dff-81de-4abe-a0a3-5ada5da73570_in_4ffd0c03-5daa-4557-978d-90821c5aeedd.json',
 'ee78953f-297f-4d14-ba79-1848cac70082_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 '24396cc7-07a5-4655-9fd2-3a4fd74f1c0d_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'ddc84420-5d69-44d9-904f-079885adc3ba_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd85fb575-d365-4846-b346-6bae19ff824e_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',
 'fbb099c2-c083-408a-beeb-57e63f0be132_in_3cd4031f-f029-4214-8d8a-97feb7a819fb.json',
 'ebd57bb0-744a-477e-987f-363f7f392c92_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 'df83635e-1998-481f-9782-9a13b913b3f3_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'f53d9046-5983-493e-a948-1520a2e6afc6_in_1673fd96-9813-4db8-983d-6408ad910d2b.json',
 'a9583327-f495-42f8-9ca3-a84a4f8f1d14_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '78ab651a-4b4b-409b-95e2-a45ad9c2d1e5_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '6a85e4b2-c1be-4786-8ed8-9392ac1c9f73_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'b8c80825-5a1c-42c3-8509-770e0503bb4e_in_b877f940-e8fb-4b86-a7e2-29dc9335d4fd.json',
 'b12dc8f2-c19b-4382-a27b-1280ff73e8e9_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '1f049984-c289-4024-9d8a-3d26b61e7ac7_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'b18f134e-55e8-4c2d-85f0-1f46fd9b4d0a_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '99333170-3360-4f69-bec5-65c27cb83b4c_in_9fc9b312-0d03-4f13-9152-8b8d325f41b8.json',
 '0c9e1fc0-c744-4ea6-855b-c114e0ea96a8_in_e5b89b52-8a37-4686-8738-32a61970614f.json',
 '1c2abd43-d106-49bf-b31a-aa6ee7e9af7b_in_51c495e9-9c4f-49ed-b1fe-40e95f9ad2fe.json',
 'a001dac4-15bf-4cae-8a74-237f4af339dd_in_9ac6844f-3c04-4852-aa07-6c97028d9ec1.json',
 '48fd6c9f-2153-47e8-b468-dee5108d1ad4_in_b10c0a23-6e99-4b0b-a9bf-90b2f61b27d8.json',
 '15a3d3c6-5e73-4354-addf-d508895f3fe5_in_a7de0b44-00f4-4bd7-80cc-64744dce38ef.json',
 '1ae1f34d-c406-48bc-91b0-24ce6b1e63c8_in_f4cb2049-f466-4df4-82ad-d4628a837f6f.json',
 'd0949cd3-a6e4-41c3-98a7-e0919f1ae35e_in_566a231c-5f23-4507-8b9b-855071856b52.json',
 '9bd36f63-3987-4705-98f3-58033a208675_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'd592b00e-779e-4724-9d38-9306bb607d86_in_9ac6844f-3c04-4852-aa07-6c97028d9ec1.json',
 '9aa8ea17-1326-40ad-a660-f7c5c276c2fc_in_89715629-7613-4621-9ff8-0cd4508c7e94.json',
 '33b58ea5-7030-42ad-811e-1383bf0a6816_in_3ce8a4a5-e136-4ba6-8ff9-0c72fc895105.json',
 '5b1067bc-ac47-4f7e-be74-6475ba33fb4e_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '217cab29-826f-48db-8ba2-5559437ea6e9_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '7c184967-6dac-4fc5-b612-00a408c61b64_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 'c80ca0e0-d83d-433f-a855-fbd5cdf13209_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '9f41b423-a9ed-4c57-a8a0-a0fab6acbda9_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '3fa10183-c2a9-4613-bd81-0095a3f238a2_in_78be837d-99a1-4da9-813d-fa139b2853f2.json',
 '0da87147-58fe-4fce-af67-71709bcc3719_in_456eccd4-54f2-48f2-afb0-c4a02936452c.json',

In [18]:
dfs_datashare = []

In [19]:
for json_file in json_files:
    json_1 = open(json_file)
    json_dicc = json.load(json_1)

    file_name = os.path.basename(json_file)
    
    result = defaultdict(list)

    for item in json_dicc:
        key = item['key']
        value = item['value']
        result[key].append(value)

    result_dict = dict(result)

    df = pd.json_normalize(result_dict)
    name = file_name.split('_')[0]
    collection = file_name.split('_')[2]
    df['file_name'] = file_name
    df['collection'] = collection.split('.')[0]
    df['id_in_file'] = name

    dfs_datashare.append(df)

df_datashare_collapse = pd.concat(dfs_datashare)

In [20]:
df_datashare_collapse.columns

Index(['dc.contributor', 'dc.contributor.other', 'dc.coverage.spatial',
       'dc.coverage.temporal', 'dc.creator', 'dc.date.accessioned',
       'dc.date.available', 'dc.identifier.citation', 'dc.identifier.uri',
       'dc.description.abstract', 'dc.language.iso', 'dc.publisher',
       'dc.relation.isreferencedby', 'dc.rights', 'dc.subject',
       'dc.subject.classification', 'dc.title', 'dc.type', 'file_name',
       'collection', 'id_in_file', 'dc.relation.isversionof',
       'dc.description.tableofcontents', 'dc.source', 'dc.title.alternative',
       'dc.relation.isreplacedby', 'dc.date.updated', 'dc.date.embargo',
       'dc.relation.replaces', 'dc.source.uri', 'dc.date.issued',
       'dcterms.subject', 'dcterms.isReferencedBy', 'dc.contributor.advisor',
       'dc.relation.hasversion', 'dc.contributor.author', 'dc.description',
       'dc.description.sponsorship', 'dc.relation.ispartofseries',
       'ds.withdrawn.showtombstone', 'dc.relation.isbasedon', 'dcterms.rights',
       'dc.relation.ispartof', 'dcterms.isReplacedBy', 'dcterms.publisher'],
      dtype='str')

### Cleaning

In [21]:
# Replace None with nothing
df_datashare_collapse.replace(to_replace=[None], value="", inplace=True)

,dc.contributor,dc.contributor.other,dc.coverage.spatial,dc.coverage.temporal,dc.creator,dc.date.accessioned,dc.date.available,dc.identifier.citation,dc.identifier.uri,dc.description.abstract,...,dc.contributor.author,dc.description,dc.description.sponsorship,dc.relation.ispartofseries,ds.withdrawn.showtombstone,dc.relation.isbasedon,dcterms.rights,dc.relation.ispartof,dcterms.isReplacedBy,dcterms.publisher
0,"[Glendinning, Miles, Breen, Kat]",[Heritage Lottery Fund],"[Wolverhampton City, United Kingdom]",[start=1987; end=1987; scheme=W3C-DTF],"[Glendinning, Miles]",[2023-05-17T16:00:22Z],[2023-05-17T16:00:22Z],"[Glendinning, Miles. (2023). Tower Blocks UK: ...","[https://hdl.handle.net/10283/8181, https://do...",[Multi-storey block details: two 8-storey bloc...,...,,,,,,,,,,
0,"[Glendinning, Miles, Breen, Kat]",[Heritage Lottery Fund],"[Enfield London, United Kingdom]",[start=1988; end=1988; scheme=W3C-DTF],"[Glendinning, Miles]",[2023-05-17T13:55:10Z],[2023-05-17T13:55:10Z],"[Glendinning, Miles. (2023). Tower Blocks UK: ...","[https://hdl.handle.net/10283/5559, https://do...",[Multi-storey block details: four 12-storey bl...,...,,,,,,,,,,
0,"[Glendinning, Miles, Breen, Kat]",[Heritage Lottery Fund],"[AB11 8TW; AB11 8TX; AB11 8TY, Aberdeen, UK, U...",[start=1983; end=1983; scheme=W3C-DTF],"[Glendinning, Miles]",[2019-11-14T09:55:05Z],[2019-11-14T09:55:05Z],"[Glendinning, Miles. (2019). SC_1141943.png, B...","[https://hdl.handle.net/10283/3445, https://do...",[Multi-storey block details: three 14-storey b...,...,,,,,,,,,,
0,"[Kim, Jinho]",[University of Edinburgh],,,"[Kim, Jinho]",[2017-06-14T11:00:41Z],[2017-06-14T11:00:41Z],"[Kim, Jinho. (2017). Source codes of the netwo...","[https://hdl.handle.net/10283/2737, https://do...",[This data set contains the source codes for t...,...,,,,,,,,,,
0,"[Anjos, Miguel]",[University of Edinburgh],,,"[Burkard, RE, Çela, E, Karisch, SE, Rendl, F, ...",[2022-03-31T16:59:08Z],[2022-03-31T16:59:08Z],"[Burkard, RE; Çela, E; Karisch, SE; Rendl, F; ...","[https://hdl.handle.net/10283/4390, https://do...",[The Quadratic Assignment Problem (QAP) has re...,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"[Nadal, Cathe Desiree]",[Self-funded],"[Cavite, Cavite, Philippines, PH, PHILIPPINES]",,"[Nadal, Cathe Desire, Del Rosario, Tovie Clart...",[2022-10-11T14:40:23Z],[2022-10-11T14:40:23Z],"[Nadal, Cathe Desire; Del Rosario, Tovie Clart...","[https://hdl.handle.net/10283/4758, https://do...","[""CAPTURING THE DYNAMIC CHARACTER OF THE PHILI...",...,,,,,,,,,,
0,"[Glendinning, Miles, Breen, Kat]",[Heritage Lottery Fund],"[Sefton, United Kingdom]",[start=1987; end=1987; scheme=W3C-DTF],"[Glendinning, Miles]",[2023-05-17T15:43:57Z],[2023-05-17T15:43:57Z],"[Glendinning, Miles. (2023). Tower Blocks UK: ...","[https://hdl.handle.net/10283/7742, https://do...",[Multi-storey block details: one 16-storey blo...,...,,,,,,,,,,
0,"[Glendinning, Miles, Breen, Kat]",[Heritage Lottery Fund],"[Camden London, United Kingdom]",[start=1988; end=1988; scheme=W3C-DTF],"[Glendinning, Miles]",[2023-05-17T13:34:44Z],[2023-05-17T13:34:44Z],"[Glendinning, Miles. (2023). Tower Blocks UK: ...","[https://hdl.handle.net/10283/5355, https://do...",[Multi-storey block details: CS 1: eleven 6-st...,...,,,,,,,,,,
0,"[Glendinning, Miles, Breen, Kat]",[Heritage Lottery Fund],"[Salford City, United Kingdom]",[start=1987; end=1987; scheme=W3C-DTF],"[Glendinning, Miles]",[2023-05-17T15:41:06Z],[2023-05-17T15:41:06Z],"[Glendinning, Miles. (2023). Tower Blocks UK: ...","[https://hdl.handle.net/10283/7619, https://do...",[Multi-storey block details: one 20-storey blo...,...,,,,,,,,,,
0,"[Glendinning, Miles, Breen, Kat]",[Heritage Lottery Fund],"[Haringey London, United Kingdom]",[start=1988; end=1988; scheme=W3C-DTF],"[Glendinning, Miles]",[2023-05-17T14:24:17Z],[2023-05-17T14:24:17Z],"[Glendinning, Miles. (2023). Tower Blocks UK: ...","[https://hdl.handle.net/10283/6047, https://do...",[Multi-storey block details: one 6-storey bloc...,...,,,,,,,,,,

In [22]:
# Everything to lowercase
obj_cols = df_datashare_collapse.select_dtypes(include = ["object", "string"]).columns #Select columns that have strings on it
df_datashare_collapse[obj_cols] = df_datashare_collapse[obj_cols].astype("string").apply(lambda s: s.str.lower())

### Stats

In [23]:
df_datashare_collapse.columns

Index(['dc.contributor', 'dc.contributor.other', 'dc.coverage.spatial',
       'dc.coverage.temporal', 'dc.creator', 'dc.date.accessioned',
       'dc.date.available', 'dc.identifier.citation', 'dc.identifier.uri',
       'dc.description.abstract', 'dc.language.iso', 'dc.publisher',
       'dc.relation.isreferencedby', 'dc.rights', 'dc.subject',
       'dc.subject.classification', 'dc.title', 'dc.type', 'file_name',
       'collection', 'id_in_file', 'dc.relation.isversionof',
       'dc.description.tableofcontents', 'dc.source', 'dc.title.alternative',
       'dc.relation.isreplacedby', 'dc.date.updated', 'dc.date.embargo',
       'dc.relation.replaces', 'dc.source.uri', 'dc.date.issued',
       'dcterms.subject', 'dcterms.isReferencedBy', 'dc.contributor.advisor',
       'dc.relation.hasversion', 'dc.contributor.author', 'dc.description',
       'dc.description.sponsorship', 'dc.relation.ispartofseries',
       'ds.withdrawn.showtombstone', 'dc.relation.isbasedon', 'dcterms.rights',
       'dc.relation.ispartof', 'dcterms.isReplacedBy', 'dcterms.publisher'],
      dtype='str')

In [24]:
df_datashare_collapse["dc.description.abstract_clean"] = pd.Series(index = df_datashare_collapse.index, dtype="object")

In [25]:
print(df_datashare_collapse.shape)

(7754, 46)

In [26]:
df_datashare_collapse = df_datashare_collapse.reset_index(drop=True)

In [27]:
print(df_datashare_collapse.index)
print(df_datashare_collapse.index.is_unique)
print(df_datashare_collapse.index.value_counts().head())

RangeIndex(start=0, stop=7754, step=1)
True
0    1
1    1
2    1
3    1
4    1
Name: count, dtype: int64

In [28]:
type(df_datashare_collapse)

pandas.DataFrame

In [29]:
df_datashare_collapse

,dc.contributor,dc.contributor.other,dc.coverage.spatial,dc.coverage.temporal,dc.creator,dc.date.accessioned,dc.date.available,dc.identifier.citation,dc.identifier.uri,dc.description.abstract,...,dc.description,dc.description.sponsorship,dc.relation.ispartofseries,ds.withdrawn.showtombstone,dc.relation.isbasedon,dcterms.rights,dc.relation.ispartof,dcterms.isReplacedBy,dcterms.publisher,dc.description.abstract_clean
0,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['wolverhampton city', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t16:00:22z'],['2023-05-17t16:00:22z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/8181', 'https:/...","[""multi-storey block details: two 8-storey blo...",...,,,,,,,,,,NaN
1,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['enfield london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t13:55:10z'],['2023-05-17t13:55:10z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/5559', 'https:/...","[""multi-storey block details: four 12-storey b...",...,,,,,,,,,,NaN
2,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['ab11 8tw; ab11 8tx; ab11 8ty', 'aberdeen', '...",['start=1983; end=1983; scheme=w3c-dtf'],"['glendinning, miles']",['2019-11-14t09:55:05z'],['2019-11-14t09:55:05z'],"['glendinning, miles. (2019). sc_1141943.png, ...","['https://hdl.handle.net/10283/3445', 'https:/...","[""multi-storey block details: three 14-storey ...",...,,,,,,,,,,NaN
3,"['kim, jinho']",['university of edinburgh'],,,"['kim, jinho']",['2017-06-14t11:00:41z'],['2017-06-14t11:00:41z'],"['kim, jinho. (2017). source codes of the netw...","['https://hdl.handle.net/10283/2737', 'https:/...",['this data set contains the source codes for ...,...,,,,,,,,,,NaN
4,"['anjos, miguel']",['university of edinburgh'],,,"['burkard, re', 'çela, e', 'karisch, se', 'ren...",['2022-03-31t16:59:08z'],['2022-03-31t16:59:08z'],"['burkard, re; çela, e; karisch, se; rendl, f;...","['https://hdl.handle.net/10283/4390', 'https:/...",['the quadratic assignment problem (qap) has r...,...,,,,,,,,,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7749,"['nadal, cathe desiree']",['self-funded'],"['cavite', 'cavite, philippines', 'ph', 'phili...",,"['nadal, cathe desire', 'del rosario, tovie cl...",['2022-10-11t14:40:23z'],['2022-10-11t14:40:23z'],"['nadal, cathe desire; del rosario, tovie clar...","['https://hdl.handle.net/10283/4758', 'https:/...","['""capturing the dynamic character of the phil...",...,,,,,,,,,,NaN
7750,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['sefton', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t15:43:57z'],['2023-05-17t15:43:57z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/7742', 'https:/...","[""multi-storey block details: one 16-storey bl...",...,,,,,,,,,,NaN
7751,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['camden london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t13:34:44z'],['2023-05-17t13:34:44z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/5355', 'https:/...","[""multi-storey block details: cs 1: eleven 6-s...",...,,,,,,,,,,NaN
7752,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['salford city', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t15:41:06z'],['2023-05-17t15:41:06z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/7619', 'https:/...","[""multi-storey block details: one 20-storey bl...",...,,,,,,,,,,NaN
7753,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['haringey london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t14:24:17z'],['2023-05-17t14:24:17z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/6047', 'https:/...","[""multi-storey block details: one 6-storey blo...",...,,,,,,,,,,NaN

In [30]:
#nltk.download('punkt_tab')

In [31]:
df2 = df_datashare_collapse.reset_index(drop=True)
col = "dc.description.abstract"

for i, row in df2.iterrows():
    print(f"Processing row {i+1}/{len(df2)}")

    value_to_clean = row[col]
    if pd.notna(value_to_clean) and value_to_clean != "":
        df2.at[i, "dc.description.abstract_clean"] = clean_text(value_to_clean)

df_datashare_collapse = df2

Processing row 1/7754
Processing row 2/7754
Processing row 3/7754
Processing row 4/7754
Processing row 5/7754
Processing row 6/7754
Processing row 7/7754
Processing row 8/7754
Processing row 9/7754
Processing row 10/7754
Processing row 11/7754
Processing row 12/7754
Processing row 13/7754
Processing row 14/7754
Processing row 15/7754
Processing row 16/7754
Processing row 17/7754
Processing row 18/7754
Processing row 19/7754
Processing row 20/7754
Processing row 21/7754
Processing row 22/7754
Processing row 23/7754
Processing row 24/7754
Processing row 25/7754
Processing row 26/7754
Processing row 27/7754
Processing row 28/7754
Processing row 29/7754
Processing row 30/7754
Processing row 31/7754
Processing row 32/7754
Processing row 33/7754
Processing row 34/7754
Processing row 35/7754
Processing row 36/7754
Processing row 37/7754
Processing row 38/7754
Processing row 39/7754
Processing row 40/7754
Processing row 41/7754
Processing row 42/7754
Processing row 43/7754
Processing row 44/7754
Processing row 45/7754
Processing row 46/7754
Processing row 47/7754
Processing row 48/7754
Processing row 49/7754
Processing row 50/7754
Processing row 51/7754
Processing row 52/7754
Processing row 53/7754
Processing row 54/7754
Processing row 55/7754
Processing row 56/7754
Processing row 57/7754
Processing row 58/7754
Processing row 59/7754
Processing row 60/7754
Processing row 61/7754
Processing row 62/7754
Processing row 63/7754
Processing row 64/7754
Processing row 65/7754
Processing row 66/7754
Processing row 67/7754
Processing row 68/7754
Processing row 69/7754
Processing row 70/7754
Processing row 71/7754
Processing row 72/7754
Processing row 73/7754
Processing row 74/7754
Processing row 75/7754
Processing row 76/7754
Processing row 77/7754
Processing row 78/7754
Processing row 79/7754
Processing row 80/7754
Processing row 81/7754
Processing row 82/7754
Processing row 83/7754
Processing row 84/7754
Processing row 85/7754
Processing row 86/7754
Processing row 87/7754
Processing row 88/7754
Processing row 89/7754
Processing row 90/7754
Processing row 91/7754
Processing row 92/7754
Processing row 93/7754
Processing row 94/7754
Processing row 95/7754
Processing row 96/7754
Processing row 97/7754
Processing row 98/7754
Processing row 99/7754
Processing row 100/7754
Processing row 101/7754
Processing row 102/7754
Processing row 103/7754
Processing row 104/7754
Processing row 105/7754
Processing row 106/7754
Processing row 107/7754
Processing row 108/7754
Processing row 109/7754
Processing row 110/7754
Processing row 111/7754
Processing row 112/7754
Processing row 113/7754
Processing row 114/7754
Processing row 115/7754
Processing row 116/7754
Processing row 117/7754
Processing row 118/7754
Processing row 119/7754
Processing row 120/7754
Processing row 121/7754
Processing row 122/7754
Processing row 123/7754
Processing row 124/7754
Processing row 125/7754
Processing row 126/7754
Processing row 127/7754
Processing row 128/7754
Processing row 129/7754
Processing row 130/7754
Processing row 131/7754
Processing row 132/7754
Processing row 133/7754
Processing row 134/7754
Processing row 135/7754
Processing row 136/7754
Processing row 137/7754
Processing row 138/7754
Processing row 139/7754
Processing row 140/7754
Processing row 141/7754
Processing row 142/7754
Processing row 143/7754
Processing row 144/7754
Processing row 145/7754
Processing row 146/7754
Processing row 147/7754
Processing row 148/7754
Processing row 149/7754
Processing row 150/7754
Processing row 151/7754
Processing row 152/7754
Processing row 153/7754
Processing row 154/7754
Processing row 155/7754
Processing row 156/7754
Processing row 157/7754
Processing row 158/7754
Processing row 159/7754
Processing row 160/7754
Processing row 161/7754
Processing row 162/7754
Processing row 163/7754
Processing row 164/7754
Processing row 165/7754
Processing row 166/7754
Processing row 167/7754
Processing row 168/7754
Processing row 169/7754
Processing row 170/7754
Processing row 171/7754
Processing row 172/7754
Processing row 173/7754
Processing row 174/7754
Processing row 175/7754
Processing row 176/7754
Processing row 177/7754
Processing row 178/7754
Processing row 179/7754
Processing row 180/7754
Processing row 181/7754
Processing row 182/7754
Processing row 183/7754
Processing row 184/7754
Processing row 185/7754
Processing row 186/7754
Processing row 187/7754
Processing row 188/7754
Processing row 189/7754
Processing row 190/7754
Processing row 191/7754
Processing row 192/7754
Processing row 193/7754
Processing row 194/7754
Processing row 195/7754
Processing row 196/7754
Processing row 197/7754
Processing row 198/7754
Processing row 199/7754
Processing row 200/7754
Processing row 201/7754
Processing row 202/7754
Processing row 203/7754
Processing row 204/7754
Processing row 205/7754
Processing row 206/7754
Processing row 207/7754
Processing row 208/7754
Processing row 209/7754
Processing row 210/7754
Processing row 211/7754
Processing row 212/7754
Processing row 213/7754
Processing row 214/7754
Processing row 215/7754
Processing row 216/7754
Processing row 217/7754
Processing row 218/7754
Processing row 219/7754
Processing row 220/7754
Processing row 221/7754
Processing row 222/7754
Processing row 223/7754
Processing row 224/7754
Processing row 225/7754
Processing row 226/7754
Processing row 227/7754
Processing row 228/7754
Processing row 229/7754
Processing row 230/7754
Processing row 231/7754
Processing row 232/7754
Processing row 233/7754
Processing row 234/7754
Processing row 235/7754
Processing row 236/7754
Processing row 237/7754
Processing row 238/7754
Processing row 239/7754
Processing row 240/7754
Processing row 241/7754
Processing row 242/7754
Processing row 243/7754
Processing row 244/7754
Processing row 245/7754
Processing row 246/7754
Processing row 247/7754
Processing row 248/7754
Processing row 249/7754
Processing row 250/7754
Processing row 251/7754
Processing row 252/7754
Processing row 253/7754
Processing row 254/7754
Processing row 255/7754
Processing row 256/7754
Processing row 257/7754
Processing row 258/7754
Processing row 259/7754
Processing row 260/7754
Processing row 261/7754
Processing row 262/7754
Processing row 263/7754
Processing row 264/7754
Processing row 265/7754
Processing row 266/7754
Processing row 267/7754
Processing row 268/7754
Processing row 269/7754
Processing row 270/7754
Processing row 271/7754
Processing row 272/7754
Processing row 273/7754
Processing row 274/7754
Processing row 275/7754
Processing row 276/7754
Processing row 277/7754
Processing row 278/7754
Processing row 279/7754
Processing row 280/7754
Processing row 281/7754
Processing row 282/7754
Processing row 283/7754
Processing row 284/7754
Processing row 285/7754
Processing row 286/7754
Processing row 287/7754
Processing row 288/7754
Processing row 289/7754
Processing row 290/7754
Processing row 291/7754
Processing row 292/7754
Processing row 293/7754
Processing row 294/7754
Processing row 295/7754
Processing row 296/7754
Processing row 297/7754
Processing row 298/7754
Processing row 299/7754
Processing row 300/7754
Processing row 301/7754
Processing row 302/7754
Processing row 303/7754
Processing row 304/7754
Processing row 305/7754
Processing row 306/7754
Processing row 307/7754
Processing row 308/7754
Processing row 309/7754
Processing row 310/7754
Processing row 311/7754
Processing row 312/7754
Processing row 313/7754
Processing row 314/7754
Processing row 315/7754
Processing row 316/7754
Processing row 317/7754
Processing row 318/7754
Processing row 319/7754
Processing row 320/7754
Processing row 321/7754
Processing row 322/7754
Processing row 323/7754
Processing row 324/7754
Processing row 325/7754
Processing row 326/7754
Processing row 327/7754
Processing row 328/7754
Processing row 329/7754
Processing row 330/7754
Processing row 331/7754
Processing row 332/7754
Processing row 333/7754
Processing row 334/7754
Processing row 335/7754
Processing row 336/7754
Processing row 337/7754
Processing row 338/7754
Processing row 339/7754
Processing row 340/7754
Processing row 341/7754
Processing row 342/7754
Processing row 343/7754
Processing row 344/7754
Processing row 345/7754
Processing row 346/7754
Processing row 347/7754
Processing row 348/7754
Processing row 349/7754
Processing row 350/7754
Processing row 351/7754
Processing row 352/7754
Processing row 353/7754
Processing row 354/7754
Processing row 355/7754
Processing row 356/7754
Processing row 357/7754
Processing row 358/7754
Processing row 359/7754
Processing row 360/7754
Processing row 361/7754
Processing row 362/7754
Processing row 363/7754
Processing row 364/7754
Processing row 365/7754
Processing row 366/7754
Processing row 367/7754
Processing row 368/7754
Processing row 369/7754
Processing row 370/7754
Processing row 371/7754
Processing row 372/7754
Processing row 373/7754
Processing row 374/7754
Processing row 375/7754
Processing row 376/7754
Processing row 377/7754
Processing row 378/7754
Processing row 379/7754
Processing row 380/7754
Processing row 381/7754
Processing row 382/7754
Processing row 383/7754
Processing row 384/7754
Processing row 385/7754
Processing row 386/7754
Processing row 387/7754
Processing row 388/7754
Processing row 389/7754
Processing row 390/7754
Processing row 391/7754
Processing row 392/7754
Processing row 393/7754
Processing row 394/7754
Processing row 395/7754
Processing row 396/7754
Processing row 397/7754
Processing row 398/7754
Processing row 399/7754
Processing row 400/7754
Processing row 401/7754
Processing row 402/7754
Processing row 403/7754
Processing row 404/7754
Processing row 405/7754
Processing row 406/7754
Processing row 407/7754
Processing row 408/7754
Processing row 409/7754
Processing row 410/7754
Processing row 411/7754
Processing row 412/7754
Processing row 413/7754
Processing row 414/7754
Processing row 415/7754
Processing row 416/7754
Processing row 417/7754
Processing row 418/7754
Processing row 419/7754
Processing row 420/7754
Processing row 421/7754
Processing row 422/7754
Processing row 423/7754
Processing row 424/7754
Processing row 425/7754
Processing row 426/7754
Processing row 427/7754
Processing row 428/7754
Processing row 429/7754
Processing row 430/7754
Processing row 431/7754
Processing row 432/7754
Processing row 433/7754
Processing row 434/7754
Processing row 435/7754
Processing row 436/7754
Processing row 437/7754
Processing row 438/7754
Processing row 439/7754
Processing row 440/7754
Processing row 441/7754
Processing row 442/7754
Processing row 443/7754
Processing row 444/7754
Processing row 445/7754
Processing row 446/7754
Processing row 447/7754
Processing row 448/7754
Processing row 449/7754
Processing row 450/7754
Processing row 451/7754
Processing row 452/7754
Processing row 453/7754
Processing row 454/7754
Processing row 455/7754
Processing row 456/7754
Processing row 457/7754
Processing row 458/7754
Processing row 459/7754
Processing row 460/7754
Processing row 461/7754
Processing row 462/7754
Processing row 463/7754
Processing row 464/7754
Processing row 465/7754
Processing row 466/7754
Processing row 467/7754
Processing row 468/7754
Processing row 469/7754
Processing row 470/7754
Processing row 471/7754
Processing row 472/7754
Processing row 473/7754
Processing row 474/7754
Processing row 475/7754
Processing row 476/7754
Processing row 477/7754
Processing row 478/7754
Processing row 479/7754
Processing row 480/7754
Processing row 481/7754
Processing row 482/7754
Processing row 483/7754
Processing row 484/7754
Processing row 485/7754
Processing row 486/7754
Processing row 487/7754
Processing row 488/7754
Processing row 489/7754
Processing row 490/7754
Processing row 491/7754
Processing row 492/7754
Processing row 493/7754
Processing row 494/7754
Processing row 495/7754
Processing row 496/7754
Processing row 497/7754
Processing row 498/7754
Processing row 499/7754
Processing row 500/7754
Processing row 501/7754
Processing row 502/7754
Processing row 503/7754
Processing row 504/7754
Processing row 505/7754
Processing row 506/7754
Processing row 507/7754
Processing row 508/7754
Processing row 509/7754
Processing row 510/7754
Processing row 511/7754
Processing row 512/7754
Processing row 513/7754
Processing row 514/7754
Processing row 515/7754
Processing row 516/7754
Processing row 517/7754
Processing row 518/7754
Processing row 519/7754
Processing row 520/7754
Processing row 521/7754
Processing row 522/7754
Processing row 523/7754
Processing row 524/7754
Processing row 525/7754
Processing row 526/7754
Processing row 527/7754
Processing row 528/7754
Processing row 529/7754
Processing row 530/7754
Processing row 531/7754
Processing row 532/7754
Processing row 533/7754
Processing row 534/7754
Processing row 535/7754
Processing row 536/7754
Processing row 537/7754
Processing row 538/7754
Processing row 539/7754
Processing row 540/7754
Processing row 541/7754
Processing row 542/7754
Processing row 543/7754
Processing row 544/7754
Processing row 545/7754
Processing row 546/7754
Processing row 547/7754
Processing row 548/7754
Processing row 549/7754
Processing row 550/7754
Processing row 551/7754
Processing row 552/7754
Processing row 553/7754
Processing row 554/7754
Processing row 555/7754
Processing row 556/7754
Processing row 557/7754
Processing row 558/7754
Processing row 559/7754
Processing row 560/7754
Processing row 561/7754
Processing row 562/7754
Processing row 563/7754
Processing row 564/7754
Processing row 565/7754
Processing row 566/7754
Processing row 567/7754
Processing row 568/7754
Processing row 569/7754
Processing row 570/7754
Processing row 571/7754
Processing row 572/7754
Processing row 573/7754
Processing row 574/7754
Processing row 575/7754
Processing row 576/7754
Processing row 577/7754
Processing row 578/7754
Processing row 579/7754
Processing row 580/7754
Processing row 581/7754
Processing row 582/7754
Processing row 583/7754
Processing row 584/7754
Processing row 585/7754
Processing row 586/7754
Processing row 587/7754
Processing row 588/7754
Processing row 589/7754
Processing row 590/7754
Processing row 591/7754
Processing row 592/7754
Processing row 593/7754
Processing row 594/7754
Processing row 595/7754
Processing row 596/7754
Processing row 597/7754
Processing row 598/7754
Processing row 599/7754
Processing row 600/7754
Processing row 601/7754
Processing row 602/7754
Processing row 603/7754
Processing row 604/7754
Processing row 605/7754
Processing row 606/7754
Processing row 607/7754
Processing row 608/7754
Processing row 609/7754
Processing row 610/7754
Processing row 611/7754
Processing row 612/7754
Processing row 613/7754
Processing row 614/7754
Processing row 615/7754
Processing row 616/7754
Processing row 617/7754
Processing row 618/7754
Processing row 619/7754
Processing row 620/7754
Processing row 621/7754
Processing row 622/7754
Processing row 623/7754
Processing row 624/7754
Processing row 625/7754
Processing row 626/7754
Processing row 627/7754
Processing row 628/7754
Processing row 629/7754
Processing row 630/7754
Processing row 631/7754
Processing row 632/7754
Processing row 633/7754
Processing row 634/7754
Processing row 635/7754
Processing row 636/7754
Processing row 637/7754
Processing row 638/7754
Processing row 639/7754
Processing row 640/7754
Processing row 641/7754
Processing row 642/7754
Processing row 643/7754
Processing row 644/7754
Processing row 645/7754
Processing row 646/7754
Processing row 647/7754
Processing row 648/7754
Processing row 649/7754
Processing row 650/7754
Processing row 651/7754
Processing row 652/7754
Processing row 653/7754
Processing row 654/7754
Processing row 655/7754
Processing row 656/7754
Processing row 657/7754
Processing row 658/7754
Processing row 659/7754
Processing row 660/7754
Processing row 661/7754
Processing row 662/7754
Processing row 663/7754
Processing row 664/7754
Processing row 665/7754
Processing row 666/7754
Processing row 667/7754
Processing row 668/7754
Processing row 669/7754
Processing row 670/7754
Processing row 671/7754
Processing row 672/7754
Processing row 673/7754
Processing row 674/7754
Processing row 675/7754
Processing row 676/7754
Processing row 677/7754
Processing row 678/7754
Processing row 679/7754
Processing row 680/7754
Processing row 681/7754
Processing row 682/7754
Processing row 683/7754
Processing row 684/7754
Processing row 685/7754
Processing row 686/7754
Processing row 687/7754
Processing row 688/7754
Processing row 689/7754
Processing row 690/7754
Processing row 691/7754
Processing row 692/7754
Processing row 693/7754
Processing row 694/7754
Processing row 695/7754
Processing row 696/7754
Processing row 697/7754
Processing row 698/7754
Processing row 699/7754
Processing row 700/7754
Processing row 701/7754
Processing row 702/7754
Processing row 703/7754
Processing row 704/7754
Processing row 705/7754
Processing row 706/7754
Processing row 707/7754
Processing row 708/7754
Processing row 709/7754
Processing row 710/7754
Processing row 711/7754
Processing row 712/7754
Processing row 713/7754
Processing row 714/7754
Processing row 715/7754
Processing row 716/7754
Processing row 717/7754
Processing row 718/7754
Processing row 719/7754
Processing row 720/7754
Processing row 721/7754
Processing row 722/7754
Processing row 723/7754
Processing row 724/7754
Processing row 725/7754
Processing row 726/7754
Processing row 727/7754
Processing row 728/7754
Processing row 729/7754
Processing row 730/7754
Processing row 731/7754
Processing row 732/7754
Processing row 733/7754
Processing row 734/7754
Processing row 735/7754
Processing row 736/7754
Processing row 737/7754
Processing row 738/7754
Processing row 739/7754
Processing row 740/7754
Processing row 741/7754
Processing row 742/7754
Processing row 743/7754
Processing row 744/7754
Processing row 745/7754
Processing row 746/7754
Processing row 747/7754
Processing row 748/7754
Processing row 749/7754
Processing row 750/7754
Processing row 751/7754
Processing row 752/7754
Processing row 753/7754
Processing row 754/7754
Processing row 755/7754
Processing row 756/7754
Processing row 757/7754
Processing row 758/7754
Processing row 759/7754
Processing row 760/7754
Processing row 761/7754
Processing row 762/7754
Processing row 763/7754
Processing row 764/7754
Processing row 765/7754
Processing row 766/7754
Processing row 767/7754
Processing row 768/7754
Processing row 769/7754
Processing row 770/7754
Processing row 771/7754
Processing row 772/7754
Processing row 773/7754
Processing row 774/7754
Processing row 775/7754
Processing row 776/7754
Processing row 777/7754
Processing row 778/7754
Processing row 779/7754
Processing row 780/7754
Processing row 781/7754
Processing row 782/7754
Processing row 783/7754
Processing row 784/7754
Processing row 785/7754
Processing row 786/7754
Processing row 787/7754
Processing row 788/7754
Processing row 789/7754
Processing row 790/7754
Processing row 791/7754
Processing row 792/7754
Processing row 793/7754
Processing row 794/7754
Processing row 795/7754
Processing row 796/7754
Processing row 797/7754
Processing row 798/7754
Processing row 799/7754
Processing row 800/7754
Processing row 801/7754
Processing row 802/7754
Processing row 803/7754
Processing row 804/7754
Processing row 805/7754
Processing row 806/7754
Processing row 807/7754
Processing row 808/7754
Processing row 809/7754
Processing row 810/7754
Processing row 811/7754
Processing row 812/7754
Processing row 813/7754
Processing row 814/7754
Processing row 815/7754
Processing row 816/7754
Processing row 817/7754
Processing row 818/7754
Processing row 819/7754
Processing row 820/7754
Processing row 821/7754
Processing row 822/7754
Processing row 823/7754
Processing row 824/7754
Processing row 825/7754
Processing row 826/7754
Processing row 827/7754
Processing row 828/7754
Processing row 829/7754
Processing row 830/7754
Processing row 831/7754
Processing row 832/7754
Processing row 833/7754
Processing row 834/7754
Processing row 835/7754
Processing row 836/7754
Processing row 837/7754

In [32]:
df_datashare_collapse

,dc.contributor,dc.contributor.other,dc.coverage.spatial,dc.coverage.temporal,dc.creator,dc.date.accessioned,dc.date.available,dc.identifier.citation,dc.identifier.uri,dc.description.abstract,...,dc.description,dc.description.sponsorship,dc.relation.ispartofseries,ds.withdrawn.showtombstone,dc.relation.isbasedon,dcterms.rights,dc.relation.ispartof,dcterms.isReplacedBy,dcterms.publisher,dc.description.abstract_clean
0,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['wolverhampton city', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t16:00:22z'],['2023-05-17t16:00:22z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/8181', 'https:/...","[""multi-storey block details: two 8-storey blo...",...,,,,,,,,,,"[block, details, two, blocks, containing, dwel..."
1,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['enfield london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t13:55:10z'],['2023-05-17t13:55:10z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/5559', 'https:/...","[""multi-storey block details: four 12-storey b...",...,,,,,,,,,,"[block, details, four, blocks, containing, dwe..."
2,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['ab11 8tw; ab11 8tx; ab11 8ty', 'aberdeen', '...",['start=1983; end=1983; scheme=w3c-dtf'],"['glendinning, miles']",['2019-11-14t09:55:05z'],['2019-11-14t09:55:05z'],"['glendinning, miles. (2019). sc_1141943.png, ...","['https://hdl.handle.net/10283/3445', 'https:/...","[""multi-storey block details: three 14-storey ...",...,,,,,,,,,,"[block, details, three, blocks, containing, dw..."
3,"['kim, jinho']",['university of edinburgh'],,,"['kim, jinho']",['2017-06-14t11:00:41z'],['2017-06-14t11:00:41z'],"['kim, jinho. (2017). source codes of the netw...","['https://hdl.handle.net/10283/2737', 'https:/...",['this data set contains the source codes for ...,...,,,,,,,,,,"[data, set, contains, source, codes, simulatio..."
4,"['anjos, miguel']",['university of edinburgh'],,,"['burkard, re', 'çela, e', 'karisch, se', 'ren...",['2022-03-31t16:59:08z'],['2022-03-31t16:59:08z'],"['burkard, re; çela, e; karisch, se; rendl, f;...","['https://hdl.handle.net/10283/4390', 'https:/...",['the quadratic assignment problem (qap) has r...,...,,,,,,,,,,"[quadratic, assignment, problem, qap, remained..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7749,"['nadal, cathe desiree']",['self-funded'],"['cavite', 'cavite, philippines', 'ph', 'phili...",,"['nadal, cathe desire', 'del rosario, tovie cl...",['2022-10-11t14:40:23z'],['2022-10-11t14:40:23z'],"['nadal, cathe desire; del rosario, tovie clar...","['https://hdl.handle.net/10283/4758', 'https:/...","['""capturing the dynamic character of the phil...",...,,,,,,,,,,"[capturing, dynamic, character, philippine, la..."
7750,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['sefton', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t15:43:57z'],['2023-05-17t15:43:57z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/7742', 'https:/...","[""multi-storey block details: one 16-storey bl...",...,,,,,,,,,,"[block, details, one, block, containing, dwell..."
7751,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['camden london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t13:34:44z'],['2023-05-17t13:34:44z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/5355', 'https:/...","[""multi-storey block details: cs 1: eleven 6-s...",...,,,,,,,,,,"[block, details, cs, eleven, blocks, containin..."
7752,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['salford city', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t15:41:06z'],['2023-05-17t15:41:06z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/7619', 'https:/...","[""multi-storey block details: one 20-storey bl...",...,,,,,,,,,,"[block, details, one, block, containing, dwell..."
7753,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['haringey london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t14:24:17z'],['2023-05-17t14:24:17z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/6047', 'https:/...","[""multi-storey block details: one 6-storey blo...",...,,,,,,,,,,"[block, details, one, block, containing, dwell..."

In [33]:
list_headers_stats_clean = ["dc.description.abstract_clean"]

In [34]:
df_datashare_collapse["dc.description.abstract_clean_word_count"] = pd.Series(index = df_datashare_collapse.index, dtype="object")

In [35]:
# Word count
df_datashare_collapse["dc.description.abstract_clean_word_count"] = (
    df_datashare_collapse["dc.description.abstract_clean"]
      .apply(lambda x: len(x) if isinstance(x, list) else 0)
)

In [36]:
# Creating the empty columns for lemma text and entities 
for header in list_headers_stats_clean:
    df_datashare_collapse[f"{header}_lemmatize"] = pd.Series(index = df_datashare_collapse.index, dtype="object")
    df_datashare_collapse[f"{header}_entities"]  = pd.Series(index = df_datashare_collapse.index, dtype="object")

In [37]:
def to_text(x):
    # missing
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return ""
    # already a string
    if isinstance(x, str):
        return x
    # list/tuple/set/np array of tokens
    if isinstance(x, (list, tuple, set, np.ndarray)):
        return " ".join(map(str, x))
    # fallback: convert whatever it is to string
    return str(x)

In [38]:
# Lemmatisation and entity recognition
for idx, row in df_datashare_collapse.iterrows():
    for header in list_headers_stats_clean: 
        
        text = df_datashare_collapse.at[idx, header]
        join_text = to_text(text)
        
        lemma_str = lemmatizer("" if pd.isna(join_text) else str(join_text))
        title_lemma = f"{header}_lemmatize"
        df_datashare_collapse.at[idx, title_lemma] = lemma_str

        entities = entities_recognition(lemma_str)
        title_entities = f"{header}_entities"
        df_datashare_collapse.at[idx, title_entities] = entities

In [39]:
df_datashare_collapse

,dc.contributor,dc.contributor.other,dc.coverage.spatial,dc.coverage.temporal,dc.creator,dc.date.accessioned,dc.date.available,dc.identifier.citation,dc.identifier.uri,dc.description.abstract,...,ds.withdrawn.showtombstone,dc.relation.isbasedon,dcterms.rights,dc.relation.ispartof,dcterms.isReplacedBy,dcterms.publisher,dc.description.abstract_clean,dc.description.abstract_clean_word_count,dc.description.abstract_clean_lemmatize,dc.description.abstract_clean_entities
0,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['wolverhampton city', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t16:00:22z'],['2023-05-17t16:00:22z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/8181', 'https:/...","[""multi-storey block details: two 8-storey blo...",...,,,,,,,"[block, details, two, blocks, containing, dwel...",149,block detail two block contain dwelling block ...,"[(block), (block), (block), (wulfruna), (wulfr..."
1,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['enfield london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t13:55:10z'],['2023-05-17t13:55:10z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/5559', 'https:/...","[""multi-storey block details: four 12-storey b...",...,,,,,,,"[block, details, four, blocks, containing, dwe...",153,block detail four block contain dwelling block...,"[(block), (block), (block), (picardy, house, n..."
2,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['ab11 8tw; ab11 8tx; ab11 8ty', 'aberdeen', '...",['start=1983; end=1983; scheme=w3c-dtf'],"['glendinning, miles']",['2019-11-14t09:55:05z'],['2019-11-14t09:55:05z'],"['glendinning, miles. (2019). sc_1141943.png, ...","['https://hdl.handle.net/10283/3445', 'https:/...","[""multi-storey block details: three 14-storey ...",...,,,,,,,"[block, details, three, blocks, containing, dw...",146,block detail three block contain dwelling bloc...,"[(block, detail), (block), (block), (grampian)..."
3,"['kim, jinho']",['university of edinburgh'],,,"['kim, jinho']",['2017-06-14t11:00:41z'],['2017-06-14t11:00:41z'],"['kim, jinho. (2017). source codes of the netw...","['https://hdl.handle.net/10283/2737', 'https:/...",['this data set contains the source codes for ...,...,,,,,,,"[data, set, contains, source, codes, simulatio...",23,datum set contain source code simulation prese...,"[(code, simulation), (thompson, centralized, r..."
4,"['anjos, miguel']",['university of edinburgh'],,,"['burkard, re', 'çela, e', 'karisch, se', 'ren...",['2022-03-31t16:59:08z'],['2022-03-31t16:59:08z'],"['burkard, re; çela, e; karisch, se; rendl, f;...","['https://hdl.handle.net/10283/4390', 'https:/...",['the quadratic assignment problem (qap) has r...,...,,,,,,,"[quadratic, assignment, problem, qap, remained...",39,quadratic assignment problem qap remain one gr...,"[(quadratic, assignment, problem, qap), (combi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7749,"['nadal, cathe desiree']",['self-funded'],"['cavite', 'cavite, philippines', 'ph', 'phili...",,"['nadal, cathe desire', 'del rosario, tovie cl...",['2022-10-11t14:40:23z'],['2022-10-11t14:40:23z'],"['nadal, cathe desire; del rosario, tovie clar...","['https://hdl.handle.net/10283/4758', 'https:/...","['""capturing the dynamic character of the phil...",...,,,,,,,"[capturing, dynamic, character, philippine, la...",49,capture dynamic character philippine landscape...,"[(dynamic), (landscape), (landscape), (cavite)..."
7750,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['sefton', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t15:43:57z'],['2023-05-17t15:43:57z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/7742', 'https:/...","[""multi-storey block details: one 16-storey bl...",...,,,,,,,"[block, details, one, block, containing, dwell...",145,block detail one block contain dwelling block ...,"[(block, detail), (block), (block), (oxford), ..."
7751,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['camden london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t13:34:44z'],['2023-05-17t13:34:44z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/5355', 'https:/...","[""multi-storey block details: cs 1: eleven 6-s...",...,,,,,,,"[block, details, cs, eleven, blocks, containin...",184,block detail cs eleven block contain dwelling ...,"[(block, detail), (block), (block), (block), (..."
7752,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['salford city', 'united kingdom']",['start=1987; end=1987; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t15:41:06z'],['2023-05-17t15:41:06z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/7619', 'https:/...","[""multi-storey block details: one 20-storey bl...",...,,,,,,,"[block, details, one, block, containing, dwell...",145,block detail one block contain dwelling block ...,"[(block, detail), (block), (block), (house, im..."
7753,"['glendinning, miles', 'breen, kat']",['heritage lottery fund'],"['haringey london', 'united kingdom']",['start=1988; end=1988; scheme=w3c-dtf'],"['glendinning, miles']",['2023-05-17t14:24:17z'],['2023-05-17t14:24:17z'],"['glendinning, miles. (2023). tower blocks uk:...","['https://hdl.handle.net/10283/6047', 'https:/...","[""multi-storey block details: one 6-storey blo...",...,,,,,,,"[block, details, one, block, containing, dwell...",145,block detail one block contain dwelling block ...,"[(block, detail), (block), (block), (carlton),..."

### Saving the dataset for future work

In [40]:
os.getcwd()

'/home/eidf128/eidf128/shared/export/juliana/export/juliana/items'

In [41]:
cd ..

/home/eidf128/eidf128/shared/export/juliana/export/juliana

In [42]:
df_datashare_collapse.to_csv("df_datashare_collpase_20260311.csv")

### Organize by communities

In [43]:
pwd

'/home/eidf128/eidf128/shared/export/juliana/export/juliana'

In [44]:
with open("items_medicine_datashare_oct2024.txt", "r", encoding="utf-8") as f:
    items_medicine = [line.strip() for line in f if line.strip()]  # strips \n and skips blank lines

items_medicine

['6565c13c-ceec-42cb-b180-fac9d0d70cd4',
 '284b0f32-35a6-4397-bd73-2e33e3a07760',
 '7d2543c5-41f2-48be-bef1-05e18565fa88',
 '221e08d6-3494-4927-aef3-e2bfb3c13274',
 '0556a87c-baad-44db-a738-b243f113cfb2',
 '328ad395-1ac4-4a4c-8d27-5b95577eabfc',
 '7c27ab9f-2c89-45a7-b02e-0c809b13ca25',
 'd6601a32-c3f1-4114-8f84-06c133579dd2',
 '74369ef7-ad36-4f28-a3ca-f109aff00012',
 'b2537efa-43a6-4827-a53c-210bafc5d997',
 '36280bf4-0599-4102-bd44-dc0dad71864b',
 '6e1770f2-4991-44b4-a80e-011877c11c2a',
 '43408586-d464-4708-886c-6643e3be2b56',
 'd57a2aff-e21b-4ac0-9bc6-82ae98849ea5',
 '40b3a371-396f-44bc-9e89-8b7ec42f5215',
 '5fba0c7d-7f28-4a49-8fc2-3a1370aa4b4a',
 '674861f3-06ba-496a-899f-235fcb69e03d',
 '91709c88-d913-45d8-8019-380027133d54',
 '917f03d6-9eae-4b3d-b65c-b3a14cb350ba',
 '7a79f454-c747-4508-aa51-7b1bd412ce87',
 '738c746b-236e-4111-9b5d-64e181620b12',
 '7e6927f7-d321-47c0-8e1f-998f8c50433a',
 'c82e227a-af6c-4933-a242-71ee96fb0491',
 '7091a3e4-4ed3-46a7-b004-f9cf557795bd',
 'be522ba9-f16e-4b89-ba8b-f80674fd35bd',
 '7726963e-921c-4459-bba4-171c20bf57f0',
 'e70467b3-d568-4228-8e56-3d428c75b2a1',
 'db636a69-8709-4196-9e32-32df99129661',
 '4ed2bcaa-1d4a-4649-b01b-eef96b22c743',
 '052d4f94-a1f9-44e0-8717-2f835316e238',
 '086a4f6e-9a2f-448f-82ed-e7af6947838f',
 'c8318af8-2fdb-4521-b6ef-8cfe96f2ecad',
 'a38d4371-c34c-48df-981a-0867df8e5071',
 '77ff1919-d469-4adc-ab71-a7b6b1c2ae7e',
 '32dce178-9a43-4dd0-a716-ac57c1835462',
 '72fcd198-920b-4a6a-b739-58797eeeec4f',
 '66fc38b3-6087-4ea6-bdda-497ab61cf8e8',
 '6045a88d-c169-4c80-892a-8b86edb9edcd',
 '9ff4c497-f7cc-4cfd-ae60-5cd9f8f4b778',
 '7ab77d4a-9293-459d-9e4d-b1a2ac4b154e',
 '156b411d-e03e-443e-97ec-3f8fddbcb73e',
 '5e035926-7c08-477c-802c-980fc1053fc9',
 '72ab8ce0-689f-4b4a-84a3-f885eaad8b1b',
 'c9b42de6-6e4b-451f-9039-38762ebbb47b',
 'd024e739-ee97-4a7f-89df-4e47dd593b2f',
 '08f7eff2-c83d-4893-9860-5b5f1da78595',
 '87428f2a-7a82-43d2-90de-51afd0a4391c',
 'c1927b32-75bb-49f3-b62e-84370800640c',
 '727c7909-8177-4be4-9c50-4538cf7d8558',
 '709d6921-e576-4b0c-bd71-8fcb7e2ad2ac',
 '8be313bf-8967-4ff8-839a-ff8c84f71b7c',
 'f35e49ed-21ca-4323-96c1-36ddddad5920',
 '75ff5f65-6f24-4705-9d70-b758f391b432',
 'e95826be-4f17-4512-8598-1fd7911f6265',
 'd0be0285-83c8-4f84-8dec-ecd03c31918f',
 '066493b8-c1fb-4893-958e-c91bc05dd105',
 'b689297b-3aeb-49d7-82a4-38c09961bf09',
 '6c5edf8a-f079-4b03-9e29-38481512ec26',
 'c0f443ce-e173-430e-b1cf-55e035c72659',
 '652b403f-018a-477e-9903-9ecb3d9502d4',
 '62afe70a-c483-49d1-bff2-9f462b8db4b7',
 'bad885c3-4155-4299-adff-d7c590604a38',
 '7c18f0d5-6093-4795-bd97-71c3b3aa4b7a',
 'a8eac73b-d954-4717-87a5-31698d8f1e13',
 'cfd3fbad-7fa2-4fee-811c-47ed91f1cbd5',
 '9e3161f3-cdf2-4ca0-8a87-5fc7946aa1f9',
 '35cfe352-0f71-4212-8046-999939cb9d29',
 '0511c6f8-03a8-4ccb-9b36-0d373472be6f',
 'c24f67fe-294a-40f0-a17e-d53172643417',
 '43ca2cdd-74e8-43ed-869a-54a0c2e2182c',
 '23730b46-54f0-46df-bc01-13149cf2a226',
 '33a67d06-813a-4081-bc0d-020d222636df',
 '65aaefab-d415-4954-95e5-cf8dbf649f7d',
 'a4b6ea33-6234-424e-988d-ee3329903a1a',
 '4d939b2c-cba4-4cfe-9f71-2481c1de7ba4',
 '50ea863c-ac9b-4f4c-913e-f7cd1efce436',
 '6169f6f4-3d44-41ac-bdc1-986e4a11eebf',
 '42ab3af4-ee6f-49cf-9729-3c1227abc843',
 '77885d8f-5dbc-4084-9042-69ef80de9568',
 'c68fb8e5-8240-4506-a697-ad86e110a9ab',
 'dc2c6c1c-e36e-47ce-861d-ee7d40198bd6',
 'c9b1dce5-4812-41dd-950e-be02184830e9',
 '69bb6377-d41e-47a3-986f-598356470641',
 '972e4731-fba3-4fce-b032-64ef52c0bc00',
 '93376bd7-db24-41de-b58b-c9887b8c9565',
 'fc721be7-e23f-49d5-a55c-0fefe927ddaa',
 'ad70c9fd-f3f7-4bac-90ce-deadc2908b09',
 'ec03a726-e4e6-4a98-b095-4da55730e5fd',
 '91437612-790b-4b98-a61f-2be976041c2b',
 '4f15b84e-8d56-409c-a586-a41b54b5d529',
 'fd951bb3-12f7-412d-b980-5e2d53f486c3',
 '2ca9a0b4-8a30-4804-a864-0f6d9192e9e0',
 '695cf685-09e5-4bba-b86d-220533ae6da3',
 'f338c3a9-4d79-4741-9d51-a9acfc3a8c0c',
 '0b41a2b3-d60c-4026-bed5-7a1eb6b10b16',
 '800002a6-dc01-4e69-89a6-2f62f5ba4a23',
 'bf0e7a55-7494-4b47-99c3-a7c299771777',
 'b321c8fe-2769-4ee7-bef2-a5d60ff41a9a',
 'c5272648-2cf6-44a6-a002-a284405f85af',
 'f26bfcdc-23ab-4fbb-9b2b-18feb59616d7',
 '655ac3aa-56b7-42ae-86c2-032ee7062ef0',
 '027c9dcb-6ef2-49b2-869d-b4ebb1eb6097',
 'b7294a3c-50f2-4476-a558-be995b1070a2',
 '2db73c26-884b-4b3f-b5f3-94e63142d1b4',
 '67a94c17-c33d-465d-afe1-04e34606138b',
 'a6b5a30f-6781-4887-9a64-d2e7b1d1338f',
 '1fae8a2d-2f04-4b13-b647-6678744527be',
 '58756963-9db5-42a0-9493-e1a606681a10',
 '40864a4a-4d5c-4694-9fa5-a74aec1ead10',
 '7e15311a-f961-4759-b75c-7e35314b2eb4',
 '55a9e13b-10d2-4f1f-9bf5-98adb25f31cb',
 'acebf702-7850-400c-8dfb-b26fe85c559e',
 '5d698a5d-d556-4af7-b2ff-34987798a705',
 '525a3213-5092-442f-aca4-58b06e160218',
 '43896270-82ce-45c3-9db1-52db6e99227c',
 '02fbedba-0189-4b5c-9b99-eaa6c27a9885',
 '206b9cb2-94d5-411b-abfb-332b79d8b92d',
 'c0b4f4f8-c08d-4a23-961c-42c5fd60da15',
 '75d3cc80-f241-4ed6-ac67-db0fa1f1421c',
 '48104b38-a3a0-4491-acc6-da348c3e026e',
 '1512fd53-1b95-4e7a-9389-3cf7eebf4d93',
 'e9729855-109f-4ed4-8c71-9b2529b49d8c',
 '43c08e4e-4d7e-4498-a6e7-c863494503a7',
 '5866199b-0eee-4702-91a7-89348b040dc8',
 '988ee071-ec53-4a2a-a86d-e33f24714316',
 '9e90e843-d903-4442-9435-f665f64c912a',
 'ee009e45-87b5-434e-9c81-6d3c4def4b2b',
 '882e362b-268a-4acc-b209-2e3461665759',
 '309b87e6-7c0d-4ea0-845a-363dc1323e15',
 '2872cd81-6509-4fbc-a358-504b8f7324ef',
 '575919ed-ed02-4b79-aec4-83c7ed1d07c0',
 '7f3b23e8-a08e-4180-a31a-7047ad893d26',
 'a5b668f1-d944-4346-954f-b9d3290f2767',
 '52d16d30-a2dd-46ee-906c-59c4380d9e70',
 '12842672-640d-4e72-a225-b53372893eb7',
 '84448a62-b796-440b-8ce6-16ceb8e1f241',
 '3a427eeb-5cb8-4ac1-be2a-1f4f16781f3b',
 '793289c0-aa84-44e6-8fae-b277722b6ebd',
 '076b77a1-f618-4def-b3db-ab66492c4f98',
 'b7312294-2e76-4718-a415-0b2792bc5fbc',
 'af561f74-fd2d-4b40-8a96-5ce56d66bfc8',
 'b8bc740a-9237-4abc-a4d2-37b93f95d96b',
 '48c1b1a4-d75f-49e6-90f0-3a1c0ff6b275',
 '9362bbbe-33bc-4766-a58a-393f3d4a506a',
 '44bbe98a-c8bc-4621-a81a-860fe77790b8',
 '8f275965-324b-4f95-9361-bfdce6345620',
 '4c970f79-37c9-414b-8ab4-32609402bca4',
 '743c1f3a-26df-4dc0-b1c9-fac49e991b30',
 'ba48b380-ffc5-4a48-90e0-017ac1e65276',
 '568e5d34-55e4-4ce6-90b7-802b0dc249e4',
 '002b623a-531a-443e-be4c-42c9de6ca768',
 '9e8f3d8b-8f07-4a86-9c7c-476d7363455f',
 'ec8b202b-6039-4669-8474-8e2f928460bd',
 '4a8d3d45-7384-45e8-b6ee-3c8b2fecddb5',
 '952f3e35-49ab-4cf1-b9ac-cb6cd90d2803',
 'b1e1a71d-cdd1-4ee3-92e4-5e0dd4ae8e1c',
 '4c99ea51-a49e-47c3-bb4c-1eadf8a0e839',
 '259c01a9-745c-46a5-b653-f6064158e1d6',
 '23266023-a2be-4382-bd3c-25c8dd938748',
 'c7155bf2-6395-433a-ba8d-abcc68a0cbeb',
 'a3c417b9-15b4-459e-854e-b309295557a8',
 'ebb63dc9-f4b0-41da-8a22-9aebb5b0bc1b',
 '16649f9e-4605-4bd1-9882-f59c2f7ea310',
 '96e3d830-6b65-4b04-85d4-81e9bef98ca7',
 'fefaa869-373d-4b8f-9519-08227a263606',
 '343d066d-ef98-44b5-aed4-8d6325074c87',
 '94ead366-8778-4bdb-8636-219cef94ab26',
 'd3104932-0e23-413a-88a8-a1dbe517cff2',
 '25bd9c36-73ed-41dd-8973-cd51c2b8ef1b',
 '65c6a7b6-1e07-479a-8e37-6d4899e3ab35',
 '3cb985ad-4a35-43cd-9622-e612417b0953',
 'f14b5006-dd8c-48b2-8f1f-0b4a102bc1e0',
 'a0092666-8900-4bf0-9bb6-33ea9f238496',
 '88205664-d322-4011-b922-f7c655bfb9b0',
 'b6bd1b5e-021b-42d5-8319-d7356affac0e',
 '9ee03bfc-d033-4d4c-ad40-8d12d9e825ff',
 '82ba2196-b153-47d3-92e7-5f71190a35ca',
 '6f8dfc25-92d6-4cb3-89e0-f8437b4e7c7c',
 '5fab5977-e49d-46e7-b1f0-78fe0e6478ad',
 '2714c903-fae4-430d-a12f-ce381009509e',
 '93a87c18-3ae0-4f67-a593-47ea6a724002',
 'e12400e3-852f-4035-8d73-aa2fd5004d0a',
 '037e6273-59a8-49e3-9fd4-45bcf3954558',
 '593b5e4d-543b-45ad-b386-6a00777a1ee0',
 '4225ce68-827e-4187-ad1e-729690e14a86',
 'e49f4915-f116-457b-8b10-0647f9bcfdb4',
 'a3b5ae40-c1d7-436a-ab6f-225bc67050a8',
 '9269f325-0d5a-44cc-ac8c-970e1fefc5dc',
 '12e18f11-6b2b-4e49-a57e-0b70796f10db',
 '3341f655-ded9-4034-a6df-7c63723c989c',
 '35d5115a-c57e-4cb7-9999-64e87142f40f',
 '4ff83b7d-e6ae-444f-99e7-2cf225c39d5c',
 '62d87067-b27b-4c03-b1bc-729c13934272',
 '242551cc-7034-4ec4-8c71-1115b829f552',
 '978c638e-36c3-4414-93d4-6bd0fac7ea5d',
 'ee58ca92-22e7-4b41-8fec-65fa7045118b',
 '5147ce08-935d-42d9-bb14-d6809a12a444',
 '0d63c4cc-b4d3-4d81-8dc3-ee07778de67e',
 'c849b856-a442-41b6-a895-1b6624248896',
 '534f5b5f-8e27-4561-a1ea-68a2d906f605',
 'ea576132-452c-4fe2-bca0-1e7a175ae205',
 '5a88045c-a5f2-472b-8595-78ba47dadf81',
 '2f6beffa-f9d6-40e9-b111-206e9bcf7275',
 '495e0dd6-db3b-439b-a3d9-e88dce1061e8',
 '45681a13-9c6c-402f-9fc7-e4fde6eeee03',
 'c6896ff0-bded-4eb7-9511-46e05b2ba7e5',
 '1c8c8c55-9e4d-44e6-8b20-a639c6994eb6',
 '6489e764-00de-4ed5-88e9-d39a6ef4bc5d',
 '4adbc689-8aa7-48b3-93df-457d4f45cc35',
 'cf8c904b-ce8d-4688-b0cb-5bdbfbd337b8',
 'e7d5cc57-7df5-4d1c-bb46-48d58d679238',
 '8478e384-fd1b-4a37-9555-0c6e1218e90b',
 'f2a529e3-b12d-43f9-ab2f-d300f2bf846f',
 '162ddc57-0281-45ba-ad9e-d0fb2d5188e5',
 '2f72401f-f900-4846-bab3-81537918984c',
 '38a422e2-fe50-4dec-aca8-9ecb0501c68f',
 'dd2fad03-2beb-42b0-8bdb-b21f8687e2ff',
 'a2a7628b-dd88-4eab-8a7e-2d34f5218894',
 'eed72f6d-1a97-4db1-9e9c-eb8dc2a72e00',
 '0e51ef10-d904-46bf-90cc-fd4e6c5b65d6',
 '6f603c2e-6d16-4f93-8ff9-0bce64f55400',
 '3c6f8a39-ad51-4b79-8cce-005c3cede781',
 'd150e6a5-7a07-4aad-91e2-77d77539f480',
 '58eec9a6-a993-4217-ad80-2b57274d288e',
 '9baf4f63-a631-433a-9899-4b95a3bf0316',
 'bed28e41-5570-4d57-b0a7-a41ca5657e1b',
 '722c1390-df71-4c1d-a555-76a06e07c12f',
 '1034cea8-d2ff-4161-b82f-5e9f2e4cb737',
 '208f284f-e94a-433d-b1a2-066afab63784',
 'fcc03ca3-2d9a-4f68-bf9f-a46d7431e6f5',
 '93ad74b2-af3c-42a0-b153-7e1b628078d2',
 '77559e44-c48a-4167-8fe4-0e525333f9c6',
 '8722ed88-7905-4b8f-85dd-cbb35866ea8c',
 '57a38478-3b1f-4304-84cb-f33c5e358b00',
 'ee2baac3-2fb5-44e7-8838-b4ab547ea8ad',
 'f76de340-4e38-4a2e-8353-3ec17c50c990',
 '9909aac8-7375-43ab-bf23-38cadac3dcf6',
 '502939d0-d758-4de3-8a5b-647eb60bee09',
 '6eeff53b-a41e-41b9-beb8-e091b5baa530',
 '2bdcf983-00c8-48bd-bde7-d41b59fae754',
 '554299f2-ade7-4111-8734-5b0f24c63570',
 '73430044-fc2c-4ef5-a2bb-09ed058fa486',
 '6c4a0ed7-4098-40a2-a4bb-d180cb6d1c60',
 'b1228362-147d-4d6d-a677-7385cc48cbda',
 '9aa94599-0f67-47dc-995d-1b0c9dfae612',
 'fc683641-1b1c-498f-bcee-462fe360558a',
 'b019375c-1216-4c68-be7e-8ddafeb708a7',
 '7c9a7994-058b-468c-9b13-d99d6be62cfd',
 '2b3c2032-7419-41b5-828c-a9b275d2c154',
 '7e597a33-3b43-48ab-b6df-113020413dd7',
 '2ad7f841-75b6-458d-9448-af7fb2314fda',
 '289a6485-20c0-4660-9ef2-bfc6ea137788',
 'e351479b-795b-47f5-8c6e-051cf9046750',
 '4d67512e-7512-4f9c-8090-4083d4718e4f',
 '4b2dc5a5-9203-4689-9876-727b4d45a941',
 '297495e8-0f6d-4538-848d-a72a89918fb7',
 '056f79b3-8efa-41d8-bac3-e2869602cd1c',
 '8e2efc19-9c35-4668-82d0-798117e0e01f',
 '9e55088e-60ae-4e6f-bf7d-d3b95600b47e',
 '887eae60-76de-4a64-823f-2e4386e31f1b',
 '23f918db-cdd8-4378-8f0b-19db41b9f0fd',
 'fab848cb-e4cf-459e-ae82-b1a063fd700f',
 'ae7ca3a9-9600-471c-bb19-f9e92e9c3c4b',
 '3509ecc4-7050-440f-ad6d-664c677aa262',
 'e91b83a4-b23f-48ba-88fd-6974e0994aca',
 '8cf38918-70b7-407b-8d06-670fa17f30ae',
 'ab42d70d-9853-4f48-a4ac-312e176d966c',
 'e9a9978b-d143-41ca-ae6b-e2be9ee14d5f',
 '28916223-fb09-427c-9ce9-b76d2370365a',
 'd5ed8d1b-cffe-4848-9165-87d42bf6eb64',
 'ee9c7959-7b9e-4193-828f-1f9db2d04211',
 '9de2dbe5-242b-4831-b615-837693584dff',
 '0b60f306-f79c-41d1-95b0-6fccfab54f75',
 '9a2fa80e-995e-40f2-97fc-203e674b32a5',
 'a54cb517-1585-46e3-9bb1-77139f357050',
 '1f26c6ef-9797-4cb5-bb96-58cd0c580d16',
 'ee76a9a0-ad04-407d-92f3-0969f84d543c',
 'bde35ce2-b6e6-41e0-8ca7-ca9e3885aeff',
 '3f0a2903-1756-4fdc-b7a7-98e91674c22a',
 '4cdc7ff5-b2bf-4420-ae7d-9b3b02b71e2c',
 'e8404a7d-ca28-4357-b0a1-49d7ecb75b2f',
 '92c56b5b-faf3-4eb4-8605-09058ab93e90',
 '1267a839-aa9a-4253-9f28-355f6c197afe',
 '871a56a6-bd0e-4a87-ae61-4f1c728bb9a2',
 'dbf5c577-5efb-418a-a28d-5cc540c05113',
 'a41471fc-e450-44f4-a202-d4299936d3dc',
 '08af3aea-1027-416c-9bd5-1ccc7ca9bfd8',
 '05786d79-b499-461c-9b0a-04698d65ee14',
 'e7104fae-aa52-46b9-bcbb-799d49f11f51',
 'c68f012c-adf8-4fe5-a0a6-695c258857c3',
 'ab2bd7dd-150c-4dfc-9d5e-f258a46ce4d3',
 'c8418128-4356-4fcf-8b0f-2ef18436f733',
 'bc2d5696-85b8-41d7-aefc-7440a101cdf4',
 'ea55cb23-eda3-4473-93f2-3c388b95b261',
 '82e9290f-3cd5-4ee9-baed-c5dfd7d906c7',
 '553a4307-457c-4ef4-8e63-d61aa5271a20',
 '69a30588-7b05-4227-a772-8b0bac6b7b1a',
 'f9ddf2ee-9109-484d-8ef7-12cfa74e6c45',
 '2f07ceb0-adf9-46e3-b1ea-d602217793ed',
 'a35e9261-fce2-4582-9d57-ea915c971a96',
 '1ff89112-efb1-442a-9caf-de8a1707b214',
 '1a2e4d9e-e2d6-43f0-bde6-0852ddc7f829',
 '1f7441ea-b26a-4a8d-af90-837c8c73da05',
 '5f23380d-b8ac-48ab-8561-0a407e41ea95',
 '3c5191b4-f773-44ec-a585-e58d6a1b788c',
 '12f2e0c7-0258-4d30-9271-184ac6af272d',
 'bc44e6b9-0ff8-4760-b8d7-de0bb36f1fbd',
 'bd4dc3b8-086c-4f9d-a2ae-7f972116aa59',
 '315aa75d-ced6-46c2-ae44-c5fd4e9843ae',
 '39323459-5e3e-4419-8a4b-0a44ef204390',
 '06da3644-88be-4c1d-a278-923312223efd',
 '74a59f05-ee6f-4fe7-a887-e049f0441493',
 '53a37cba-eec0-48ef-96db-01f7fa0f599d',
 '1b6f53e2-8385-40ae-ae54-ddea049f9408',
 '5d2b4be4-ff8d-42df-8108-725c87d4c6d7',
 'fdd08601-f80e-42c6-a775-a0890898da7d',
 '6e72fa1c-b09f-45a4-8700-38e0ce5e9f53',
 'b0417fcc-2176-45af-8e5c-f9382f7e9926',
 '357a8121-c07a-4c90-8cbe-bb7a666a98d5',
 'a96fa86a-e6bb-416e-a8ed-436649facb5b',
 '4d0e1150-d90f-4adc-a5a7-5d73b2a35cc1',
 '340e556e-87a7-40f0-a07c-102a5fc65657',
 '54d32c84-9657-46cf-a24e-0601f658e126',
 'f3c5e4dc-19c7-40d3-831a-e65410ad64aa',
 'e6ce7dfb-621b-4e35-a7f6-45783fbf3be1',
 '3e4f2161-5505-4e30-9568-f60516dfc999',
 '8f347591-3fb6-45f8-926a-6d8f8063c2ae',
 '217fac3c-4bb9-40ba-a089-b703f5626c02',
 '2527dd2e-a036-402a-908d-084b590d932f',
 '225413d8-7233-4f85-b0fa-724bb216506a',
 'e03d2ce1-e0ad-4655-8ba3-f2847d8df786',
 '739b2aae-317a-4cc0-9566-d67caf18cfe6',
 '7e878715-dec5-4aef-9090-2ba048866cef',
 '77d9df08-5b0f-4ead-91b9-77494913ac17',
 '7c85bb0b-d140-4f10-9cda-b6b31f09d880',
 'ce45f871-2174-4bad-b978-5a1eeb559b89',
 'ecbbf905-8578-4a57-93e7-adc76cba4dc1',
 '8844c817-c534-45e7-bf91-c157deffa204',
 '66094b37-a3af-48d7-8006-64b54eae79b4',
 'a368f4cd-52bd-432e-8458-86551a6012f9',
 '1b03c2cd-fd64-4f7a-bc1b-f5e793509a78',
 'e03753fb-7ef4-4b44-a88f-f0bf09080061',
 'fe932fec-f665-48a9-975d-55b2b4bbcc58',
 '25aa0385-92f3-47c5-b2cc-11f7c3c57956',
 '4233df39-672a-467b-bf20-1bd02bf2c0dd',
 'd925b4ef-d6bc-4782-8191-01c3d012207a',
 '79b67a0e-30d1-4488-bb45-1fb146ae6f9a',
 '511d37e2-2e98-4e7a-a0eb-8a72b68809dd',
 '89500722-2535-4d8d-a1a4-74af8d76952c',
 'cc299982-ed15-444f-b479-02ba27f65191',
 '1bac9064-beb8-48f4-acbd-c74dfb8f7737',
 '1e3dd8c9-0e77-4177-b905-f15a902e5b15',
 '08d8204a-fa52-45ac-a5e0-41e55c954519',
 'd94c6370-4ce9-4bbb-b649-e71464ec3a67',
 '9d5a89e3-9c9c-49e0-afb5-01a33612eaef',
 'c8b4cdd5-05ca-43c6-a295-8cc3e4017e1a',
 '1b623818-6e71-4b24-b509-4b8a6b296546',
 'f3c7ccf4-f426-41b7-a771-8422b57ab631',
 '66dadb6e-9246-4d8f-9a6e-d00ba1656cf1',
 '878fa679-4ffc-466f-a30e-dfc7f26e0dfd',
 'f44a943c-9641-4cab-beba-2b3e20ea0626',
 '56e7d971-0be1-41bc-8f29-5f24b88cb7b9',
 '8447030f-c13d-406b-930f-f37a22acaff1',
 'dd8fe47d-5c9e-46c6-9221-9e8bab3e44d1',
 '0f1ac760-437e-4006-814d-32ec7d31fc79',
 'af534570-ec13-458a-ad4e-04eb6105b5fd',
 '0c658c43-f484-41b2-bb32-e60285fa54c7',
 'a955434e-a47f-4fb5-b2f3-2aa7d8acc077',
 '4c8c6625-db10-4606-a18a-fe7c027fcfd5',
 'ad3554eb-4269-4ae7-8914-337997f5c0f0',
 'b931baaa-556c-4817-acf8-ae228849636c',
 '19a35996-bb26-4f81-b97f-d08f152757c3',
 '8004b0b2-dec5-4a5d-aa51-e158880f7310',
 '29a56227-b225-45d4-8a98-da876cfa79cd',
 'd7d5391e-699d-4e74-b272-2440d1f2309f',
 '05cffe70-732b-4772-9164-1083d88063ae',
 '380bc3ff-9f8c-4763-8d92-235b6d7edb0e',
 '113c5deb-b059-48a3-b0df-5e60b606f2be',
 '5b6c5dc8-d007-481c-af8d-9b822e2f70f5',
 'd75662dc-1007-4b9e-8be5-cc30598ae1a8',
 '5df031ac-56bb-4e93-a287-aa526b78c688',
 'b4a6aafc-4165-41f8-9a92-0f52a192754a',
 'c6348a2d-6a05-433f-ac02-9848a6abc1b8',
 'e78773af-0212-4d0d-88aa-73fef74b6161',
 '44011dba-8fbd-445b-8498-b6a4fe77ea5c',
 '2b21f055-203f-45e9-bee4-4d5e0da37b37',
 '6a68dc8c-6961-4ef4-b226-ff29a4e89996',
 '80a21484-024e-4362-9d38-5adf9a6a974b',
 'f16f3349-fa45-4d85-9a77-75391ba96ffa',
 'b5bc92d6-a614-414f-b091-b4e1849edd09',
 'fab1a92d-69b4-40dc-821d-1f2d211057df',
 '6eff6e68-df97-40ae-b96f-44d4a880321e',
 'efa9042c-d9d4-42df-be5d-7ef1f25b9b9a',
 '2a8da4c8-b287-4998-b9b4-e1137eb83d51',
 'f188fe27-3367-4dee-81d9-2ae303ff7128',
 '7f790d74-43ef-456f-9528-677e7da80aef',
 '0d81b0ca-2b02-4d52-bbbc-87a9e8ab93c1',
 'd230bcff-98b8-4943-bc34-2abccebf752d',
 'f10ba482-057a-436f-970f-1baea6e5f8fc',
 'a85b00f1-d96f-44ce-8beb-e5b682e55692',
 '9a4a47ac-2e07-439b-87ca-d75a9efc739d',
 '75a3b83e-9dbc-4425-be6c-bcc947347293',
 'e6619c6a-b9e2-49d3-9f53-f16b16441a04',
 '28d776ce-2770-488c-ac4a-eedc9a9b200f',
 '732380fa-1836-4718-8857-9d02e60211f8',
 'bcd79a09-b202-45ba-ae06-6f3ce20b95b0',
 'b101cd2a-34f6-40a7-b41b-b9a4fa39d0a8',
 '0e5c354a-add1-456d-bcb0-d2da8ac038da',
 '84ef8d7d-b9e1-40f1-a721-d6170352d3c0',
 'ba2ffad5-d672-43ca-8af8-0af98ef75a07',
 '131d93fe-e81c-45a5-a839-cb9d2498ff6d',
 '904ef18d-4cfe-44b7-9aae-0c65e9d44bcb',
 '62c9e40b-85f2-4454-a5a3-31fccb2baeea',
 'af9656da-20a6-4192-b684-322f6fa7997b',
 'd1607a60-4444-4d5a-9856-f614b3023fc4',
 'f6e46d5f-c9f2-4193-8031-305caad474be',
 '821cb2bd-3bde-4e1c-a27c-d0fd5e7b2a50',
 'b96faf9b-5bdf-44b5-a94f-02022be3e655',
 'a17add09-dc19-464b-bd50-4ca1b5de6300',
 '3ca2ce7f-aa61-495e-b976-b723946edc07',
 '3e0abfe9-c40d-4b5f-9762-0f2c0fc0b73d',
 '6effb765-52f8-4d4f-8182-07477775449d',
 'ba52afce-57be-489e-868b-4611630f3b87',
 '4ab6079e-87f9-4c13-803d-05ab5d3f8a3d',
 'e873aebe-ee8d-45d2-8812-0a8164092539',
 '752a7ca5-dfd9-4659-b658-b3a39812ad37',
 '95f369ad-17a3-4032-b5ee-2f10b6fd724d',
 'a7fb9fe6-c5ec-4f39-8433-7521f713c4bf',
 'd2800e16-8ed2-44b2-bb89-68f5255abede',
 '219ec5c5-b0e7-4234-b5c1-fda3d65434f7',
 'ac3a6786-4732-4c79-b3f0-fc1b53f6c79b',
 '4da0d7ba-7740-4a15-b311-4230c76dd6a0',
 '7c3571ee-cb4a-453a-ab7f-66c24123d225',
 '177f0107-bed1-42b5-8784-346130898bcb',
 'b0417fcc-2176-45af-8e5c-f9382f7e9926',
 '6f059fb8-cbe7-4092-961a-73570013f91b',
 'a1b07892-48bd-43fd-9d9e-29ba02775f00',
 '2fa45b66-962f-49a2-8bf6-00285f782f1e',
 'eaa16e89-a7da-48ec-a6cd-5f1b48571f92',
 '0297beed-5731-4a58-8a83-52a6bb250ff5',
 'c3da9b1f-25fa-425a-a0c6-71e21547cbb5',
 'aec551c7-d7ba-40ab-b676-58edf1e448fb',
 'd6e00738-8ac9-4405-9b66-10fb55b1683f',
 '99217cc5-9811-468f-817c-b37be688e5d4',
 'd36c562c-cc91-43f0-b0c9-318eb40a2917',
 'a8288ee5-248a-49ca-a3ab-4828b7561fe7',
 'ff93a45c-a3dc-40d9-a781-049f6c82ed19',
 'fc318929-8a62-427e-8534-1ee49552743a',
 'b4ae7a92-7e36-4342-9f0f-fda242fabd72',
 'e558ba04-03c1-4be7-9da5-26b7468af2b6',
 'f8c4de81-7008-4a99-88f3-0fd66e741b21',
 'd490a09c-e325-42d6-a896-4e7054a3e7ef',
 '65539706-7683-4a49-a410-48671a81baa3',
 '3b0a3031-3d98-4937-bf17-bf31e8a9b88a',
 '3c51b165-554b-472f-a1ab-6839b41d7a6f',
 'c1b064b3-81b9-4abf-804c-4b4be0af3a8d',
 'cd1dcf05-b6d5-440f-a1aa-b16673384de1',
 '2266defd-17b6-40ac-aa66-60aa83ec8287',
 'd2a60d7b-6747-4941-89de-3cfa933f75f1',
 'e8eb0830-2039-4897-86d4-2a389d3032e3',
 '33b7a5c1-a232-485f-aceb-543f25c45830',
 '697a2ad9-7ad9-455b-af8c-e3da3657b642',
 '266353ef-aac3-44e6-9b89-9092a588adbc',
 '38696f38-452c-4d97-b7bf-e32ac567b2b9',
 '3a335b07-27f2-45d5-84a8-09626bf2be00',
 '96bcb3fb-a4a1-40ce-bd2f-bf226f4dd8ac',
 '3d14b947-273e-4ac8-8cbe-4cf07aefaf8e',
 '9902bd96-af42-415c-8cf3-f4a0ca434748',
 '4c2415c3-c486-4485-901e-301496a9707e',
 '409bdd7b-bc90-4bdb-a6c3-ecb8bbfe98ae',
 '79dce4b3-52c6-457d-9023-fd4d66551f01',
 '518d5f9a-d7f8-4cdb-8e7f-382097ba0584',
 '69c52aef-77da-462c-a83c-4d9c20a5b275',
 'ca905397-7b70-4232-8f0f-fcd2b2b59cb5',
 '413fa7be-a7d5-416b-b58e-1b232c06bf54',
 '3be87dec-31d3-49f1-829c-7b58e8e56185',
 'a3ea8564-7501-4495-8722-1c37c3ab0dc7',
 '4b51dc71-1f76-4a14-8743-bfa777d07997',
 '2e3d472e-807a-4ac8-9fd9-d85cb4acaad0',
 'b85f9f6b-c6fa-4526-95b7-c7fe78229ce5',
 '1d2cb531-ed20-43b9-a74d-4e0e453c941f',
 '31e6fcaa-0a2c-47b0-9a12-81627bc8e187',
 'ce7d2fed-a52d-4761-857c-221bb304ba4c',
 '8fbd7710-dd76-4b81-9056-49acff2bab90',
 '45aebae0-fd9f-452a-bf1d-b450e7c07c4e',
 'aa37d225-48b9-4d90-9e94-1acaa99b3c04',
 'bfd55708-7f67-4cce-97bf-a2bee8397287',

In [45]:
with open("items_arts_datashare_oct2024.txt", "r", encoding="utf-8") as f:
    items_arts = [line.strip() for line in f if line.strip()]  # strips \n and skips blank lines

items_arts

['6938dbb0-21f2-44ee-b8da-a1323f5c0dd3',
 '0e3d03bd-bec3-4087-a9cd-b65aeb91786b',
 '520381ab-72b6-4824-8460-e0fcc647286a',
 '498e11e4-d1c7-4449-9937-918d82024a3d',
 '6237ff2c-1854-4a8d-853b-07e10c268dc1',
 '0a2a9035-4398-4af4-9aa9-73b93f0cb234',
 'cd4fa368-7373-4fe5-97cf-f7bfbea903e2',
 'b413fc38-1407-47bf-82dd-369dfca1d0ff',
 'fa043a92-abe5-4e4f-84a8-fe1ee929fd02',
 '324547e5-5334-49f9-b5f4-c69e5f37847b',
 'cf96b0b7-2935-49ee-84ce-8cd2ae39df8a',
 '9ce07b58-9a37-4116-8d9f-3cf67045303a',
 '7ffd32c8-6de1-4e26-ad99-df38d5375882',
 'fc5bbb0c-1e4a-493a-b7ba-7681804949d8',
 '10d58017-3006-4222-ba5b-48d86393ef6a',
 '945e027d-30f9-4b4c-bc76-073836b6057a',
 'f6cf6974-ddbd-4737-ba38-513d1d35992e',
 '9a74d10d-9cc4-4307-9751-22a0c00ff14f',
 '2b861c2a-eded-4643-85cc-8b64b92027fc',
 '9d45cba9-e757-4f9d-a3bd-8aa2a50ac2c9',
 '639ec43a-0bb9-4f33-a164-21850d198eb2',
 '7897f448-8b36-4f1a-83ea-1da22598a555',
 'aa9265a1-ab5a-4400-b8bb-f9d80a869af6',
 'c4ca94c7-7cfa-4f1e-b126-a0db7261829b',
 'aedbbb28-fbe1-4c5a-8932-956a5817198a',
 '0051c63a-af9a-41bd-9c78-96109e4dc967',
 '72e8ec17-6fe0-41bd-8048-b6c4c1b8dd28',
 '18bd3b70-ff25-4440-a212-2e20f7055ec0',
 '6810f0a9-29d7-4d56-8d5a-0ba05dcf67a7',
 '4e142ca0-05a9-4fb7-bcbc-1c1c6ab57f2f',
 '5fa87878-1d0c-4f69-868b-575d09fd46d2',
 'd79cdc63-7b83-4dcb-abc9-5d1997849511',
 '55211759-0418-4041-aa39-5af05f7dd757',
 '2f2dd358-9646-44c8-a566-30e4365bd732',
 '630b2dc0-e042-4f8f-b4e0-c851defdb10b',
 'cce40db0-1967-45f0-9c95-69b57d710089',
 '104a3ca9-8750-4978-853f-44f7b32a9a2d',
 '2b9b8850-cd97-454e-8f83-e68af60008cf',
 '9fbe7d10-f782-4ec6-be08-dd59d7e49729',
 'b5daa452-5303-4720-86ed-d7d6f0d44944',
 'b1e7618d-4f10-4093-8f43-f1c4ba7b53af',
 'ff84d6b4-ade2-491f-a375-b036503f2ecf',
 'adbbe4d0-b9fc-48f1-bf01-e298393f1ca2',
 'ace0fd90-e3d2-4c3a-9b16-2ff5419a64d6',
 'd7f81708-4aae-45c6-95a3-f91d49cc94d1',
 'e750a168-87af-4c44-b976-b208b835632b',
 '7af1db96-54ad-49dd-a345-5d39801ccd1a',
 '0316b2ad-af12-40f0-a16f-758c4185062a',
 '72bcd4bf-5d84-4fd3-bc21-694e195eb3c4',
 '8fa123c1-ea8d-403f-92a6-6632809fb083',
 '650024d5-b8f2-4051-b7a7-78677e0d95f2',
 '693a46db-b3d6-4e4c-99ef-69fb590f2fea',
 '2c8eb965-1d10-4252-bc12-fe747be4881c',
 'e458a928-77ea-43bf-aa92-fb45e1c38f3c',
 'a2e1b31d-e64a-4d3b-838e-d29a134435a6',
 'b9d0fd0c-8b6c-4e69-a28f-60bec966cfa7',
 '8bf19a93-5050-4f16-9de1-2b8d075fad7b',
 '35cea4d4-c8f0-4d2d-b809-49213deb34c8',
 '92bf0e98-f314-48b9-b83a-0e315e3276b9',
 'ac16f812-41f3-4fac-833d-3fb0135020be',
 'a9ae3da2-801e-4f15-907f-8b800fd54677',
 '0ddca034-1754-4369-903f-828e70d8edd4',
 '32a03988-39d2-4e98-8368-39600f890d7c',
 '9d34aa54-9932-48a2-a339-0ebe9470dd89',
 '9bc4e931-b283-4449-9f61-32fab3d7f482',
 'a8a61ef9-6b70-4270-9e42-739350e1cbeb',
 'bf77148e-f610-4b86-9fa7-862c2f03f812',
 '25daa3fa-46fc-4032-b2e6-fe20bb58d1f4',
 '956409cc-8e1e-4f40-aa9c-84545dccc296',
 '257b7bc4-8402-4d94-acb0-ffebb9992e55',
 '2eae2a6b-61bb-4121-be08-245050ca8405',
 'deca01e1-80af-4798-bd07-58db083bdb76',
 'b4c4dc38-cf68-4852-870a-cf0d82db4ab2',
 'a08db84e-b2fa-463a-aec3-4c387824a6b9',
 '14d3d9f3-19d1-4790-8de9-bacf9f3e94b0',
 '8ff8abc7-e6a0-44fb-b27f-1afbf9a0c84a',
 '3b4ae490-a4b1-4878-87c5-36ea4e527790',
 '9bd36f63-3987-4705-98f3-58033a208675',
 'de32f8cd-1783-4021-b6cf-f0d8a929937b',
 '9cd48244-2046-49b3-b366-32b96f266a95',
 '480a348f-c77d-405b-aeeb-731083e374c8',
 '1da97127-2af0-49b0-955a-fdbabdd00581',
 '984d2166-bbef-4fe0-8bd0-ed10b76dd160',
 '0aa0b733-0c9c-4fd5-93a8-44e1cd0a3d37',
 '77ed21bb-c7c8-45ab-b4e2-49ce8b6458e9',
 'a09107be-ba4f-4844-8edd-7f1c0194f050',
 'ac504e4e-3bea-4470-b1c3-9603adc3107d',
 'd80f23ce-ea33-496b-8675-e6db1df081d1',
 'efe19464-b86b-4e30-8541-6cf5311dde6e',
 '9808062d-b7c9-4b74-ae8f-cffcef69c57a',
 '3a66c59d-e677-4e26-88be-c6a926bc160a',
 'e5ac65e7-41d1-444a-ab95-6a4881db4c39',
 'c5477d5e-9708-4747-a01e-d8f1e7d5934b',
 'a5fdfbf2-d348-4766-a289-ce0da5273d17',
 '3b12a631-e13f-4181-84ba-72edc065fc09',
 'b9fb36b9-59b3-4bb6-b7a9-ae22766074b3',
 'ffb40edd-e639-418b-a8f9-a1146a99c65e',
 '397afa0e-1f3d-487b-8cba-2b7eafb50450',
 'e1beda7d-bde1-4ab1-8330-effb9a0d8c64',
 'b6ae4320-ec3f-4348-8312-0f51b92606dc',
 'f8dc59be-c480-455b-924c-22cc8ec1a055',
 'dacd56ad-4d8a-4cc0-a138-01a488586314',
 '84c167fb-d492-4e03-a07d-2bd19bb0c30b',
 '114ee4f6-c0b3-4e84-8157-67c91cfacf11',
 'c09d23c5-de7b-4099-b90a-fc458f8c6def',
 'cc3fa137-a933-4d1b-8a53-062774067389',
 '7e0bf95b-bfba-4ecd-aa85-c3ff2b90677b',
 'ce449d34-5962-48ef-ade2-a8a54defd158',
 'b6f2abe8-9f35-4fcb-9a9c-179b3f801b27',
 '46d006fd-049c-457c-90cb-67afd33eee43',
 'efd0fe53-2384-47b5-a7ea-8b8f0779f11e',
 'bcf50332-8f22-401f-8f47-dce61c7cd7e3',
 '9bc23c27-f08a-4034-a36d-c13e9b17a2ee',
 '7a2269f9-30f2-4e24-8392-c55f47e56d29',
 '18cfb1ae-103c-413d-9585-e5d6aea64d27',
 'c92e03e4-f2de-4164-b2f2-9d2eb1407a8e',
 'ce394480-47d1-4663-ad30-413efe6d99f4',
 'c702e79c-062e-4ff4-b3ce-fb9b23e3edc5',
 '93d89b2c-f2fb-408b-bbc0-a3cd85bfbf56',
 '492f2570-6faa-4393-b82d-0339aeaafddc',
 '5a61a66c-c688-4e8d-b5f3-954ea8f4c798',
 '10a6a1f5-1805-4e80-84a4-fec4c805120e',
 '713952bc-d879-4d40-9edc-64d0e65646bf',
 'e4ebc283-15c1-4ebb-a931-3e4f82b40a5e',
 'a5701d44-3956-4dc3-9965-eb8922637893',
 '46942530-b61c-43d7-a841-1e2d6cf44be0',
 'eb52da0a-72cb-4c77-9e00-25151432f57e',
 '24d4c9aa-10f5-4212-b28e-55025d11a370',
 'db090622-388c-432b-8b41-a83ba59ad7f1',
 '92ec0605-e85e-4d9e-881a-8963754b1226',
 '03df6fa7-401a-4996-bcde-54d9722c8e3e',
 '26a2e774-fcf1-4d38-97a4-84836e2f692f',
 '34a64d43-377f-44a5-9bed-7efd54130ec8',
 '5f0c6d40-bfed-4fd4-aa56-91804851110a',
 'fbe10217-fd86-4287-964a-2df47437e1ea',
 'e10d44dc-d281-4872-a67b-605ef3c8f719',
 'e6f7d797-2eb8-4b14-87c3-b004d8aa6d37',
 '6c164958-d4e0-4130-8a4d-e96bfc4a8a36',
 'c09eb69a-4b27-4f7c-afc8-856884d87903',
 '1241ee28-c58a-4f73-a6de-8631044cdcbf',
 'f8440a02-152f-4baf-903c-120ace4e072f',
 '1c47003f-6ea7-4bde-b869-1178400ea5fc',
 '00e513ae-62f2-4f65-9acb-8fb4dd51c9a3',
 '3912274b-4666-439f-a1be-275dd46fa41b',
 'b64978bc-f09e-401d-9003-65c93f34e3da',
 'ba2bf844-5f5c-4e36-af59-3900a66cc98b',
 '93f035f9-9e2f-45ab-8d81-6e1dca172fc3',
 '3367c6c6-de45-4dbf-a23a-b6a87723e88f',
 '774a82f2-fd02-4415-aa6b-61b045934478',
 '72169575-70af-4468-b634-9c284a08fabd',
 '05ea4cb2-0cc7-4d2d-b1e1-2217e736be70',
 '6014b330-494c-4075-a9e6-644217faa2dc',
 'c648fbea-c3de-46db-9197-55aeeb50529f',
 '69ec4764-ce53-45d8-820c-eedb1ba332ab',
 'b95d8b74-8025-4e2f-a027-738904b8c023',
 '63de8275-be2b-4f36-974c-abe430917acb',
 'e5b26c47-cfec-49e5-827d-a5db50cf5698',
 '988b1cc9-a340-467c-8c47-2b175b0601b8',
 'ecb3c7b5-9315-4393-9c40-a0056b1cd374',
 'd76ef854-1ee3-42e9-8a3b-c534bef9846b',
 'd23218a8-16c5-4365-8442-a888cb48d6c7',
 '8264b348-3995-4cc7-863c-31d8bc3f8cf1',
 '62485861-963e-4cbc-8d3b-cf09457015c0',
 '7721d374-0da1-4325-ab6c-7750ed835ee7',
 '4b2f20c4-d2bf-4cdf-97f0-616891001155',
 '2c7e3417-208a-4ddf-b6b6-cd117217648f',
 '8222b69e-629e-491c-a869-a2edb7f727ea',
 '533a1a99-f385-4aa9-81b8-e41a5e8eeaf2',
 'ffe3e974-fbe5-480f-81a8-a7e1088078df',
 '35586518-7633-475f-b1d3-795d9407fa29',
 '9977b501-8323-4808-86dd-410eb91bea3d',
 '2408ee21-4b29-471b-9fae-7d08104aa8bd',
 '8a05265e-05cb-4e78-a620-80de9343da0c',
 '2d9b4a72-46a1-4e26-a6b6-8900aeed8656',
 '3eaad10d-165f-4eb2-a73d-e329aa54ea65',
 '6ac178a3-9202-49b4-bdeb-7d693c77535c',
 'b2879af1-9be6-4083-960c-ce1dc484c0ac',
 'acbd1944-1d44-4b31-a0a8-f29d67d999b8',
 '3fd7e1f1-f00e-40bd-a89c-1b5844db205f',
 '855ca283-a69d-4a39-a912-52206a886ebe',
 '98b722fb-e1d6-451e-80f5-0e12a99bcd53',
 'ebf998ed-ba29-457d-aff6-3254d155d32b',
 'd1cb9587-5291-439d-9517-77f4039dd59e',
 'd279f9a7-43b7-4d32-8687-95970100870b',
 '3955e985-815c-491a-b6dc-633337fad866',
 '2c1b4d62-5117-4548-90cb-3c497690b988',
 '12429aa9-0d4d-45b6-b6fa-54e5d0049079',
 '24e0e9d4-9277-4be3-8daa-d6578192c0bd',
 '0221717e-737f-492a-9c9c-4f4b37ca2642',
 '16692c3e-a7fd-4aa7-a458-0830c11f6692',
 '817d3a35-fda0-4db7-9dfe-40491a33bc8a',
 '70c50a6c-f3e2-4c27-8fe0-3fbc0cfa6c60',
 '2b1fe670-8e77-42ce-975a-6ac368feb150',
 '6a50f127-8f8a-45cd-9110-9a03e6461ff7',
 'c4a29272-a9fa-4668-944f-7593ef29b632',
 '7b8b6e8a-4dd2-463e-8c1f-57a36b10620a',
 'f8e68daa-fa89-41a7-a75f-63386be1cc14',
 '95674382-727f-4c2f-a86a-9d3e4738849d',
 'e4e81785-668a-44a0-bae1-8fe4e6bde2be',
 '1a602d47-862f-42a6-bdfa-fe33abd5e437',
 'e454e6ec-6562-4fe6-bce5-6ae370d7240b',
 '6dd3e3df-a176-4cb4-9775-e49cf9968c1f',
 '3847e413-0675-4b7e-97aa-dd1ce93f6f21',
 'd9311d69-f289-469e-87aa-b342e9a41ddc',
 'd6171243-b9fe-43ae-9cb8-1c9771311983',
 'cde476ca-ca1b-42c1-be0d-1f9137e7d150',
 '2482be68-d1df-4142-9396-d131d9b5de14',
 '3e043bcf-128b-4d84-b98d-e844404fcc82',
 '91feaf35-a3d4-47b6-aab0-772994100c3c',
 '3095e597-3f3d-4cc3-99ce-68c09a8666bd',
 '6dcac7ce-712f-4c03-8294-5b2db0e9c277',
 'c87ccecf-3518-4908-8973-ffe5f3b34b2a',
 'fbd4ede3-64ec-49d2-8305-a4103b61219c',
 '66bf2bc0-eebf-42d7-917f-1daffdc687d5',
 '2a5151f6-1ab4-48c7-bceb-8e73962d933b',
 '284ecb78-5c01-42b6-8df3-d5ab3ed470a9',
 '92ff8fb9-b24b-4307-b07f-1b8968415122',
 '840a728d-1f12-45ac-9328-cc19925566fc',
 '4c3d8688-ea8d-4bac-8dbf-d9830532a85d',
 '4499ccab-8e66-4143-8f39-b4ab6d2c6796',
 '4d99ed1f-92fd-4012-ae80-dccf60e352c2',
 '3d425b9d-3f2b-439e-a458-57436d0d7de7',
 '77413506-01a4-4663-89e7-ed8e877a170f',
 '0dbefe16-221c-4841-8f6d-d120619b79ac',
 '109e3468-3120-46e0-9e2f-3ae3e86ffc62',
 '528d6495-0ef1-4f24-80df-2e1616f8aa51',
 '87a967d3-a145-462c-8063-8acbbf94739b',
 'caff33a1-5098-442b-bf3d-9b8f893903a9',
 '124d4eac-f166-45b1-95ff-3643754cf1bd',
 'e474f9bd-bb2c-46df-9fcc-bd67ea56c408',
 '3f12cdc0-d2c7-40de-814d-8215eac4b77e',
 '07e826a4-73b2-44a2-a1ff-1e477597ed9b',
 '6af0a8c2-c359-4ed4-b1d2-85bd19865eda',
 '950c7c2b-7c37-4b2e-adce-0ff617eb09df',
 'f4c68e84-2884-43a0-85a5-5ad65e4ca4ef',
 'fe7bb59d-cf0f-46ce-ab80-2c76986a33d4',
 '87463082-d416-4acd-9642-1c0ed5d19333',
 '6415e504-65e5-4b76-98e0-561c6b0e18b9',
 '48aaabe0-56c8-407f-8940-7680b0d51841',
 'be1c17fe-6343-4647-915f-30fc3d490d4f',
 'b50dae87-7e0f-46b7-8b5d-b2ca4ddb5c0a',
 '84aead34-e61f-4d15-8ab6-4ae31f80d41a',
 'a8ccc890-829c-4c33-a7aa-bd7b63f2d54f',
 '1d30789b-bdf4-4973-942d-ab8002b2721a',
 '481b672c-0ba6-413d-8d92-30043d2a3ed6',
 '4db0b60d-49b1-4841-8c32-13d1fb03978f',
 'ddea0b31-c1f3-4074-8e1d-0f0ec0df04a1',
 '66aba6e9-9364-423d-935c-ba0956c4aebc',
 '2c9dc363-76ed-4996-a791-07831e0723f8',
 '88c3c724-c80b-40fa-8092-51a4e43565f6',
 '7bb976b0-cde1-42af-9bdd-481321412a78',
 'a92274f3-7f64-45e4-8c95-6d8ecedb281e',
 'a4aa4a2b-8cdb-40a8-b8f1-c02570013153',
 '720deabb-6dcc-41fb-afad-b00ef5e9223d',
 '28eb245c-6c3e-4296-86ea-58d6b83b32fe',
 '4d1384aa-e75c-4ecf-945a-3b494e7cdf30',
 '45a50693-89f4-4b70-b2f4-7c3c9565d832',
 '745b0403-e1c8-47d3-b0ae-82c342db5ea8',
 'f2168b57-cc51-4d80-b08f-0059a79e55e4',
 '85612528-cb9b-4a08-9878-293c380cc945',
 '7e387cbc-70a1-4903-9815-58ca5decb17f',
 '9f4e23e0-57fb-4af9-afea-93977f4b8027',
 '9dbf9f3a-a2a8-4add-99d7-36b8442a1734',
 '14aa378d-3a49-45aa-960d-a55e1e85894b',
 '9247e377-cf7a-46d6-baa4-36dbc3f1681c',
 '83ca29db-d5e7-436d-9886-e53990eba6b0',
 '72589ead-ea4e-4505-b319-ad0d4b37ccf6',
 '38ffac02-f1f4-4389-b4f7-8199f05a81f1',
 '103b9545-9dfe-48a9-8216-09085b7ec62b',
 '92d8899f-70fb-4040-83db-1d764c69d355',
 'b62e1979-3cfd-4d52-b1e5-03e2451baee4',
 'f08e99fa-6b6e-473f-9ecd-618f0cc57769',
 '3629c598-2607-42fe-a05d-01a4613f7f4f',
 '09ef0172-4041-4fbe-a64c-a39fec9fc32d',
 'fb3b3790-7870-451b-a5ed-af70d1f7a473',
 '457b1c93-7d3c-46b9-895a-905e928d41ae',
 '772c3636-046d-4933-9000-917fa0fdd577',
 '7eca1839-a7be-4bf8-9d8b-cbe9ccd279d9',
 'e825da85-0f1d-4dc9-9ac4-ccf07fea1f8e',
 'f4304656-ee59-454c-9002-1b8622eef291',
 'a36feffe-0763-4d31-b309-a24070d5c818',
 '693b253f-a3c4-4811-8d81-ea9a372d3e2d',
 '3a2c58d6-dd7b-4d82-8782-53d60b2aac81',
 'c327ed4b-bf54-4932-8676-94d1f0270d87',
 'ee0f38e8-2a57-4abd-b0e6-6e6ccc654bf0',
 '2041e589-a162-4ec7-a6a1-fc7dbcf6231b',
 'd1cce9ea-7c32-4c48-9fa7-7865497fbb3a',
 'cb9bc73b-1ca6-4937-b556-ffcf662b4a34',
 'a27182b7-5b33-44d1-a07f-62aa2f294967',
 'e31eb9cf-050c-47ef-9604-35fb70b26742',
 '97fcb2db-2ae9-49c2-b8f9-0212cb88f1bf',
 '1c1386b7-86c0-4c31-8bb5-d96ae87719cc',
 '4d59f719-0f4f-4c89-9804-412f83a82c6d',
 '55a38ba8-e7c3-4644-a521-0d26f67813d2',
 '402131b5-92ce-4b56-b8d8-59dabf25e028',
 '68953134-bb6a-4322-b6fa-da0f82e260f6',
 '62588074-1256-45dc-955d-de98e1160b2b',
 'fbb03dda-4284-4331-adec-0d886fc5dc6e',
 '625c552f-b168-4bc6-b952-57b376ab56f6',
 '2b37502d-f36a-49e5-9c43-e035809f4e8e',
 '97557f4d-9a39-4e29-b927-37585b779b50',
 '8d560850-b818-44d6-9f84-687142ed7d40',
 'c3350dee-8813-40ba-bfd0-36b889605a59',
 'f39af48f-a70c-449c-9854-90f1086b4aa7',
 '92ec27f7-f68a-4ee5-bf28-999d0d034dcf',
 '3fcdb64b-f2fe-4641-9dc2-9d59a462e048',
 '14e0c48b-559b-4be6-b6ce-4117b4268ca4',
 '380f50f2-9897-4e1f-a46f-884e827eaa5d',
 'd7a3a491-482b-4dcc-9501-228e7c2f950f',
 '90688523-83d8-4bc2-aa88-98a4c6f21d66',
 '9adb5103-3a9d-427a-9516-e32377ee8b8f',
 'c5b764c5-548c-4e5d-856f-6f443a376e7d',
 '6e2a82f0-1abe-4181-a292-dec94f86128e',
 '91f11fe8-9554-495d-b655-dc297f8fac3d',
 '09c18873-29fe-4798-831b-57d652fa7ec9',
 '00bac46f-925f-48e8-a296-5e5a7bd4f22a',
 'eafde9d6-453e-4422-93d6-6d9c883f133a',
 '54ae02c2-f217-4206-828e-e7c716f9e373',
 'de201aca-4047-4fbf-a7ff-eb1a1d4cc937',
 '9c9762fd-890a-4586-97d8-54e80e6d2592',
 'a32d22a4-9316-47bb-8ee8-26906d844363',
 '11d9b174-f91b-48b4-9fc4-d9d8ff4df449',
 'd6958c9e-5c40-4ea6-9808-4a778eb57ee4',
 'a5b00f59-4ede-4fc4-b323-f79d50d01491',
 '383708c9-fef4-4e85-b41e-da97d8693075',
 '1355b969-0476-4621-bb8a-ea8956093480',
 'afc41049-6d0d-4741-be51-b735d92d0da9',
 'ddea2b6b-9cfd-42f0-9d9b-1d19baaeec1b',
 '7819a98a-2a43-4e1e-904b-898f3b85fd15',
 '1304317b-695f-44cb-b79a-dafb498ec455',
 '3e49fa03-55f0-49cf-b197-3d9bdd1984bd',
 '9abdb867-7561-4baf-a88c-ccedf5c31c30',
 'b8493d04-80a5-4b6e-8096-acebc5580cba',
 '4a646cc7-4d5d-4ca3-922d-0b07020d8fd4',
 '96ef24be-70bd-4f70-a1e1-106347921c2f',
 'a255d291-57be-4db1-a72a-8db017884a3b',
 '40fac644-5db8-4c3f-9f6f-31bd63e5460b',
 'e994cf7a-7159-4d84-b985-78cd75f4311e',
 '0bb1a611-c262-4639-aefd-65214f2bbcdb',
 'ea4ffd81-d5cd-4611-8b23-254dca286f21',
 'ed0af0a2-2243-43e6-936d-5bb298074740',
 'cd4c5584-7835-493f-bc08-040d880223f6',
 '91552689-20fe-41cf-a7f5-89e6acefbcdc',
 '5234fbdf-603e-4fa0-bfdd-41d473ebdca2',
 'ed5f72df-1186-4091-a970-1289d68f4e07',
 '603fa590-bcc7-447c-8322-3e2ab736aca9',
 'fc78fd95-4f24-4926-af42-cf1bc711fff3',
 '2a737829-c999-4100-8ccd-e9cfae50aa81',
 '5dff2451-853d-4a81-8647-adf1c59b8cae',
 '439f0f7c-4cad-4eb4-b418-59990c3b4637',
 '7e905710-c8da-4327-91f5-fe6115ae0a7b',
 '08d39113-cc56-4c70-a5db-785a31860373',
 '09918744-7ea2-40a0-a33f-98cc783bb827',
 'b3e5c04c-2175-4495-b05b-c380b79dc4e8',
 '9f12d9be-2750-442a-be65-6753cfa85243',
 'b0c4f271-a9bd-4f66-b639-7e8e475f2f54',
 '3ce71e04-3a71-4cc2-ab65-b9dbc0c0f55d',
 '9b7176de-b32d-4697-87c6-52d4024cf160',
 '0478637c-f9a5-4f6e-b62f-b6118af5328e',
 'ab57eacd-7941-4c9d-a20e-ae673e220e6b',
 '3fd9f8f4-3825-408c-84ca-0824eb56e32d',
 '2ca2f821-73c3-45e5-8bb6-f8f55e217764',
 '62a899c6-f0cd-4be2-a504-8c6a595602b5',
 '5e20bede-838b-42ff-85d5-5d8c55f9cc54',
 '730c270d-c655-4087-bd66-95e2a1bb330c',
 '0f35521b-2687-44fe-9d50-d4859e6c23b9',
 '6f8e60e6-6487-4ee9-9f52-7593ba29355b',
 'e8d0cd4d-21fd-409b-bc5d-13e90db50d55',
 '225fd4a2-3540-4933-b490-5333880e755e',
 '233e590d-cf60-424d-93a8-491715ce4700',
 '6b78b93f-9075-4ec7-a8b1-70d61944f6b0',
 '6df1cc78-6984-4e05-b145-4e10012c9820',
 'fefab5c5-7632-42ff-880a-eef9a085bed5',
 '74d8edc6-b7f2-47d6-ad53-7b8d0de0d705',
 'f8dd4c08-07c8-40d7-8a36-23ea6527dd0c',
 '876601d0-d8a3-4241-98dd-102cfecf963e',
 '96a8e08e-59d9-4f56-a5bd-927a663b832d',
 '6cc5a12c-8314-4725-9b24-292556584583',
 '765f2bcc-331f-4129-97dc-2156856cfbfa',
 'd4a2aebd-cb53-4f28-bbd5-f647013f6a18',
 'c6f01a1c-315b-4d35-8847-c263f725abfc',
 '9158f718-f39f-40d2-8edb-3d8ee8fb9e8b',
 '650b2a1d-40c0-46c2-b468-604c3cbb0730',
 '6d8f61ab-acf2-4bd6-b70d-9cb8234b37df',
 'f3652e26-daea-4180-823d-03f059351a31',
 'b9ec6b33-9fc0-4ce1-a56d-d6fe58660ed9',
 '0bc26a0c-e39b-481a-8418-bbe453019831',
 '72a7a795-fe66-4538-bf6c-29e536a7e803',
 '10ceab96-1d77-426b-ba29-7eb1de3319cc',
 '8d7dbf3a-bb6e-472d-b730-8abab93387f0',
 '4f179e0c-df1d-4a29-9a7e-662279dfe91e',
 'b3e3d8db-ab0e-49c7-bd46-20fd9a0c2415',
 '70981f58-898e-4ce9-99d7-8e6be3fd63e2',
 'c9432fb1-9fa4-4bb8-b98f-8277a556e071',
 '1a571574-72c5-4aa2-b87e-748e4e2f209c',
 '2da413bb-7733-4276-8968-843c3efccd88',
 '27913c18-dac7-45a6-9ff7-583a2a631001',
 'ec9ae752-e6d1-4b2c-ac26-361d0f900501',
 'e46294df-25c5-48a8-ac34-19daf8fd2b50',
 '3eaadcc9-1b46-4d77-ae1e-be5fb2a3331a',
 '438dcbb1-215f-4752-8a65-817696a01fdb',
 '6a9c5bb5-054d-409a-9f7c-1c3327fc8ace',
 'a56a669b-4947-40cd-9b1c-da840f453deb',
 '44b70d9b-a118-4881-bb3a-a4609b25aef2',
 '7475774e-cff5-4630-873a-66a45ed83f4c',
 'a9912665-3a4a-4499-8c77-6a561f624cc6',
 'c6e6c597-3522-483b-aa89-59f1f513d1bf',
 '443d8464-cef1-46e4-928f-fc39cf521683',
 'b46458e6-9d41-44f6-9736-d439b01a8c0c',
 '6fb3bcb6-6cfb-44bc-b2d9-fd1597c21608',
 '7c5daaf7-bf0c-43c5-a503-1d9a15508619',
 '435251c4-ffd2-4e57-aed7-218ec6a3b8e2',
 'cea002b7-d6a1-4885-beb1-8991c3ef2e83',
 '3fd24799-0913-42cb-bc1a-c46d6697d1e7',
 '55627481-46dc-4bef-8ee2-c75952495da3',
 'fc48a026-fbbd-4f73-a11e-f06205cb0936',
 '5c7763ef-1822-4a5d-a301-b6748e8d8a12',
 'dabbe6af-868e-44b3-98e3-179a31c579f3',
 'fd1ae692-87e8-4990-bd12-c04f7d9af75f',
 '6e1eaec0-cf0f-4c8c-95bc-1b08734b04a6',
 'd429e9a2-00de-49e7-9ec5-b3d0ac5167c6',
 '5d3257a5-9ede-417d-b255-072e7175bd07',
 '643b6f28-e758-45d0-9114-e9a9760fe930',
 '98eb6ce3-f586-4018-8c3f-6003a550f019',
 '7cd9b1d7-af1e-40c9-96e4-69e1a8277b41',
 '7ceff9bf-6bc8-4d15-98bf-70842ca047b8',
 'a413479a-7087-48a5-ac2e-099bffaa049d',
 '5a7ba1af-bd63-4ed7-97a2-3b1e736af3b8',
 '00a48f80-3deb-4355-ad74-89b977a4acf9',
 '3ab87cb5-39f4-4bed-b1cf-ab10de847139',
 '5b4b15b0-1f46-4f2b-994e-f7df208d203d',
 '2983170a-d1da-4eb9-b9cf-f3c8d1b83f8d',
 'ef72a1c8-77d8-4479-bb2a-8d4313fd2fd7',
 '1ae674dc-ef44-48a5-aaf9-260fc0f5ba71',
 '4f99497b-52c5-4197-ac22-0a390d42973b',
 'dc2f1db8-e4bd-43cb-96e7-bf9ab4720826',
 '4e009000-b738-4a35-b022-5b3e819a9b31',
 '7441f1e8-7209-4535-856d-2844d59ab7b1',
 '69baaa4c-1291-4b93-83c7-98a956c503a1',
 '77781ce3-dc7b-464c-b8bf-77c83587390f',
 'dc30deaf-84b6-44e1-9b0f-bb3eb3031341',
 '5e2fab49-2eb3-48fc-a2e0-d1109e1437a8',
 'e45920f2-f472-4d14-95b2-03a9bebfe7eb',
 '268c4d0a-ee17-4b41-a89e-df7a9de76f04',
 '7f59c969-1547-45ef-80b0-fcc5f2d42ac5',
 'a9943315-0dc1-4f86-abeb-bb68b5f3cf30',
 '057d2419-bf9e-429f-b684-2514f0d1ead7',
 '4119a677-03bc-4a9d-a0ed-3cee54a09d1d',
 'b64c10fb-8320-45f3-bb4f-79d18cf3f1dc',
 '892aca9e-67df-434e-87ca-bce43a15db22',
 'f8b7a5fc-59bc-44a4-92fb-2ad904271f81',
 'e490bc2f-8c9f-4cd0-bb14-27f4685ea318',
 'd578f557-7291-41e0-b673-a7db41b2a9bf',
 'e7c86ea8-2ac7-45e4-9b4d-bfc53077b63a',
 '0e5366b7-a7a6-4505-8c81-09e5cc941eda',
 '80d2e752-4d9e-4803-99df-fcccae6aa4ba',
 'b5f048f3-14fd-4050-b5ca-6e9d9dc9586c',
 '0780276d-c61f-4aef-b9e3-41ea5c0dd96d',
 '7277cfcf-f868-4e73-a8e8-fef95b5a1dc1',
 '7a4c9c53-d653-41e7-a554-b1ab674e1ec1',
 'cbb51828-8d0b-4b57-963d-d40d09ae9a7c',
 '804398d8-333d-4263-99bc-5a9fc65a6fa5',
 'cde5aabd-3acc-4789-a70a-731310b501c0',
 'f01d5c29-c971-4141-bb9a-b4deba68e2b5',
 '5e965b30-19a0-4e65-99d2-af9bbc7a9270',
 '2cd1609b-3018-415e-8d48-89cf4446064c',
 '06cb000b-0af5-4012-9dc8-30adb7124e8e',
 '369e72e9-9144-4f74-8c99-b09b8bb536a0',
 '5a2da438-ce60-4c20-ac29-4c3a5094b3e0',
 '83c2b30b-d4bb-4cdc-b7fe-5786384c50db',
 '39251be2-c3b5-4fec-b4b7-532c85283942',
 '2d4ccd41-c058-427f-a453-884047ffddea',
 '2a363e4b-a8e3-4d73-b74b-c1ab50d8b93d',
 '0e0144cc-7962-4f31-8367-3969e5763957',
 'cd140f37-3d0b-4432-9e6e-599f98aa7993',
 'e169cd79-746c-46f6-83e6-62908bf6fe1e',
 '98437d23-3160-4714-b8b3-7dc874095c7d',
 '7923b124-82bc-4737-9574-3938ea69528a',
 '3eaf05fd-1c46-40a7-bf62-55ac4774aa8c',
 '6fa4918e-3663-4b52-b86c-8222fd9ec4d0',
 '55c2d26b-613b-41c4-b5b4-5204f2494a7f',
 '4321929c-e4e4-4efd-8e59-a5b293dc1aa6',
 'c908c24a-a6a9-4934-8aa3-942ba87b7b01',
 '2a00b65a-2e28-46e6-945f-db1c538ae32b',
 '1173f8e3-1c60-41d0-ac8f-81b8439b181f',
 'eb813e52-7bea-4752-ac92-f5f222c35295',
 '85933e45-60e3-454e-8ba2-6491edb0b4bf',

In [46]:
with open("items_sciences_datashare_oct2024.txt", "r", encoding="utf-8") as f:
    items_science = [line.strip() for line in f if line.strip()]  # strips \n and skips blank lines

items_science

['33abab4d-b941-4bf1-b27f-dc2404873bed',
 'daa15aab-1579-4d53-94d3-6200afcf9225',
 'e6b41690-ae54-4fd3-b5fb-e9d004677378',
 'b7bcb32f-a26d-422a-bd94-0cb58305ab14',
 '7f76afd3-0c78-4dbe-b937-0060aff81128',
 '857329d3-f6c0-4738-8a31-9ead1702ec5e',
 '70291716-bec9-4afb-b863-9981bcda1d52',
 'e8e22326-bba8-464f-8118-c17db718b348',
 '34f058f9-811f-462e-bcd3-f8b7d9d9789f',
 '2fdc71e7-f96e-4afa-a700-b53d5aee737a',
 '9a520471-ffe7-44c4-a1e2-3401edd50a8d',
 '63e43e02-61ad-4a04-846e-685d90d1ba4e',
 '532cb51b-bc1f-4f33-953c-12075cade7b7',
 '8ac6b1e2-b56b-4cf7-8030-fb920574979f',
 '31ef29a0-9815-495e-9e3c-4f0683fc5ddf',
 'c0deb700-63af-4a26-a1bd-76222465fb04',
 'bf092a1a-bb20-4212-bcfc-6a6aed23b87e',
 '419527df-f78b-4b67-a3ff-f0d6ee4ea6d5',
 '750e30c3-1da5-4925-a529-3e8186613bfc',
 '5426c2fd-a134-44cd-b0a7-273ddbebc6ca',
 'ce42f02b-3245-4a5c-a527-aef8ce7791d2',
 '966044f2-14ba-4c50-ae69-f4f19fe32d70',
 '18530eef-aa66-4f16-b3b4-71c74b805560',
 'ccf0c907-e6d8-4d01-a7fb-8631e8a86fc2',
 '9ce217f7-7641-44b8-9d99-2985bb493002',
 '497ef6d3-83f4-4700-b67c-651c9dbb74b3',
 'e6941141-46b4-4fa1-b2f9-0da3615b1a0d',
 'eddd08ab-1172-48ea-931e-d35a06f1aabc',
 'b45e7799-d130-4b29-9ce4-35a471a60f39',
 '8ff2698a-082c-402d-8337-a3f59c6e1957',
 '3d8bdc21-e3c6-44f9-a5bf-3c8c60c42f9d',
 '6778ac07-0780-41a8-bb3e-8905fd194f4c',
 'c40031b4-1105-4282-8178-78026ded57d9',
 '331a993e-de6c-4d88-b4bb-48ebe472c0dc',
 '8a5bc89f-ace2-47fe-a1b1-29b6613c2f23',
 '01ce43a0-f815-4663-87a9-46be5d4916cf',
 'c819d40c-16d2-4457-b059-57d96d88391c',
 '236c692d-264c-4fb6-99ac-2edba347c3ae',
 'c77a1c44-010c-4bcc-a24c-36ac31acd084',
 '6512e39f-48cc-42fb-a8cd-81934a5e25ae',
 '350e93e9-3ce9-4d08-81d5-06ff87126855',
 '1f3658da-3abf-4619-8c3c-61f45b52aa65',
 '9904a1fc-c4b7-4c05-bca8-cb8715ba7af7',
 '8c4ae5ca-4412-4b07-9786-055644bedcef',
 'ad20c575-e4ad-4bea-9010-cfb0637addfa',
 'b01e85a0-add8-4694-8494-60a5c06e81eb',
 '822eaa1a-2175-40de-9de7-79a55465f553',
 '310bd281-b12c-4c87-a570-9925b9839f59',
 '1be7cf2e-f1b2-46e3-bd74-b07e5a4d7d95',
 '96d4b700-f89b-44ef-aa1b-7445b79b5a1e',
 '88356b34-6351-42d0-a215-a545fe353669',
 'eb09a3be-7959-4f32-a883-6ac82a9f28f2',
 '031cdf75-1168-4884-9cec-77cb7322de0c',
 '8273fd5d-38c4-4ffe-9f48-55622abe7086',
 '49ad2766-5d40-425e-ae25-67dacf971cf7',
 'c0517850-ca88-482b-af2e-b8841e63c1f8',
 '19198062-053b-47b3-aead-c29989b8cfd2',
 '80fe840c-49b8-4b61-8704-afd54c2e2459',
 '54c6af31-5f99-4749-8409-ea8acd6ea8d3',
 '97835c7d-3e65-4514-85fc-78cede84925e',
 'd657a331-8594-4f60-ad94-0bfa83001205',
 'c4139eee-eb10-4631-a856-e188e61c1814',
 'e95d0a56-7884-4155-9fb1-529ddc02aa11',
 'f03648a5-c5a1-4805-a742-ea580ba4f1ef',
 '6f0b722c-d954-4349-97d0-c94d3f2ce1b9',
 'c2e36e34-92a6-465f-86d3-33e6f38a2393',
 'e232d2db-1621-47df-bb6d-ea69187de44f',
 '7ef02c9a-8f06-449c-ae58-34b1330053fe',
 'd58acb37-6756-4cd0-a971-c98dba59b744',
 '532b71c1-777f-492e-b7c3-25cba0954faf',
 '8140387f-ae94-4ab0-a7ea-bd0339c748ea',
 '5d36df1c-7a40-4c59-b62e-3b2fbad64867',
 '976fdd23-278e-4a6c-af8a-56fc9b77c832',
 'e232d2db-1621-47df-bb6d-ea69187de44f',
 '7c6158d4-bb11-4be6-b5c8-9d10bf777bd3',
 '0ca72751-b740-4821-8364-1eb1788e860f',
 'b0adf773-19ac-4ad7-8def-2d0dd20d15a2',
 'f343b685-220c-4d7f-9671-0576f97f84f8',
 '19c5df25-73a6-4498-ab73-9e260ae3c198',
 '534a77f9-b84a-420a-9587-7dbf5558d752',
 'de718fd2-5d41-4a5d-bd44-c46b66096c87',
 'b779e02c-9c52-4ff9-8357-1573f37ccd18',
 '2d5223d2-89d0-4eee-b283-a6b7a94d0274',
 'eb020208-0593-4ed9-8b2e-f12c8278ed89',
 '25a19606-c588-4e61-a7e7-0a64f30ee63f',
 'aa2c46d1-9844-4c9a-b2c5-c310ad4a791b',
 '7fbef9d1-c440-49b3-961d-1bf80f8050fd',
 '99a88646-68f8-45f5-8008-07dee2b4ab40',
 '830105da-e5fb-4d04-b211-b22ca0b90663',
 '86c1a9a7-9f6c-448a-9942-8fbefe63594e',
 'aad81a22-49b9-4156-a194-43bf88b1115e',
 '6ed35425-bf14-4d2b-93a1-0a4984952757',
 'fbd1894f-82bc-4fd3-9db0-43b445c42c10',
 '82b2c628-4e01-4139-905f-b300135b09a4',
 '9466bff2-3fec-451c-a4ff-2e4c3ca8fa2d',
 'c29fbddb-1fac-4df5-a45f-8720b91d9156',
 '12259564-61d6-4718-b86a-0cdcbedcd55e',
 'd8199000-be7c-49f4-8f25-1875e40ae9ca',
 'dd09b169-1547-4f0e-9685-5409a150463b',
 '4e89a09e-955e-4997-9750-5e1723ecf187',
 '5331c90d-d458-4789-8877-17499e315c0e',
 '5dc9ff33-6894-4204-8790-9f90ff31e01a',
 'e95d0a56-7884-4155-9fb1-529ddc02aa11',
 'a887382c-5642-4c2d-93b1-b39f94bc7137',
 '63d276fd-d20b-4a39-85b7-fd34160d6dc5',
 '3463b626-d0cd-4c15-a47e-6d514792725d',
 '293f16aa-fd84-4959-94f8-45f94bf1020b',
 '57f5df32-fa7b-4db8-a44a-78709ae3684e',
 'fe78d41d-dd1b-4c8a-a5dc-5d97a4af47e0',
 'c2f4b6cd-535b-442d-8b6a-9b9876078065',
 'a45f5f66-1232-4613-91a1-45913fa9f702',
 '7fa14cd5-661a-4295-8cd0-338c8e66ba0e',
 'b16bbcc4-6a04-42b0-9301-6ac25e646b28',
 'de665351-1f19-4fb1-b28f-c69a8f108739',
 'fe8700a4-69da-48d7-ba79-2e808c42860d',
 'd5db6788-772c-4aa5-be62-7961a08c772d',
 'ad496617-0982-431e-ae39-7f55a06b6b57',
 '75aaf3ad-1c81-4c72-adda-98ea880b820c',
 '3efa6feb-bed8-43a2-bf4d-fecc481de4bc',
 '077e1e5e-e40b-4f6e-a39e-384235d67ce0',
 '4b0ec746-04cb-4aa2-99c8-b0429c187739',
 '575d656d-f6e8-46d9-8844-6c8de4d04c73',
 'db6ee3bc-feb1-4be3-833f-d0551e1c7a93',
 '2e11822a-cd2c-4fa1-9770-98fb596890a6',
 '9dad226a-5ee5-445c-bbc6-f6bd0ace90ed',
 'a714c9b8-4acd-43a2-ac45-68eebcd070de',
 'f5c22db3-a085-468e-887a-3bbc0990ff1b',
 '45fd7bfb-d2e5-4d86-8e41-a9762a4aa9b8',
 '62aa6a27-22ae-4d02-b5c8-f9e88f235e04',
 '1c6bfe23-f500-4b42-b850-d0ec7f603a5b',
 '7d387267-4f00-4628-9e58-b1b731d9802a',
 '12d7762b-7266-4f4e-90bf-20fb7ed091a2',
 '5304a77b-c4ce-4615-99ce-01ff32d0fe67',
 '1ce253bd-55a4-4ffc-9336-b65bf2bfc2d7',
 '3756f951-df59-4c56-8df8-28bcec6224ce',
 'a55678ff-50a3-4df6-b2b5-00f6884ba9fe',
 '99769065-c3af-4f35-9963-2f4ff1358e54',
 '441c8905-cbef-4698-b096-81d25a72d189',
 'd310b1d0-4d8b-43a5-ac2f-f9d6ec066f40',
 '29ec0cd4-07d9-4eac-98a2-6ab9bbf7f49b',
 'cbc5dcfe-27e8-4ab1-b198-5fc4235ea2a8',
 'caf2f9a1-dc67-4614-bff7-909fd67f386d',
 '133365e4-3a67-4419-8ed5-7b6a47af0990',
 'a041a1f7-4635-4721-b18f-9583323a975b',
 '394caae6-2817-4f44-bb06-307f9e366868',
 'e612eaaa-02ba-43e6-a0cc-91de90a47f28',
 '334a8c4f-87c9-464b-a7f5-6ebc1cc2d4f2',
 'c70883ba-5592-41c8-8613-87fcd248d33c',
 '279b043a-0eb2-4ae3-96b0-2e0657af36c3',
 'c9aea3d7-76f3-4fc9-b577-a53b0d753c99',
 'cc4265f7-1555-4426-9c2e-f970c4783b9c',
 'bf37e261-f1fc-42af-84a3-69109cb7a5e0',
 '4e73c438-4bfc-4598-bf72-8fc5d6b58c8b',
 '25eec0ac-1a17-48f2-9f1c-a8899e1c247b',
 '3528c781-8d36-4dc9-92f7-e3365be93c99',
 'ad825a4f-92e2-4579-bd77-e99118c4aa4b',
 'a9c401bc-6148-47c5-a94a-21f413029bdb',
 '1a5ce174-9d22-4e56-98f1-7a12a02812ba',
 'e94e4b66-a3b2-4874-8c9f-7dfc8bbacb38',
 '7dc67d3e-e3da-40c6-aa0b-70d4745c01b8',
 '30e7453c-9ea8-48b4-8e18-f96d0dc62928',
 'f91683d8-6a6f-4903-b1ea-8d1c21c2507e',
 'aa46f4e9-abd6-494c-bdf8-c251ab2c56ed',
 '50e2352e-6123-43bb-bb31-73dce5c3698d',
 '12aeaad2-fca2-4488-9303-7c9264595288',
 '62d487dc-a380-48ea-87ad-0c27744ef908',
 '383439d3-480a-483d-ba1a-75d80b044438',
 '824807cf-9fb0-4a1c-909c-c23a61359d32',
 'f883a54f-46a2-49c9-b491-f92a3e6eb255',
 '0d91650c-4c63-4a5e-b7bf-d29b44900fc3',
 '562d9077-2ea7-475c-81b2-7a17536ed0c3',
 '51cee9a7-1059-4276-a6cf-8e07614d05f2',
 '8414bf3e-27ab-4ce2-891b-3068daa8f8ea',
 '25bbe423-27c9-4705-9e72-db6b956e0602',
 '31d08515-7c8c-4895-b42e-80ccfe2c22d9',
 '68d2e32d-5211-41b1-af17-5e0c7dba7f24',
 '4b806b92-a6e4-4c63-b604-64c398683568',
 'a476b2ad-bddd-4d1a-bd60-d8371b5f31cf',
 '8ec61e48-0475-4a5b-b6bf-21e8a71bfa7d',
 'fb34bc47-1739-4728-bc0b-83eb1ea0d9bd',
 '8f9dff6f-7cc1-4009-8721-1f7435e0c845',
 'c4fa0511-7a21-4745-b716-558b1c153b56',
 '622fb05e-3d4e-4434-8b8e-f78c2e190e8e',
 '75fcff2a-916d-4128-a0c4-dc767d72b865',
 'be95972d-7b11-42bb-aa2e-39f57804f64a',
 '7c06f457-2c45-4566-9d77-85bc440e03b8',
 'f5e46242-98e8-4a43-b06a-7cd089b32238',
 'fa432a26-f045-43ab-b381-f548edc23407',
 'de3b94e7-eff0-40a6-bdaf-53bf243a85d8',
 'd31be4e1-67cd-4f3d-af94-f1cb4b1d8e84',
 'e3eb2725-46b6-40c6-88cf-3ccad62cd419',
 'a1eb71d9-4a14-4369-ae7f-8b555beb05da',
 '5fd96033-afd9-4b7e-baaf-8dfe00f17ca3',
 '83470765-2336-4339-832b-f58c96454fcf',
 'f001b442-a796-4906-b4d6-1e0ecb1e8c7f',
 'e892b915-b2e1-4f3e-8c92-e4a6e8450ded',
 '1b38ab7f-c3ff-4cee-84c9-4d1e469203fc',
 '15f5ec3d-e483-44c4-a3bf-d7566f9cbdd6',
 'adbaf13d-af15-4493-a33c-7d8000dbce3f',
 'dd648da2-928e-4d42-a6cf-b965bd94318a',
 '4c44318f-c29e-4eef-9ba3-358c00720a48',
 '4f026682-e07b-42cc-9b1d-82bdd930a96a',
 '6fcd8108-74e1-4c16-9113-3b718f651bc9',
 'e3088c85-1854-470b-826b-19c41a2109ee',
 '3a4caf07-cea3-47ab-be48-08d2e8445969',
 '6d950dc0-d092-4f51-a9b7-b24d2eeb3bc9',
 '28f2cd08-1e54-4267-a5bb-52ced4ccb393',
 'c4f307a4-3ae1-475d-a747-bb8a773c1529',
 '0c948eb5-d9ca-4d66-8974-70b067187dfc',
 '8b0138eb-ac59-4e63-a330-6b07c7a1fa9b',
 '69678ae0-e9cb-48ca-aa7c-177e451878ba',
 'e0d78c30-c38d-41a5-947c-b03186a50a97',
 '0b5b296c-9a8c-4233-bda3-d0b62638335b',
 '9a285cf4-7f32-4831-af27-2c7a3dba84a6',
 '28414742-f42d-48cb-822e-47711d4d31dc',
 '136c37a9-2079-467a-807a-627943d20f83',
 'eeb449bc-23ea-468a-ae6e-adb0960f3942',
 'e3542b2a-72c2-44cd-815d-ab7a5bd5ecfe',
 '36f77c6f-c91f-44d9-aed8-08d3fd0524aa',
 '0a9ccf4f-f437-4311-8f85-79bc8d1d79f8',
 '52a15f73-8b68-4efd-8e1e-e8d99428513c',
 '64d3f7bf-18af-4089-91c7-435a99f569ff',
 'd851d061-1f41-4a8c-a66a-6b117176748c',
 '44dd71d1-aeff-4a30-bf97-7f223ffd70a8',
 '7cc5858d-2c2e-46d2-b963-08f93cb1558f',
 '0b933edd-01d0-4f85-8ad5-93c4b89c5939',
 'be55f7c2-7bf5-4346-8a6b-c9c97c7a96b9',
 'cf2bb5a6-170d-4eb9-87bd-33dcf31ab549',
 '18ac8b15-3a7e-4691-bebf-1c10d73f31f2',
 'b2e5f041-18fa-4386-aff1-fda1ba319385',
 '253e24f6-c4db-4a81-adfc-c4c119b8ce11',
 '23c0233e-e831-4645-af26-f23b2f386dd4',
 'f7f4c01e-58db-4876-ba34-65f46d7287f0',
 '6aa953ac-515b-46c6-854f-68768735d423',
 '5eac2559-532a-44fc-8506-f44c4082adaf',
 '989591e8-14eb-4223-a907-0cd26d8ca18d',
 '9b470dbc-308c-442b-ab8d-29c2b7437024',
 '04ffd691-4b2b-4700-9ea0-d57783764c9b',
 '487bbdcd-bd20-4a71-bbd5-a5fa666f9925',
 'bf1e7fd2-50b6-449e-b88b-c832d0bb9e48',
 '82d249dc-310f-4a42-bd93-43e30c655c2f',
 '215a62ab-4d76-447a-ab8f-cf8d3ebecec3',
 '6778ac07-0780-41a8-bb3e-8905fd194f4c',
 '65b8480d-7ff0-4e56-bb48-d13bf44de680',
 '1d33c9cc-029c-4e8f-af8d-18e0eb57fe78',
 '4c69743e-9776-4d76-a395-74e0e42c0ccb',
 '701bab57-250c-4e9d-a98d-315e8fe782d7',
 '049642c4-15f2-4787-8a60-c39746a16d17',
 'e458cdc5-f971-4a4c-929d-53ed818938ea',
 'd49585e2-de03-4a4c-a04f-9ce1de563810',
 'b6b4c7c3-8d08-4de7-9c0e-d8f23b25b622',
 '57f7df6c-0a26-4665-a6e7-b091160e05aa',
 'ffa45f26-7fcf-4278-b2bb-0388d5f983dc',
 '2e19e9e4-f3e0-4cc7-b15c-bf2d195abf36',
 'cc13cea1-16b9-4dfc-82bc-bdb1caf8591f',
 '20805a04-7d89-45cb-8338-6f21bb87e494',
 'a7fb5edb-0c88-482e-b9ac-188fe8828124',
 'c3011885-5255-45e5-8373-0a8e1ca28a10',
 'f4dac4c8-ba5f-4d8e-94e4-563c0e7e5dd2',
 'd0bf1a5b-38b0-4c57-a550-7e09b898436f',
 '887b6ff0-4c31-461b-8965-d49feb99bba5',
 '122bf0d3-568c-48fc-9855-b8f3ea464bf2',
 '0b8f0882-ccde-4d22-8e4e-26b283c63d84',
 '24fec4ce-113c-417f-ab81-a3ebbcd21c7c',
 '1ed50612-2a45-46ab-b791-08858197334c',
 'c27a4271-9c86-4145-8a8e-d049ce8c3549',
 '4b3359a4-32e9-4fad-9e7c-de1512d15bdd',
 '532cb51b-bc1f-4f33-953c-12075cade7b7',
 '8472a591-0ae5-418e-b8c5-22c53c0b8bd5',
 '33165766-cc77-4e5a-8fe8-6d68f0019ae3',
 'a52e9ffc-7e00-419a-98f2-f5914dcb2c40',
 '236b277b-1ba1-4933-b319-4b980b27e463',
 'dd7f25e3-27af-42bd-99a8-1956ed510cbb',
 '73631ed3-f813-4cab-b0e2-97e7286116d8',
 '5f18472e-8790-4b3e-b919-e3855ba91bda',
 'ac6d749c-00ae-46de-8a5c-6e9474e83dd3',
 '321b9e1f-5413-469e-83c5-6a6a1fa517ef',
 '30d10e2e-0ccb-483b-b499-8b3c98ad0a2c',
 '88cb3a9d-0a1d-42b4-bec7-43668bac2886',
 '8c98ce01-c9d3-4167-9e3d-2501eb0dc9e8',
 '5b8490dc-25b8-422f-b358-cd1aae8a9836',
 '37dc2aa1-2aca-434b-880b-a9978feabdae',
 '4b6b334a-e6c3-4b20-8d46-a1c89c4cc924',
 '3acfd8c0-d75e-48c4-8fe1-e60884bdaad6',
 '16bf3e00-1ef8-47a0-a3f3-c620f1a14dfd',
 'cba441e7-0d06-4e3a-95c4-c1d0e52ef765',
 'def6eba6-cf1a-4dde-8aee-11b702dd37de',
 '53aa78a0-4720-46d2-95b2-3c99b357cc35',
 'fbb099c2-c083-408a-beeb-57e63f0be132',
 '47d12539-c032-4cd3-bdbe-8ba498420309',
 '4aac74c7-7bf5-4bbd-86eb-7ad4b7005cad',
 'e2727b47-063d-4d21-ad1a-98d3e23bd4ba',
 '7e348ad2-41b8-4be1-8fd7-2c7b59ce1e73',
 'ba852b5e-c62a-4931-ad78-cc3daf22391e',
 '4d20fb92-aa81-4c45-bb29-6027cc4473a1',
 'e946d280-dc4b-4e74-a7db-59e250554e0c',
 'af483d62-a177-406a-9b9b-a7c8ca015e85',
 'd23947bf-ca25-4f34-8b20-840c299ae023',
 '0128655d-a83c-473f-a1eb-780fda328d2b',
 'acc0bef9-b9ea-41b3-bad9-dee7b3bb8836',
 'addf6c0e-a4f0-42e2-b68e-c160d9a1b508',
 'e48217d7-3291-4ca4-874a-a0f0176a94e8',
 '293f54d4-b925-45f6-af74-d34ef4707cfc',
 'b40a46a2-09fb-463c-a3b5-dc25829f831e',
 '40fd7e6a-8a5c-4cad-8eae-bc4915654c8e',
 '89547260-3550-4aed-a541-569540c31d65',
 'bbb9bf95-9456-4e30-9d27-382cd6fd984f',
 '6f15a6c7-41c0-4eee-b7ca-17a5a31f2e90',
 'a4d6e78e-1bc4-43d3-a39a-70e161745774',
 'c4b0b823-3ec2-40b1-b664-73a76724cf17',
 '950ef0c6-55b6-4377-89b1-f7fbab4a5bdd',
 'dd621d17-1c05-4af1-8db3-5ef95c3b5cd4',
 '30e7453c-9ea8-48b4-8e18-f96d0dc62928',
 'da688d1b-2a84-4511-97cc-34a4ad6b4eb5',
 'a276d033-6929-4780-917e-41e0955aecb0',
 'a21023a7-b7ed-4897-8950-2e15307ff870',
 '5f278cee-a308-4dc5-8f5e-72aad9eb05b0',
 '0d71685a-5de3-4ab7-a7c1-828030d9a208',
 'd592b00e-779e-4724-9d38-9306bb607d86',
 '5633d229-d45a-4447-9e57-27e077bebab0',
 '007124dc-30f9-4f01-b286-e25ccd16849d',
 'e78547d3-400f-4ea9-aae3-5fe39cb327b5',
 '9a7590ef-08bb-400f-b746-72b7d3879fff',
 '4b06bf8f-c4bc-4511-9e61-919544cf9ab8',
 '8055184a-4270-461d-8b0a-cbe43025e519',
 '27c720d7-8795-4bc5-b33b-ea98a371f44f',
 '890054ea-a743-4585-a6b8-8bdd0f59fe49',
 '0df0f662-fbe9-49eb-bcae-453d9291d9ac',
 '3c809d8c-f9b6-4094-94c8-6c8e7f86cb92',
 '9fed5b1a-c9b6-40fe-bad2-6660c7a27502',
 '3f4ed848-7f90-44bd-8bb1-48f2433cda56',
 '839f889e-7fc7-4c67-a386-81fba450e532',
 'ae602553-2a02-41d3-8033-244dc18135e5',
 '3988dee4-9c8b-4540-8f1e-6c5321271414',
 '0eedbf48-5a2a-4337-ba22-8b1b0f01645b',
 '9d0cf179-3850-4071-8d07-9fe81174807f',
 '607ba421-198e-4976-9137-f397ca930b18',
 '9d22c9e4-1107-4513-9de7-4da42706ef5e',
 'eee430eb-56d6-456e-ae27-222e47d2e6cc',
 '18973223-b7f9-41e3-a917-1fd3591299ba',
 '50ee3128-423e-43b0-858f-9f76e2dcc179',
 'a97852bb-4c84-4a25-95f9-511e92b6fb53',
 'ae1cc7a2-d7b6-4aff-9a04-67347397faf9',
 '72efa34d-f6b4-4640-9662-ac4eed12fb1a',
 '98e9c505-7b45-48b3-9f1c-3c231d9e3b30',
 '72522281-db07-46e8-a92d-7d90ac5841d2',
 'fd1f6cce-9934-4166-9d8d-26deac59d68a',
 '27c76eab-ec69-4d21-ac46-b1afa43952b3',
 'ccbff0b0-0d49-4b2e-a715-430a00f935fc',
 'd8051ab9-2a31-4700-8d33-595d72afc9b7',
 '2ba9d782-2275-4ceb-8ff9-e0344829100b',
 '1d25ed43-3d6c-464a-b0bf-45faf13ea42c',
 '92a54093-7b17-4d87-a92b-74b1a5c276ca',
 'c015be1a-e008-4243-91ee-1da0c4cf89a1',
 '15215de4-4856-4c99-b774-a2fc3b610277',
 '6aaf4c44-fbc3-4d5c-9bcc-71cdbe3d8271',
 'a276d033-6929-4780-917e-41e0955aecb0',
 '6789398b-c4de-42bb-8fc5-74dfefcf514c',
 '7aa3162e-3a2a-4f7f-a172-862fd5c57553',
 'd2db22f6-f7c5-4db8-86a5-b9c8ce6b8c76',
 '76d73568-41a5-42a5-8aa9-87ec488e62b3',
 'c632d0b5-11c3-466e-a85c-45b7fa93e8e7',
 '6e23996d-2f42-4a24-b60d-54aba6b3ca70',
 '096c757d-f7af-4746-9625-2754d9a26148',
 'da98a763-d2b7-4635-99b7-31b6ba124847',
 'cc58fda2-375f-4572-a251-bfba7baea8fe',
 '89e277c5-c2cd-4392-a6c2-0fae76cf34a4',
 'f0bff12b-6b90-4887-af12-a9f759967b05',
 'b23f0540-5a96-40cc-b5d6-394d1dfeb17a',
 'a71bebe8-7339-4269-87dc-346742d4f2f6',
 '2735bdf4-9c9f-4dae-aca0-a725cf7e228f',
 '96a28380-32c8-49b3-91da-a5c7ba31869c',
 '2cfd90ab-2d5f-40e2-a17d-972db800cf2c',
 '89672523-d764-4c0a-8940-c0675b7d1264',
 'f71f7767-1fd0-4cf2-980a-91ed67905d59',
 '8aee383a-e889-41ae-9f68-5a1be20abffd',
 'e1fb25c9-650e-4f6c-ab30-aa0db918870f',
 'd80575b2-fc65-4357-a17b-f66f16adb3d0',
 '6d3014c2-ae3d-4bf0-aec7-d3a6b4f7454c',
 '294b10bc-4949-4d4b-9ead-a7d68516818f',
 '81447437-b5ab-4025-8c5b-4c07ad79b131',
 '28b2ac1e-4a6c-4b48-be06-939285606bf9',
 '78330371-80bb-48a3-8685-c5d4e4747f90',
 '1ac3e276-adbd-4444-ac8a-73d73de807ce',
 'd2fc1478-cfa6-4c0e-8b55-d5d42a3ef279',
 '6885743a-6288-49d2-b85a-c2e3ea9d5c31',
 'f3187cba-ba3d-4b77-abf5-9bebea80deee',
 '7ad07300-6179-4a8c-ac9a-8b3a8fbd2ac2',
 '01fb404f-992c-4a6e-b297-1422682a2a7d',
 '41d315e7-32d5-4e85-8f33-68b8719c98f9',
 'ea756641-4a26-4818-a67f-5660ae57fee9',
 '945c21a2-7dfe-490e-add5-0504d791f2fa',
 'aac63266-c7d3-4a30-92be-c3b7dce2243d',
 'bc4a8a25-2bc2-4059-8c9b-effbf223e325',
 '8273fd5d-38c4-4ffe-9f48-55622abe7086',
 '4eb397ba-a486-46f1-a9ac-5874800d859e',
 '2c0ce538-545a-4aec-a70a-40b0aa0d84c6',
 'dfecb00b-9887-4e1d-8582-a5549935d19d',
 'f454f652-abaa-424b-b796-9054674e45e7',
 '07da4e0b-05d6-4608-ae3c-8179850e55a4',
 '14d0fce8-a11e-4b20-bb99-a7f5298dcc85',
 '70e06815-c88f-4a0b-bce3-5005f2133fa3',
 'b960987b-f5dc-4356-9768-e21d02ad5afc',
 'b968f403-72d5-4957-bd52-18e69b033b37',
 '34f1d7b9-3cbf-4517-a02d-d1fdcfaaae2b',
 '1e257fb7-244d-4f2e-8ee5-3f86903c8681',
 '85d6677d-58e4-45bb-a8f2-197eb34b49d6',
 '089b4bd2-2263-4da2-b11a-bd4e15163554',
 '6e4f1228-8cfc-4fec-9830-05df6a6b8dd4',
 'c77b4b02-857d-4a4b-bb91-99aa0e9cc154',
 'b6b31881-178f-4d73-8711-44bdbd5e65a5',
 '53cdad8c-a843-42cf-8c45-a16a233b3599',
 'de67e7b0-919e-442b-b40c-1b9adf368fd7',
 '6e2c35f7-77bd-47ed-bab9-81e4490ee3e0',
 'babc80f9-6b1c-471b-a934-e364a0015219',
 '0c752804-1d06-40a0-a33b-df65dbe19cd1',
 'c654c9f1-ee60-49aa-85b2-f5e9f997da9c',
 '11c57d44-2516-43c4-aabb-41860f9cf884',
 'ba6b2730-cb8a-43fe-9e8d-8fa162faba67',
 '49631bd5-6be3-444e-9ecd-afbb8f629296',
 '625b3ae3-3dc6-4ce2-92bd-94ec8c06cd33',
 'c453e153-7b18-4b3d-ae05-69ef3210e4c7',
 'ac159440-0c73-41fe-a06f-9fabc8728c22',
 'cb7d7d79-c7bc-4b02-b993-6ebe2e037ee9',
 '7e6a0cab-bb2a-4a83-a363-bd036ccef931',
 '034da596-9034-4036-a35a-de020c2806f0',
 '1f9c0432-80e1-4528-8c19-016193e46984',
 '162ccdae-895c-4281-86e1-bb27eaac68b3',
 '95a4e3b6-054a-41f9-8a1c-6425b6d63431',
 'ffbba3ac-c4a4-4ca1-ad60-78735fe236d9',
 '941242cb-cd31-45aa-b329-364e5ed33b7a',
 'b00ff486-e017-4b94-8a18-b7dc654b3fa5',
 '78a4b4b9-4ed3-4de1-b907-e248f0acbd74',
 '3feda27c-b12c-429c-8129-430c1d79262a',
 'd4b9973c-2780-4f52-af8b-6ea0219560fb',
 '5b273964-4a1f-4808-bdfe-364b9881b781',
 'eba771bb-99fc-4e88-afd5-640bafe8a2d9',
 '6b428a9c-79f4-462d-9b41-584b0231dcef',
 'e98337bc-f7ce-4998-8f91-c87fa8f8a307',
 '53696535-829b-45da-9552-164cead067c2',
 '2dc50b67-68de-4562-8cec-641601169665',
 '7189efe5-bbe7-4de5-a836-42b8fe2077b3',
 '5991aadf-4cf9-4f65-84ea-54965fe28c9a',
 '0318d1b0-aebc-4afb-aa21-9c5514f50112',
 '6fc12674-86c4-4e44-ad4b-426b945d94f3',
 'ee7d8c99-74f8-4a8d-80bb-9d73fbf58b7a',
 'b6f620f5-768a-4158-af35-881964c65906',
 '64f0d743-36df-452e-89e3-cada043eeb79',
 '5c380a2f-fbfe-4bf8-83c9-6abdd8f4ada8',
 '1723de59-9603-42b5-8e22-a881874ff77b',
 '8b09b9db-dd98-47f1-a175-a58649e17603',
 'da515f61-0462-4baf-a0d0-af99c51b2e0e',
 'ab0b3e03-9b61-4edc-8b7a-69244e94468f',
 'b3f792d0-d00a-42b3-8b01-e7d1598fe969',
 '92bed677-f639-4b55-8f37-ad5b17ead5a2',
 'bc5e1cf0-3a23-480e-9c96-60113eec6a3f',
 '2fecdabc-8e54-42ce-8b10-489e73b5e4b2',
 '7a25075a-5af8-49da-99d5-474836e32853',
 '25a07916-c49a-4e5e-8166-db08bbf1ca24',
 'f4e328c5-a988-4a7f-9288-bd57088217aa',
 'fae8d47d-0648-4188-989d-114c3172d3f8',
 '1c73087c-42c7-44b9-bc93-2ca6961c360f',
 '633dd10d-3084-4051-bbf2-798619c9d8d3',
 '2f8b3fa5-552f-40cb-9229-b9d20dc062ea',
 'ad3192b4-16ae-44d2-841b-64c4409f28e4',
 '055584ca-3fed-49a4-922e-2b8656bf9d5f',
 '17415ff8-cb85-42e4-9151-5ffc2a917300',
 '46807768-75e8-4ef0-b3b7-1664e2bb0417',
 '7a84ebaa-bb82-425a-aa34-959e4cb2093f',
 '8a1371b4-8404-4430-9d7e-b5be07275704',
 'fa4644b4-d41c-42f4-b3e8-2082e081cf30',
 'e668c87e-b352-4ecd-ae94-bcf79cdf8b57',
 'aa4d6c42-f82b-4bad-b71e-2a5c7195707e',
 '3c9d8084-a9e6-4d7f-beb8-6867b9dd7541',
 '707eeff3-a4da-4e5d-815c-9ff585f9fd9a',
 'e65a4ccc-f600-4840-85d6-18140dcedc82',
 'e22a342b-fa8c-4058-a231-07d92c235db6',
 'c484cfdc-4295-4429-b790-dbe8551f2622',
 'd89c6250-abc5-4bd8-9859-bf9d1189c62c',
 'df1140ed-8761-4ec4-b473-d6d9ae8bc088',
 'cb5bef34-4016-40e8-b424-8477394660ab',
 'af7e6f9e-9080-4243-af7d-a3737f48eb4a',
 '1868beba-c3e5-4d75-85aa-942d588b8d9f',
 '5ce06c3d-afcc-4738-9f67-91abc5b303b7',
 '6df3ce3a-7d63-426e-9cbe-8bc089b7b058',
 '0e3d1da7-b7ba-4e24-a0a3-760e2e74361f',
 '6b8820ef-b98d-460a-8979-9ac561686a82',

In [47]:
with open("items_thematic_datashare_oct2024.txt", "r", encoding="utf-8") as f:
    items_thematic = [line.strip() for line in f if line.strip()]  # strips \n and skips blank lines

items_thematic

['d2fc1478-cfa6-4c0e-8b55-d5d42a3ef279',
 '9aa976fb-6e7e-4ac9-87c6-439efc9b75d3',
 'ebd7b9bf-63bb-4941-8b2c-c32a7c9b0276',
 '971bf000-9b4d-4b11-b6cf-51750e9e051d',
 '97835c7d-3e65-4514-85fc-78cede84925e',
 '439f0f7c-4cad-4eb4-b418-59990c3b4637',
 'b20446df-1f61-4472-9992-da5182f5a8f2',
 'e95d0a56-7884-4155-9fb1-529ddc02aa11',
 '1af232b7-d511-4cc0-9bbc-96d6fae75aee',
 '3f6952a3-13c3-4a72-a424-33cab60f1644',
 '7fb3b4c8-6847-4c68-b900-13c71e4e5a21',
 '4c69743e-9776-4d76-a395-74e0e42c0ccb',
 'd228a88a-f77d-4585-99cf-cc42265c2071',
 '1f9c0432-80e1-4528-8c19-016193e46984',
 'a9f26f49-43fe-4cb6-ba77-ed1e83512737',
 '15e82917-56ed-4282-99ef-7f211bf87f9d',
 'd10f0b0a-e3ee-4416-8420-0781815c3bd2',
 '40ad4ad7-d731-4ddb-8b5a-51350a0dd731',
 '57f7df6c-0a26-4665-a6e7-b091160e05aa',
 '7ef02c9a-8f06-449c-ae58-34b1330053fe',
 'e998be81-fd5b-496c-b352-f90407716848',
 'd9353382-628c-4085-bebd-11bdcfde39de',
 'd0bf1a5b-38b0-4c57-a550-7e09b898436f',
 '534a77f9-b84a-420a-9587-7dbf5558d752',
 '47b99bea-b844-491c-a108-d89dab72ad51',
 'b21ccba6-5544-435e-bc0c-1fdab12353aa',
 '2d59d91b-a296-4b26-9cef-464fc44d4473',
 'fbb099c2-c083-408a-beeb-57e63f0be132',
 '8c4ae5ca-4412-4b07-9786-055644bedcef',
 '7f76afd3-0c78-4dbe-b937-0060aff81128',
 '1723de59-9603-42b5-8e22-a881874ff77b',
 'a276d033-6929-4780-917e-41e0955aecb0',
 '8659fd28-cb61-42e5-8941-d0bd23586769',
 'b2b7c860-a153-487b-b153-76f72b546138',
 '966c06c8-7e0c-4576-ae04-66dd0a48bf69',
 'b28b0873-31ea-4464-b7d0-4b6e4d80f09d',
 '0fd01dbc-1cfa-4d94-9bc5-21227d10f5e4',
 'c015be1a-e008-4243-91ee-1da0c4cf89a1',
 '0e3d1da7-b7ba-4e24-a0a3-760e2e74361f',
 'c0deb700-63af-4a26-a1bd-76222465fb04',
 'b11eae2e-02a9-4d4d-883f-9a97cd48eef3',
 'f71f7767-1fd0-4cf2-980a-91ed67905d59',
 '695cf685-09e5-4bba-b86d-220533ae6da3',
 'e9d0e889-2742-42b6-b522-7df82bcb95e0',
 '778027f4-743b-4aec-aa7f-bf75ed21df4a',
 '4550c9fe-4d00-4e9d-b967-69c76c78a6ef',
 '6ce6c777-4f2d-40fd-97ec-d33ef93883f9',
 '7e6a0cab-bb2a-4a83-a363-bd036ccef931',
 '6225e771-954b-44fe-a6fe-db3e00061952',
 '49631bd5-6be3-444e-9ecd-afbb8f629296',
 'ee58ca92-22e7-4b41-8fec-65fa7045118b',
 'dd56f044-b8c9-4bf7-89ce-d6fd84e411ee',
 'b2749176-e3a8-4786-bb5e-35bcb9869ca5',
 'dcaae666-857b-45b0-acfe-3c1ed1a04d57',
 'd6293ff3-6dc4-4161-b14f-621b6326973e',
 '0c4caf7f-ef40-4831-8550-48fe876a8b15',
 'ad20c575-e4ad-4bea-9010-cfb0637addfa',
 'fa4644b4-d41c-42f4-b3e8-2082e081cf30',
 '439f0f7c-4cad-4eb4-b418-59990c3b4637',
 'de8bf49f-1553-4da6-8912-dacc42a1650c',
 '54ac5fa5-ba09-42c5-8119-5917ea229a1d',
 'fb567d5e-666f-49ef-800b-4396b2a9a48a',
 '2cfd90ab-2d5f-40e2-a17d-972db800cf2c',
 '45e0d03b-e207-40d8-8a73-b8ee43ec0f5f',
 '67bfda21-cb4b-43af-b816-377894c1a2ff',
 '2ca46575-74db-40eb-bf35-847ffc29d774',
 'df3ee9ac-a90f-463f-9200-53b75a994508',
 '712282c4-e29b-4248-b75e-3da8d844f555',
 'f9ef954e-1271-4144-ac7d-8bf8a71ce272',
 'dd862928-0cb2-4fa8-aa38-635579328933',
 '441c8905-cbef-4698-b096-81d25a72d189',
 '3f4ed848-7f90-44bd-8bb1-48f2433cda56',
 'e77eab70-fd1e-4aa3-b63b-e06720056112',
 '8118b63e-4625-443f-a177-6acf28dad8bd',
 'c9aea3d7-76f3-4fc9-b577-a53b0d753c99',
 '89e277c5-c2cd-4392-a6c2-0fae76cf34a4',
 'a5c81ea8-4940-4da2-a6d5-30cfa05cb915',
 'fc26f2f7-76a9-4d4a-a243-ed885cce0ec8',
 '75aaf3ad-1c81-4c72-adda-98ea880b820c',
 '04ceb771-4c59-49b8-9798-cb44f73dc393',
 '904526b0-1e46-48b6-9b93-3ff39d155c68',
 '94ead366-8778-4bdb-8636-219cef94ab26',
 '4f026682-e07b-42cc-9b1d-82bdd930a96a',
 'ccb1ac38-04e0-402c-bf81-1da929e4d2b1',
 'a4d6e78e-1bc4-43d3-a39a-70e161745774',
 'e6941141-46b4-4fa1-b2f9-0da3615b1a0d',
 '2fdc71e7-f96e-4afa-a700-b53d5aee737a',
 'e4d41684-5459-4dd4-bcc6-5862ea2ac864',
 '1ef5192d-9e6f-4996-a3a0-74952074620e',
 '427ddfe5-89aa-4b10-ae2c-5b3b6d776372',
 'ce00c930-a213-44e3-87c1-d093438e10ff',
 '2f8b3fa5-552f-40cb-9229-b9d20dc062ea',
 '729478c5-afab-4b6e-a296-a984ee9dc340',
 '37761d36-0fe6-4cce-9f42-4ccc27a8d6c2']

In [48]:
with open("items_support_datashare_oct2024.txt", "r", encoding="utf-8") as f:
    items_support = [line.strip() for line in f if line.strip()]  # strips \n and skips blank lines

items_support

['a8427d6f-ae38-42dc-8631-365e709f79b3',
 '4d9d1f69-9dda-4eb7-b3c5-4c6b3c454c2c',
 '8407e11d-0489-419d-9a8e-2176beb339a3',
 '1e8cdbeb-fad8-496d-9ced-9ddb1501ae8f',
 '37965637-dcdc-4309-a83b-893400466ac8',
 'a01d08ed-d07a-4933-baa6-c2b158e333f6',
 'c1264cd6-6bd1-4e0b-9d60-3536e861c2f3',
 'fd8cefc1-8a92-44dd-ba37-617992ffeea4',
 '02f77652-d9dd-4f96-ab04-778bce3d12ca',
 '577cea5b-4291-4b6d-b686-be0f21b1288e',
 '526e7fc5-3b40-4082-be55-4c5381bcd3ce',
 'ea31ce42-b815-42e5-8fbc-e67de98222ed',
 'd58bf0a3-a5da-4f86-bb7d-805bf6a814b4',
 '54ac5fa5-ba09-42c5-8119-5917ea229a1d',
 '0037d8c3-f792-4106-a255-2594846e9a97',
 '9a0da7a8-8324-48fa-a31f-c620b762d34c',
 'efe57d9c-cd7f-4195-87a8-ff98ff0bb9e4',
 '40961da8-2be5-400a-a7fb-a32854fdd2ac',
 '747da831-5bb6-4701-8298-7b8857668ffb',
 '9bf40b37-a9e7-428c-9bf6-9c13f288883a',
 '217d495b-0712-4824-a36e-2b11b88cc0f7',
 '58910db2-b0e1-4f02-95df-51368b775e6d',
 '61e6836b-ad45-4ac6-b825-a58064b8dec8',
 'b80afaff-b3cb-4f72-87c8-25d148ba1801',
 'e04feeb5-9d28-49c6-89df-73cd2a565267',
 'd799b541-ae13-4f3b-a47e-ca1689ff36a3',
 'e8ec356a-b259-4b2e-823f-bb6f531b1343',
 'a4afc434-9f38-4cfc-970c-45828acb452d',
 'abe824ba-ffaa-45a6-9f8c-49e52c6eb86a',
 '237da2c9-2cc8-4532-a3ee-03f56f4be404',
 '75f6d74a-e1ac-47b6-b14f-b29d349c5904',
 'b5f52cb2-8b92-4c5b-b0aa-3957c31b9331',
 '3df9c800-f870-4832-9fbb-19761f475ed8',
 '3f0f49f4-786b-4628-848f-a064660d7b51',
 'fa5594b0-6f0b-4eaf-9055-d318059a5fee',
 'f1356c8b-91af-4d11-bb29-4a11a8d9eaaa',
 '273a03a5-c97e-4151-8dbf-80ec282154cc',
 '26431ee5-4809-4237-98e5-8f5b1e96788f',
 '002b8129-dd32-4804-a436-a733bcfdd319',
 'd5e24c3a-d6f1-412a-8f50-e990bb2bb653',
 '0c955320-1f86-403d-bf60-0c3018c57903',
 '21010b11-8d29-4f89-a638-d41460c49c36',
 '4811f4e9-92a1-4006-a3ae-b1663ad26d33',
 'ce767835-6406-44a9-85dc-b487376ff3c9',
 'e416e748-59b8-435e-b5f4-6f592d0557b0',
 'dd8cd0ea-eac0-4645-888a-bcaf82cb7b45',
 '300a05d1-e37f-4523-a847-aab070c2a569',
 'c18a7671-2111-41dd-919b-bed767c0b747',
 '3c7e34ef-1be0-4e42-8475-debad6eea398',
 'aeebc763-01b5-4f8f-9ee5-3e93f23f0f6b',
 'a43efe66-e6b4-4906-8c78-bc937cedd5c6',
 'a10284f8-759c-44aa-bb14-851ab5e69ac4',
 '8ada599d-d15e-4c2d-8d7d-0bbdc6155f5c',
 'c6af7320-a322-420d-aed3-98dda6e0f82e',
 '7eecc59a-4c34-402c-9218-14c3ca16dd7b',
 'a5932adf-dda0-416c-acb6-945731832b37',
 '5ebcd5f0-62d5-4952-8124-d3cd0d56511b',
 'f3b45ae2-754c-4cf8-92e5-92038344d86d',
 'ea4732d9-2940-4d63-898f-547c4bf3cc22',
 'b8341413-e6b2-4874-b3bb-c4a07facfd25',
 '5d87607f-6868-495c-ae0d-709ef0c11262',
 '38c0737a-8553-407a-a859-c2afc141e085',
 '72cea5ba-561c-49a2-950e-63b714e24240',
 'fdd61b92-4e43-46b0-8ed1-f1d778095840',
 '900c7330-470f-4e04-8be1-ce80a7b37275',
 '053d6ac8-a124-44a1-88c1-bbda50dbbe1b',
 'f99cfb5b-7c77-45c3-ae71-a780577fbb59',
 'ebc1952a-0365-4c64-8a7e-7e48f2fc4d45',
 'b888550b-01b0-4fdb-942d-dd38b8b7e6cf',
 'f53d9046-5983-493e-a948-1520a2e6afc6',
 '073ca271-d184-4f6b-818a-5315df204695',
 'aa84f441-3449-484f-b7f8-7efec104c961',
 '58efdece-bd90-43c3-9748-210c600199ed',
 '9a0da7a8-8324-48fa-a31f-c620b762d34c',
 '33623bfb-11fc-4339-8a8c-edf428f800f6',
 'd58bf0a3-a5da-4f86-bb7d-805bf6a814b4',
 '72f1781b-b2cb-4b5c-b350-74a1c0dbc5df',
 '5ae61c12-28c4-4c5f-9273-17bfe12fbbd9',
 '00e8a245-ee8b-4967-8569-2b66725d8ed2',
 'a9b78995-0d0f-40d3-bb40-ccdd10c1f3c3',
 'b9de6f41-e93e-4e53-918c-cba09f053bdf',
 'f80fb011-bc72-4dae-b5c0-f495cd3f2dbe',
 '7ec1d8b0-fe3a-422b-b23e-e2b766731860',
 'f6af36bf-2bb4-4ff4-bfca-8dd2e88da889',
 '3ae17f35-e424-44e7-9bc0-e6cc024af91a',
 '8483d276-e1eb-4c28-bfd8-496653eb2eec',
 'de25e18c-2f70-4692-a30c-8f4af7b846fc',
 'a01d08ed-d07a-4933-baa6-c2b158e333f6',
 '31bed5aa-6be8-470b-beca-00390e423fa8',
 'f752aad3-1419-43f4-bf54-9123cb602bbd',
 'd26d8bd4-8a2b-4f43-b6eb-6979faed231a',
 '87be3da4-a126-4189-876d-9efc2aba5765',
 'b76baf82-687d-4a23-82aa-074d0daa2717',
 '96d328c1-e4bb-4233-9bb3-2234da474bf6',
 '0b0cb740-6d24-4ea6-a022-812710952b57',
 'a5c81ea8-4940-4da2-a6d5-30cfa05cb915',
 'dd6c11d2-e52d-42e9-a7a5-45dca44ba214',
 '8c18c58b-f435-49e4-af54-dd33d7c4d581',
 'b4059454-8072-48aa-8129-b6637b0fb471',
 'e9718176-f3d5-43c8-b556-b6a178fa1f59',
 '63bfeed6-fce0-4109-a32d-fdaeb2bb843b',
 '39874917-2b1a-4180-a7cd-c2153f9a54e2',
 '72827998-599d-472e-9386-3889d6e2ee13',
 '6d852048-f5a6-45ff-9265-09f5b084435e',
 '8d4935aa-7e95-47dc-873d-d98f5a57d1fb',
 '59b1087a-2dbe-4028-a168-5301d8a13620',
 'efe57d9c-cd7f-4195-87a8-ff98ff0bb9e4',
 'd6c92750-af1d-44bd-a49e-fc53ca9cbd2c',
 'c47b17e8-cca7-4b9a-970e-5b8474e15417',
 '7c23bfda-0795-43e5-8ec2-2f9ba4d02ad8',
 'be3e63eb-6612-4d07-b5b6-ec891023871c',
 '053b5c39-7e3e-4bf4-9c88-5d199fe33522',
 '040978cc-cdd1-47a1-83e4-5702d9c907fb',
 '983a5324-0204-424a-9195-4eae796daf60',
 '831d0240-7f7d-4b7f-936c-df507a35d8a1',
 '8bbb4730-818a-414e-a2f1-793c8d4eb897',
 '7122695b-905b-4551-8097-f749f03b78bc',
 '273a03a5-c97e-4151-8dbf-80ec282154cc',
 '75c7a89e-9f8b-4a86-a854-81c7c2f2ce3d',
 'abe824ba-ffaa-45a6-9f8c-49e52c6eb86a',
 'da620d90-a784-44ad-abda-ef286e5cb97d',
 'cc1ab0f8-a31a-4a08-90de-752ef670b3ab',
 '56344e59-194e-44b2-a53f-d45c932ff22c',
 'e697f0ab-b5b3-462c-893e-4efe0fc9bb1d',
 '3df9c800-f870-4832-9fbb-19761f475ed8',
 '45e9bdbf-8d20-42d5-a1e3-9bd791cbd352',
 '60f6ec4b-3397-43d8-ab56-738a416dc1e7',
 '8480ded8-0085-4cf2-a6cc-0ba9948af277',
 '5ebcd5f0-62d5-4952-8124-d3cd0d56511b',
 '76edaef6-e2e7-43ca-aa41-0964d2308c73',
 'c6af7320-a322-420d-aed3-98dda6e0f82e',
 '90c243fd-8219-4ad0-8f49-92886d1f1281',
 '77344842-cd8b-4a98-bd22-10f5ac9900a1',
 'a5ddcd09-a81f-4316-bc38-727329853820',
 'de15120f-d407-461c-89ee-7ee54e276f96',
 'a3ceac39-6e07-4653-90d4-bbaf77834be8',
 'b8341413-e6b2-4874-b3bb-c4a07facfd25',
 '8f9c0a04-f64b-476a-8168-da65b0e09d67',
 'b349008f-0ce3-466f-95e4-7525a0962ad0',
 'b372b543-0083-4e3a-a977-fa54d5ddcd9f',
 '929ee826-bbb2-4531-85a5-fd044b624d47',
 'a0582e2c-5ba9-44db-8e1f-544c269967b9',
 'fd95acf9-2089-4f51-bfdc-f3870353096b',
 'db4697f0-df28-46af-ba7c-e3df5722064f',
 '01e48788-f21c-4985-825b-5f0358d91d3f',
 'e4d41684-5459-4dd4-bcc6-5862ea2ac864',
 'ca6b0a42-425d-4307-968e-55738ac3528d',
 'f14def5a-2a82-44f6-a5b3-32a1087b17b8',
 'b45bdc81-fa14-4ce4-92e2-abaa8778079e',
 '0dbbbcd7-51bf-4025-abf8-54c4f936bfac',
 'aa723a60-f684-4af9-bea1-488dad3a7b4b',
 '1e552675-efa3-4c01-b02b-c6dbd6655a10',
 'dcd1bb12-6b5a-417b-9bcb-6b7a6cf32ee4',
 '5a4f4577-9e37-4b4b-b79c-1c99ba80d3bb',
 'fe9b0670-1005-4ebc-8042-891ef3db6658',
 '901ab7fa-2465-4be2-8777-1549c0cba23a',
 '9dcc2683-1b6b-4bf2-952a-0deadacc984e',
 'f833a4f3-3c9f-4c27-b127-cd1a75f8115b',
 'c5ff7bcb-a81a-446b-a9f0-f78d530246ca',
 '79d101d8-a79e-4cf3-8d04-4b32668174bf',
 '208a2564-0485-4c09-b7cf-2587e7a4634d',
 '53edb387-fd55-4c15-9cfb-95f150540a26',
 '9c65b5e0-3122-44b8-974b-0bbcd936d72d',
 'a6b83b6f-8b3f-422c-bc8b-78d939dd6d8d',
 '95121b68-3164-48d5-a30c-b991b75e9797',
 '23d2529a-8ae6-4c8f-af01-969085f9d9bf',
 '7f486648-d424-4be4-a576-112c09d02505',
 '62efa4aa-81bc-4953-9e1f-32041395adfe',
 'a0cb873b-b371-447a-a5da-9b616f3a6455',
 'e85de177-880c-4ad6-a026-2f47b4246a48',
 '1df640e4-5d35-4eb6-a46e-510ef5286a95',
 'b888550b-01b0-4fdb-942d-dd38b8b7e6cf',
 '4c4a389e-6fbf-45f6-919f-7a4d9ce8464b',
 '1c2789f8-990a-4101-9209-f82e1ae65c13',
 '537b0761-1969-42d8-9ed5-e93d18cb293e',
 '4646ce3d-f799-4729-b433-eccb4a6bb753',
 'd7e58573-d2d9-429e-be5a-0f8f2a7bc090',
 '6eb58210-cf1f-445e-a152-c8caee029171',
 'f55fb0e0-be70-4914-91ea-db287bc7cdb7',
 'e5e6876e-b1d7-4657-83f2-22f8aae84e6a',
 '639580c3-983b-473c-88e1-ec061046c6ff',
 '1fe02e91-384b-45b4-be0d-4ec52d6c23fb',
 '6e61d151-eeae-4ebe-874a-739b6caa6f3f',
 '95f2136b-7f3a-42c2-84cd-a9fb72f4c007',
 '1e8ed72b-2691-4485-9095-e34451daf0da',
 'a4d4a827-7615-47d0-b762-5be18d307d41',
 '375f1f45-aafe-4c5b-9982-c37df17904c8',
 '80bc59f5-4e16-4cdd-aacc-b9b56668f2a6',
 '830e992f-c9ea-42f9-8c52-e1cf7485b086',
 'e15f2c76-cc95-43a4-af5b-152b497d8a62',
 '49b0b040-2b3c-449d-9c9d-9640d55cb7f9',
 '3dc81acc-ae58-4b2f-b5fa-0c7ab2a626c1',
 'f35379de-9a94-418b-bcac-01b5f98cd638',
 '69754c34-cb5d-490a-b81a-5fbe48e860c5',
 '33c39510-e8c7-4a10-91e2-6791e7dc3f61',
 '6662480f-8972-4052-aa5c-53d8db1c9e0e',
 '786afa55-323f-46d7-8336-e15584b00873',
 '1190caf2-37ba-4c93-9d1d-d8ef98cf2fa3',
 '2bcb9857-020a-4ac6-8aa4-a8cd7408c274',
 'db807ea8-d583-4e89-bfbc-cd86f383d66e',
 '5402ae27-b1c3-450a-aa8d-52ccc121074e',
 '88dc6947-a483-401d-80ef-1514d3ac965b',
 'f070ec05-02dc-4450-8f16-039c7b2d2062',
 '4013d62c-0407-4884-83e3-2a647e3b2d8a',
 'c93da964-ae94-43dc-a914-3cc4777a5b72',
 '075fb7e3-7886-4b64-8552-d2c03dc7e44d',
 '0f40d752-46dd-4b8a-9c3c-607f1d3341f7',
 '60ca62bd-db46-4609-8f98-5264a9e7ecca',
 '707dad3b-a244-425a-b0bb-260189ba412d',
 '00874572-cca6-44da-b0f3-b6d799d08c4f',
 'ce9a2fc5-e131-46ab-ad5b-b8132ef0d541',
 '748149fd-ccd9-4a03-a8ff-eaf3874ee29b',
 'd10f0b0a-e3ee-4416-8420-0781815c3bd2',
 '96166f1b-8e82-4adb-8eaa-81da36e66860',
 '783f7ae6-3142-442c-be20-38ceaa4b4990',
 '556ef8b8-726e-4056-98a9-63d84f419e4d',
 '3cd03c2c-f07d-4e96-a163-b1ebce195e8f',
 'e6d152f9-e81a-4b3f-906e-d8261ef81d1f',
 '188c15ff-207d-45f4-a305-43cb994f6f56',
 '67f4ec35-6fbb-4d90-9f53-5094ae61f6a9',
 'cd254284-b08e-4895-9fd8-429a5a47a27d',
 '2b582611-a362-4b58-897a-c5b0746159a8',
 'ac3c0750-38db-4507-94b3-7f1006819b74',
 '3125f76d-5bb7-48a5-8a7e-70c7a614ffbe',
 '60e78fbc-2556-45cf-bac0-0861b45838ea',
 'edd94b70-b2ae-471d-a115-1f3b74dddbec',
 '00b647cf-38bd-491d-b2ad-b0f18b87390a',
 '83c0dc34-c8f2-4f38-88f6-8fd4250ffe5e',
 '2f561ace-f903-4308-b200-1037d5d000cb',
 'c5ff7bcb-a81a-446b-a9f0-f78d530246ca',
 '17826022-6234-4690-9f5a-3471463072e1',
 '8da27ea5-da64-4cf5-b1e6-9a994d0ea0a3',
 '6e65718c-6f6f-4a16-94cd-8a3e0fc0fcf9',
 '7f486648-d424-4be4-a576-112c09d02505',
 'adec6bb2-076b-4d25-9e2b-1533e2d820cb',
 'bf5a4832-0e13-4c39-bf24-16f05b024120',
 '599b8731-7cec-4b37-8432-e41a61cb4b2a',
 '341bda12-c536-4d81-a887-18786134cd42',
 'cb96fc96-7876-4152-beba-ab64c337d57c',
 '6bc1a431-8801-4039-9f71-0be9cfaa66a7',
 '7af44541-f908-4991-91b5-0d5f5c6e71f8',
 'f5a6ffbf-5474-4ee0-a68c-f730528176f9',
 '848d373c-b80e-4eeb-b359-59d71118b7ab',
 'ab0764d7-2835-4c00-8cf8-809ffb8a3570',
 '19524fc6-0564-4ca6-8401-8218d0b02589',
 'f14def5a-2a82-44f6-a5b3-32a1087b17b8',
 '0dbbbcd7-51bf-4025-abf8-54c4f936bfac',
 '51688b50-b894-4bfb-b58a-3e32adb72315',
 '8b414a19-992b-48cf-9106-eabf41b50111',
 'cbad0aca-a5b5-4767-ad08-d1a7f34b060e',
 'e3ddbb15-2fce-4787-a32c-273b67ec1274',
 '0d00057a-26de-476c-b493-5377db11d28f',
 '23958b4f-12e3-4884-9214-80e179c23657',
 '7e8bb20b-43ef-4e73-a9ae-2430719a923e',
 'f3438252-73a7-42c2-bb69-409dfe67cdea',
 '7754a148-b2fa-43b4-b413-d86e5febd429',
 'e5e6876e-b1d7-4657-83f2-22f8aae84e6a',
 '56501a2e-b2d5-430d-ae92-390798ac5ab7',
 '1e9c78c4-6b26-46fa-8b28-3b5cc9748661',
 '930ec93d-2956-4588-8368-11c289b4c0c8',
 'e88061e3-894f-4fbe-9b83-c44badce52f9',
 '0647d7be-8142-4eec-b8ad-efcc4652ac00',
 '097c4c55-27e4-4ad0-9815-b257f2b64594',
 '859321b2-ab99-4687-a6a5-939584b029ff',
 '49591bf2-d420-4933-bd97-4845b6ff7bc8',
 'a4d4a827-7615-47d0-b762-5be18d307d41',
 '9ad03453-7325-4c5d-b1b9-162f72c32e2e',
 '925d95d5-7d53-4784-9727-0c760b91a392',
 '95f2136b-7f3a-42c2-84cd-a9fb72f4c007',
 '99c83c1d-00b1-41ca-ad6c-e61fd8d8c47a',
 'e6c8ce59-cfbd-44fa-bca4-93b559b8490b',
 '7aa740c2-e87d-494f-948f-81437c11c59d',
 'a84bd1a0-1118-4c90-9d54-17536df253e9',
 'e21e6ee1-7eac-4274-91f4-9f4c1e0ebaa0',
 'b4dc2269-f601-4348-905e-0a331a220fca',
 'a20496bd-ea44-42a0-bf3c-b8d5c31d1c86',
 '66582139-5b61-4e40-9297-ef8f33d4c680',
 '01f1ede5-2e60-4e88-9e2e-8c96748c6d5c',
 '4c4a389e-6fbf-45f6-919f-7a4d9ce8464b',
 '5f5a9035-e5d3-4f28-b3d3-857ab40471fb',
 '0e47b56e-4ccd-4bdb-ad95-03f9d8aa2f40',
 '6554eb37-2b60-4335-a863-546a7f2b466f',
 '237aebfc-a094-436d-b69b-6f5a440802b7',
 '0235eb1e-63c3-4b42-9668-aa094e598a94',
 '366ff369-b170-42db-b35b-1dc368960e4d',
 'f480080d-4893-4647-8f21-02579f06f70a',
 'e15f2c76-cc95-43a4-af5b-152b497d8a62',
 '03544813-9b05-4c27-9cd2-3730a9944d72',
 '272f9c53-84b4-49f6-a3a7-be5956f861b1',
 'a648320f-c869-4fab-a165-069fb7f5bcc5',
 'ffcb2d9b-08c2-4526-8193-28f8ae32edae',
 '77522ee5-2e53-4256-9d72-b3245fe3477f',
 '9bf9609d-662b-4121-a80b-1dda0ffdaded',
 'dd3226bd-c237-48d2-a838-b337fee0be06',
 'f945ff6a-c1db-45d2-b47c-a36bdf26fc49',
 'be77945b-838e-4472-b22d-3f15053697c7',
 'ab10af71-6dc3-4465-8862-badf0c91176a',
 '3cd03c2c-f07d-4e96-a163-b1ebce195e8f',
 'ca6ed025-6952-49d4-b6ac-a5424d13d756',
 '924f7375-6dea-4c48-9d63-3382cfd52146',
 '53822247-1223-49c3-ae9b-688829c52848',
 '748149fd-ccd9-4a03-a8ff-eaf3874ee29b',
 '00874572-cca6-44da-b0f3-b6d799d08c4f',
 'b0133f21-4b17-4472-addd-1be5427ed422',
 '52fd0c19-bc41-4dfe-ae09-a44c0c1e2b4b',
 '075fb7e3-7886-4b64-8552-d2c03dc7e44d',
 '0c9deace-e1ad-414b-a728-f36f3bd93f89',
 '54e706cc-85b1-4ea8-9dbe-ccdf97f9c94e',
 '6cdb8953-af05-45ec-a841-64a31c1fae86',
 '47b99bea-b844-491c-a108-d89dab72ad51',
 '6e468d11-5fe0-43ec-98a8-5c9d9c7d7b99',
 '57925487-3af3-4908-8936-981489ba81c3',
 '65bb8a61-915d-4025-bf24-ae91f3f29763',
 '2e58dcb8-0814-4a47-b2ea-38c4b9fe0b3f',
 '06d0e027-e4ca-40b0-95e4-f13d89e415ff']

In [49]:
df_datashare_collapse.columns

Index(['dc.contributor', 'dc.contributor.other', 'dc.coverage.spatial',
       'dc.coverage.temporal', 'dc.creator', 'dc.date.accessioned',
       'dc.date.available', 'dc.identifier.citation', 'dc.identifier.uri',
       'dc.description.abstract', 'dc.language.iso', 'dc.publisher',
       'dc.relation.isreferencedby', 'dc.rights', 'dc.subject',
       'dc.subject.classification', 'dc.title', 'dc.type', 'file_name',
       'collection', 'id_in_file', 'dc.relation.isversionof',
       'dc.description.tableofcontents', 'dc.source', 'dc.title.alternative',
       'dc.relation.isreplacedby', 'dc.date.updated', 'dc.date.embargo',
       'dc.relation.replaces', 'dc.source.uri', 'dc.date.issued',
       'dcterms.subject', 'dcterms.isReferencedBy', 'dc.contributor.advisor',
       'dc.relation.hasversion', 'dc.contributor.author', 'dc.description',
       'dc.description.sponsorship', 'dc.relation.ispartofseries',
       'ds.withdrawn.showtombstone', 'dc.relation.isbasedon', 'dcterms.rights',
       'dc.relation.ispartof', 'dcterms.isReplacedBy', 'dcterms.publisher',
       'dc.description.abstract_clean',
       'dc.description.abstract_clean_word_count',
       'dc.description.abstract_clean_lemmatize',
       'dc.description.abstract_clean_entities'],
      dtype='str')

In [50]:
df_datashare_collapse["id_in_file"]

0       49dbc9e1-eeab-411b-8510-080ceb5dccfa
1       ecfd3009-d585-4b1a-9137-6b7460379b94
2       619bb04f-94c4-4eb8-9511-b2dfeaa3412a
3       e232d2db-1621-47df-bb6d-ea69187de44f
4       9bf808da-4a87-4bfc-a885-4f53bf7531fc
                        ...
7749    95b48a67-d9d6-497b-92f8-eca8ba9eb13e
7750    5a681507-5f98-4b33-821a-f7a14e27e6e7
7751    f5a80a20-a794-45e8-8f67-de9031a43037
7752    163fe91b-f71a-4337-9baf-8bfe1ddbb9ae
7753    2a18550b-fdaa-47a4-94a2-5359ae0266a3
Name: id_in_file, Length: 7754, dtype: string

In [51]:
df_medicine = df_datashare_collapse[df_datashare_collapse["id_in_file"].isin(items_medicine)].copy()

In [52]:
df_arts = df_datashare_collapse[df_datashare_collapse["id_in_file"].isin(items_arts)].copy()

In [53]:
df_science = df_datashare_collapse[df_datashare_collapse["id_in_file"].isin(items_science)].copy()

In [54]:
df_support = df_datashare_collapse[df_datashare_collapse["id_in_file"].isin(items_support)].copy()

In [55]:
df_thematic = df_datashare_collapse[df_datashare_collapse["id_in_file"].isin(items_thematic)].copy()

#### Saving the files

In [56]:
df_medicine.to_csv("df_medicine_datashare_collpase_20260401.csv")

In [57]:
df_arts.to_csv("df_arts_datashare_collpase_20260401.csv")

In [58]:
df_science.to_csv("df_science_datashare_collpase_20260401.csv")

In [59]:
df_support.to_csv("df_support_datashare_collpase_20260401.csv")

In [60]:
df_thematic.to_csv("df_thematic_collpase_20260401.csv")